### ISSUE TITLE
Support Pardot / Salesforce form handler

### ISSUE THREAD

**Issue by aloco** [verbb/formie#1015]
### What are you trying to do?

Hi,

a customer requires us to use Pardot form handlers, as far as I understand, these handlers are just kind of "endpoints" where you can submit your forms to. It seems like form handlers are an integral part of Pardot automation flows.

### What's your proposed solution?

It would be good to have this directly baked into your plugin. Any chance that you add this?

https://help.salesforce.com/s/articleView?id=sf.pardot_form_handlers.htm&type=5
https://help.salesforce.com/s/articleView?id=sf.pardot_form_handlers_integrate_form_handler.htm&type=5

Thank you!

**Comment by engram-design** [comment]
One or two people have asked for this, and while I'm not a Salesforce/Pardot guru, from what I know it makes sense. I _think_ all we need is available via the [APIs](https://developer.salesforce.com/docs/marketing/pardot/guide/form-handler-v5.html).

My main concern is field mapping, and how we handle that (if at all).

I'll see what the best method to add this is!

**Comment by aloco** [comment]
I can see your point regarding field mapping - maybe in this case, forms just get forwarded to the API, editors must make sure that field names in formie match the field names in the form handler.

Let me know if I can assist

**Comment by engram-design** [comment]
There's two other integrations that handle forms: HubSpot and SharpSpring. HubSpot is easy in that we can query the fields used in HubSpot-created forms, and map that way. SharpSpring is _crazy_ weird in that you need to send a test payload of a form in Formie, for it to determine what fields your Formie form has, then you do all the mapping in SharpSpring.

I hope it's as easy as HubSpot, but otherwise, yes we'll just have to make it more of a "data-forwarding" type thing, but again, the other reason for mapping is so that we can translate values into their proper datatype. For example, mapping a Checkboxes field in Formie to a text field in Pardot will convert values to a string. If you change that to a Checkboxes field in Pardot, then it'll be an array.

Without the other half of the equation (the destination fields) there's bound to be errors unless the fields and 1-for-1.

As I said, will investigate!

**Comment by aloco** [comment]
Hi Josh,

do you have a rough timeline for this? We need to decide if we wait for your implementation or start implementing a custom integration for the current project.

all the best and thank you for your efforts!

**Comment by engram-design** [comment]
No strict ETA sorry, but likely in the next month.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.11",
  "...": "..."
}
```

Then run `composer update`.

**Comment by aloco** [comment]
Thank you!

Any chance to provide this also for Craft 3?

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.6.14](https://github.com/verbb/formie/releases/tag/1.6.14)

**Comment by codyjames** [comment]
I'm so glad this got added just in time for a client project!

One thing I'm noticing though is that when I add an Endpoint URL to a form, it saves correctly (and seems to work), but on reload the Endpoint URL is empty. So, I'm guessing the value isn't correctly being pulled in to the field.
