### ISSUE TITLE
Can't delete useless Form Template

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1059]
### Describe the bug

After setting a custom template in `/admin/formie/settings/form-templates`, I can only edit it and can't delete it.
I'm running in devMode and the template is not used in any form.

### Steps to reproduce

1. Set a custom template in `/admin/formie/settings/form-templates`
2. Try to delete it

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.2

### Plugin version

2.0.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
The only other thing to affect this would be `allowAdminChanges = false`, but I'd be surprised if that's enabled for you. The other common one is that it's used by a form or a **stencil**, but you mention you've checked that.

You might want to check any soft-deleted forms as well.

Otherwise, there should be no other reason you can't delete the form template

**Comment by romainpoirier** [comment]
I have doubly checked, `'allowAdminChanges' => $isDev` is correct. I didn't have any active form linked to that form template BUT you're right, the form was hidden in the `Trashed`. I didn't remember that there was also a Trashed for Forms. Thank you!
