### ISSUE TITLE
Assign form during entry import via Feed Me

### ISSUE THREAD

**Issue by belkin** [verbb/formie#1074]
### Question

Is possible assign a form during entry imports via Feed Me plugin? I've tried to pass form name, handle and id but none of them have worked. 

![image](https://user-images.githubusercontent.com/3419659/188397186-4d4bf56a-b724-40ae-b30d-8c0cea22f0e0.png)

**Comment by engram-design** [comment]
We didn't actually support importing Forms via Feed Me, mostly because of the ability to create them would be pretty impossible via a feed. But it's valid for your use case to be able to map against existing forms, which is what we've added support for.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.10](https://github.com/verbb/formie/releases/tag/2.0.10)
