### ISSUE TITLE
Change button/submit text via setFieldSettings

### ISSUE THREAD

**Issue by jamiematrix** [verbb/formie#1106]
### What are you trying to do?

I want to dynamically set the text on a button on a page using the `setFieldSettings` method but it appears button or submit aren't in the docs to make changes to.

### What's your proposed solution?

Add basic support to change parts of the submit button - even if it's just the text on the button.

**Comment by engram-design** [comment]
You can't use `setFieldSettings` because buttons aren't fields, and they are also in the context of a page. Unlike fields, you can have multiple buttons in a form.

The recommended approach is to use [Theme Config](https://verbb.io/craft-plugins/formie/docs/theming/theme-config) for this, but it doesn't really handle multiple pages well, and you can't set the text of an element (yet).

I'll give this some further thought.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
