### ISSUE TITLE
Hidden field twig values aren't rendered on the front end but visible field values are

### ISSUE THREAD

**Issue by fvwanja** [verbb/formie#1117]
### Describe the bug

There is a difference between a **visible** and a **hidden** field. I use the same field „Default value” but only the Code in the visible field is being rendered.

In https://github.com/verbb/formie/issues/957#issuecomment-1169389151 @engram-design states that „Twig functionality isn't supported for a Hidden field”. It's just confusing that **it is supported** for visible fields but not for hidden fields. Why is that?

Please fix and apply the same behaviour to all of the fields or add a hint for the user in the backend like „you must expect a different behaviour for hidden fields – Twig is not being rendered because...”.

### Steps to reproduce

![Screenshot 2022-10-11 at 16 14 29](https://user-images.githubusercontent.com/90781427/195115874-427694a8-8b86-41b5-bff6-e74d9dd16fe2.jpg)

Field 1/2 (red)
1. Create a new field „Single-line Text” from the section „Common fields”
2. Set the name to „params”
3. Enter the „Default Value” (see below)

Field 2/2 (blue)
1. Create a new field „Hidden Field” from the section „Advanced fields”
2. Set the name to „hiddenparams”
3. Enter the „Default Value” (see below)

Default value for both fields:

```twig
{% set parameters = ["utm_source", "utm_medium", "utm_campaign", "utm_id", "gclid", "fbclid", "msclkid"] %}{% set value = [] %}{% for parameter in parameters %}{% if craft.app.request.getParam(parameter) %}{% set value = value|merge([parameter ~ '=' ~ craft.app.request.getParam(parameter)]) %}{% endif %}{% endfor %}{% if craft.app.request.getReferrer() %}{% set value = value|merge(['referrer=' ~ craft.app.request.getReferrer()]) %}{% endif %}{{ value|join("&") }}
```

Check the rendered output in the frontend. Add some query parameters to the URL: `https://example.com/?utm_source=foobar&utm_medium=medium`

Console output should be:

Field 1/2

```js
document.querySelector('[name="fields[params]"]').value
'utm_source=foobar&utm_medium=medium'
```

Field 2/2

```js
document.querySelector('[name="fields[hiddenparams]"]').value
`{% set parameters = ["utm_source", "utm_medium", "utm_campaign", "utm_id", "gclid", "fbclid", "msclkid"] %}{% set value = [] %}{% for parameter in parameters %}{% if craft.app.request.getParam(parameter) %}{% set value = value|merge([parameter ~ '=' ~ craft.app.request.getParam(parameter)]) %}{% endif %}{% endfor %}{% if craft.app.request.getReferrer() %}{% set value = value|merge(['referrer=' ~ craft.app.request.getReferrer()]) %}{% endif %}{{ value|join("&") }}`
```
![Screenshot 2022-10-11 at 16 17 16](https://user-images.githubusercontent.com/90781427/195116628-d28aea12-a43d-4dc5-8aa7-a3c0e3fb4033.jpg)

### Form settings

- Multi-page form: Yes **and** No
- Submission Method: Ajax **and** Page Reload
- Client-side Validation: Yes **and** No
- Custom Form Templates: Yes **and** No

### Craft CMS version

3.7.54

### Plugin version

1.6.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
There is indeed a reason for this, and it's down to how people use dynamic values in hidden fields. For non-hidden fields, when you enter Twig as the default value, it's compiled at render-time, as you've found. But some people don't want that for hidden fields.

Let's look at two different use-cases:

#### A hidden field with `{siteName}`
This is easy, and it could be evaluated at render-time because it's a static value. You'd get the value "My Site" as the value for the hidden input, and that's not really changed as you submit the form.

#### A hidden field with `{myEmail}`
This is a little trickier, as we're referencing another field with the handle `myEmail`. If we evaluate this at render time, the value for `myEmail` in the submission will be empty, so the value for the hidden field will be changed to an empty string. This will mean that the `{myEmail}` shorthand Twig will be gone from the field.

What we really want in this scenario is to wait until the submission is submitted, and then evaluate this shorthand Twig on the server, when we have a value for `myEmail` from the user, which we then use that.

Hopefully that helps see that we're in a tricky situation where we need to allow for _both_ use-cases. It could be argued that non-hidden fields have this same problem, but we just don't cater for that, as using hidden fields with values populated by other fields is far more common. This is alluded to in https://github.com/verbb/formie/issues/957

To resolve this, we might have to add a new setting to hidden fields to split the default value (value generated at render-time and static), and another setting for a "calculated value" when is evaluated server-side, and not at render time.

As for adding text to describe all the above, I might find it hard to condense all the above 😅

Hope that makes sense?

**Comment by fvwanja** [comment]
Hello @engram-design ,

thank you very much for your extensive answer!

As I understand it: **Twig code in hidden fields will be parsed on form submit.**

I can see the Twig Code in the browsers inspector, nevertheless that Twig code will be parsed on form submit. That is by all means a bit dirty – since every user can actually see the written source code (see attached screenshot) – but it does what it should, only at a later point in time as I would expect it to do.

![Screenshot 2023-02-07 at 11 14 17](https://user-images.githubusercontent.com/90781427/217216697-ca5b2960-6643-4d4f-84d5-18b6a83f3bb2.jpg)

Thank you very much for your time and patience! I will close this ticket. ❤️
