### ISSUE TITLE
Clear all fields on submit

### ISSUE THREAD

**Issue by clsse** [verbb/formie#1131]
### Describe the bug

Is there an easy way to clear all fields on successful submit?

### Steps to reproduce

Fields are not being emptied of valid submission.

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax

### Craft CMS version

3.7.55.2

### Plugin version

1.6.14

**Comment by engram-design** [comment]
This is (or should be) [done automatically](https://github.com/verbb/formie/blob/378a74ac64dd2ed347233cadda0f8efcb87656b8/src/web/assets/frontend/src/js/formie-form-theme.js#L640) using `form.reset()` as a JS function on the `<form>`, unless you're redirecting away after a successful submit.

Otherwise, we can either figure out what's going on - because it should be doing that, or you can use the [JS Events](https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#the-onAfterFormieSubmit-event) to call `form.reset()` yourself. But again, you shouldn't have to.

**Comment by engram-design** [comment]
Closing due to lack of response.
