### ISSUE TITLE
Cannot use `setFormId` when using form handle to render the form.

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#1144]
### Describe the bug

`setFormId` does not work while using the form `handle` to render a form. It does work when using the form object.

```
{% set form = craft.formie.forms.handle('payByEmail').one() %}
{% do form.setFormId('formie-form-pay-by-email') %}
{{ craft.formie.renderForm('payByEmail', { formClasses: ['form'] }) }}
```

Does not set the custom ID.
This does:

```
{% set form = craft.formie.forms.handle('payByEmail').one() %}
{% do form.setFormId('formie-form-pay-by-email') %}
{{ craft.formie.renderForm(form, { formClasses: ['form'] }) }}
```

Workaround could be using:
```
{% set options = {
    formAttributes: {
        'id': 'formie-form-pay-by-email',
    }
 } %}
{{ craft.formie.renderForm('payByEmail', options) }}
```
But then the integrations such as ReCaptcha throw an error as they are still looking for the Formie generated ID.
So working with data attributes is the only solution right now.

### Steps to reproduce

See above.

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

3.7.54

### Plugin version

1.6.15

**Comment by engram-design** [comment]
Right, so that's a fair point that if you're doing things like modifying the `form` variable, you'll need to pass that into the render function. I don't want to say that's obvious, so maybe it just needs to be documented better. I know you mentioned [disabling rendering via the handle](https://github.com/verbb/formie/issues/1145) but that's not really an option for us.

This is greatly improved in Formie 2 where using Theme Config you can set the ID and other attributes far easier, and it won't conflict with Formie's JS

If using the following not an option?

```
{% set form = craft.formie.forms.handle('payByEmail').one() %}
{% do form.setFormId('formie-form-pay-by-email') %}
{{ craft.formie.renderForm(form, { formClasses: ['form'] }) }}
```

**Comment by TomDeSmet** [comment]
Not if my other issue isn't solved first, see https://github.com/verbb/formie/issues/1143
