### ISSUE TITLE
Only allow a single way to render forms using the form object.

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#1145]
### What are you trying to do?

I've added two bug reports and all are related to using a form `object` or a form's `handle` in the `renderForm()` function.

### What's your proposed solution?

I just think it may be better to drop the form handle support. This has two advantages:
1. Easier testing for you as there is only a single way to render a form using that function.
2. Documentation will be clearer.
3. It makes sense to drop the handle support as you need an actual form instance to be available to render the form. This makes for better error checking in twig files.

**Comment by engram-design** [comment]
I'll follow up in your other issues, but going to keep using handles and form elements for rendering. If nothing else, it will be a nightmare for backward compatibility.

There's something to be said with the simplicity of using `{{ craft.formie.renderForm('contactForm') }}` which people enjoy.

We handle this like so https://github.com/verbb/formie/blob/358ab2eecef70824c5cb88d09fe31919b5cf1fd3/src/services/Rendering.php#L70

I think your other issues would be slightly unrelated (due to other issues).
