### ISSUE TITLE
reCAPTCHA preferences are not respected when creating a new form from a Stencil

### ISSUE THREAD

**Issue by Saboteur777** [verbb/formie#1191]
### Describe the bug

I have a Stencil, where reCAPTCHA is disabled. When I create a new form using this Stencil, the reCAPTCHA is enabled for the newly created form. 

### Steps to reproduce

1. Create a Stencil with reCAPTCHA disabled.
2. Create a new Form from that Stencil. 
3. Check Integrations tab: reCAPTCHA is enabled.

### Form settings

- Multi-page form: -
- Submission Method: -
- Client-side Validation: -
- Custom Form Templates: -

### Craft CMS version

3.7.61

### Plugin version

1.6.19

### Multi-site?

No

**Comment by engram-design** [comment]
Right, so this would probably be correct behaviour because of how we handle integration settings. When enabling a captcha at the global plugin level, and you create a new form, the captcha will be enabled by default. This is the same for when you create a new form from a stencil.

I'll see if we can add handling just for stencils.

**Comment by Saboteur777** [comment]
Okay, thanks for the explanation! 

This seems counterintuitive to me, though, as the Stencil-level setting is more specific than the global one, so I think it should override the global settings. Thanks for looking into it!

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by Saboteur777** [comment]
Thank you!
