### ISSUE TITLE
Custom variables in twig templating within the value of a class when using themeConfig give error

### ISSUE THREAD

**Issue by angelokeirsebilck** [verbb/formie#1209]
### Describe the bug

I am using themeConfig and want to use a custom variables inside my class attribute to change the style based on this custom variable.

`{% set randomVar = 'test' %}`

`                    submitButton: {
                        attributes: {
                            class: [
                                "{{randomVar == 'test' : 'rounded-full'}}"
                            ]
                        }
                    },`

Following code gives an error:

Unexpected token "punctuation" of value ":" ("end of print statement" expected) in "__string_template__

### Steps to reproduce

1. Create a variable
2. Use themeConfig to render form
3. Use twig templating inside a class attribute of an element where you use this variable

### Form settings

- Multi-page form: No
- Custom Form Templates:  No

### Craft CMS version

4.3.4

### Plugin version

2.0.19

### Multi-site?

No

**Comment by engram-design** [comment]
Isn't that because that's an invalid ternary expression?

```twig
submitButton: { attributes: { class: [ "{{randomVar == 'test' : 'rounded-full'}}" ] } },
```

Should be:

```twig
submitButton: { attributes: { class: [ "{{randomVar == 'test' ? 'rounded-full'}}" ] } },
```

But this still won't work, as your variable doesn't exist within the context of rendering the classes. It only exists where you're calling the `renderForm()` method. As such, you don't need to use the embedded Twig functionality here, as that's for evaluating Twig within the [button](https://github.com/verbb/formie/blob/craft-4/src/templates/_special/form-template/_includes/submit.html) include, using any variable defined in that include.

The following should work for you:
```twig
{% set randomVar = 'test' %}

{{ craft.formie.renderForm(form, {
    themeConfig: {
        submitButton: { attributes: { class: [ randomVar == 'test' ? 'rounded-full' ] } },
    },
}) }}
```
