### ISSUE TITLE
Pre-populating Formie fields e.g. dropdown with Dynamics 365 CRM specific label and values from API data

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1252]
### Question

This is more of a general question, but our Microsoft Dynamics 365 CRM has various fields that are Lookup types such as Nationality and Country. There are quite a lot of options on these fields that makes creating each option statically to map the values in Formie to CRM very long winded and not very dynamic. Each option also has a specific unique value that's a GUID such as `186489dd-fc0b-e311-92ae-005056b50017` and this needs to be provided when submitted to Microsoft Dynamics 365 CRM, otherwise it's going to get rejected.

My thoughts were extending an existing Formie field for example "Dropdown" but with the ability for the options for this field to be populated from CRM, rather than manually. In fact the usual setting area of adding/removing would probably be better read only for this type of field given the values must match our CRM.

I believe I've been able to determine the API call to get the lookup label and values from a Lookup field using something like:

```
$crmUrl/api/data/v9.0/ccl1000_nationalities?$select=ccl1000_name,ccl1000_nationalityid
```

This returns the data from the Lookup field from what I can tell, which could then be translated into the label and value options required in Craft CMS on a field.

However, what is the best approach to potentially populate CRM specific label and values onto a Formie field. Would the best option be to create a custom field that just extends the standard Formie dropdown field with a form field name like "Nationality (CRM)" and make the required modifications for being able to perform an API request to pull in the data onto the field? In reality it is unlikely the values will change, but having the ability to update the values from the API could be useful if anything did change, which should be possible, if I can implement an option on the settings menu to do this, which possibly then triggers a controller or something.

Would I be able to piggy back on the existing Microsoft Dynamics 365 CRM authentication methods, in theory the accessToken can be used as it's the same APIs. I can see there's a new nice service class for getting tokens available.

Just looking for a bit of advice on the best way. I think a custom field is probably the best way to go. I can add my own service logic for the additional API request on a module, but just wondered your thoughts.

Thanks!

**Comment by engram-design** [comment]
That's supposed to be what [this](https://github.com/verbb/formie/blob/70553023cb2a2e6a57793d569f2603908075aec7/src/integrations/crm/MicrosoftDynamics365.php#L448-L483) code does. Any picklist field will have options to pick from, as mapping it from form values is probably impossible (you'd have to enter the value of the GUID). But I suppose a Picklist and Lookup field are different.

But the real question:

> However, what is the best approach to potentially populate CRM specific label and values onto a Formie field

Isn't possible at the moment although it's [come up before](https://github.com/verbb/formie/issues/512) for other integrations. We'll need to do something to address this with the option-based fields (Checkboxes, Radio Buttons, Dropdown) to allow for them to be made dynamic using integration data. There's all sorts of concerns with implementing this though, such as keeping field value data up to date.

A custom field is certainly the way to go here. Although the issue is you'll fire off an API call each time you render the form, so it's probably not amazing for performance. You could employ some form of cache to those values - however you want to implement it.

Take a look at this [user guide](https://verbb.io/craft-plugins/formie/user-guides/using-guzzle-clients-from-formie-integrations-in-your-own-code) for how you can use the Guzzle client Formie will create in your own code. You can use that client to make whatever requests you like making it straightforward to implement a call to get what you need.

**Comment by jamesmacwhite** [comment]
Thanks! Picklist and Lookup are two different types in Microsoft Dynamics 365 CRM land. The issue currently would be you could map a Formie field to a CRM lookup in the mapping, but if this field has a lot of options, lets say over 100 for example for a dropdown field, all of those values need to be the CRM value which in some cases could be something like `9920000` or a GUID. Handling those manually is going to be horrible, so that's why being able to import such values is probably best. I don't think there's any way with import related plugins like FeedMe as it doesn't target fields, more on elements.

Custom field sounds like the best option. It does certainly need a caching mechanism, I guess one way would be to import the values into a DB table and then the field would get the values from that, rather than the API call all the time.

Thank you for the information on the integration Guzzle client, that makes things even simpler for API calls!

**Comment by engram-design** [comment]
Another tip you can use Craft's data caches rather than the database to make it simple. Depends if you clear the cache on deployment (common), but it's not really the end of the world:

```
Craft::$app->getCache()->getOrSet($cacheKey, function() {
    return [];
});
```

Where inside that anonymous function you have your logic to fetch your data. It'll either get it from the cache, or set and return it.

**Comment by jamesmacwhite** [comment]
Thank you! I'll look into it for sure, the cache would be cleared often with deployments, but I guess if going through the proper field classes, it would just be regenerated on init?

**Comment by jamesmacwhite** [comment]
So there's possibly a easier way to do this specifically for lookup fields. In actual fact I don't really need custom fields, because I don't need anything different from a field perspective, it's more about the option data.

Using the [Predefined field options event](https://verbb.io/craft-plugins/formie/docs/v1/developers/events#predefined-field-options) for importing bulk values, I can do an API request there to pull the options from CRM and then allow those to be populated on a standard dropdown field. Then using synced fields you can just create a standard field type with the populated options to re-use it, so if you needed to update the values, you'd only need to do it once.

Technically as well once the values are saved onto the field, this data would not need to be cached as it's stored on the field table in the database and not constantly queried, given the populating of these values would only be triggered on using the bulk options feature.
