### ISSUE TITLE
craft.formie.renderJs() does not seem to exist, although the docs mention it.

### ISSUE THREAD

**Issue by tomdeleu** [verbb/formie#1260]
### Describe the bug

The documentation talks about a 'renderJs' function on the form variable:
https://verbb.io/craft-plugins/formie/docs/template-guides/available-variables#craft-formie-renderJs

However, this function does not seem to exist in the source code, and obviously throws an error when called.

Is it possible the documentation is not correct about this?

And the larger issue which got me to this: Are there any good examples or guides on how to approach Formie in a SPA-ish website? (using Swup.js in our case)
We got it working by including the 'renderFormJs' call for every form, but reCaptcha is being a PITA. We get an error "Error: reCAPTCHA has already been rendered in this element". (reCaptcha seems to be initialized both in the 'renderForm' twig method and the Formie.initForm($form) JS method we're using.

### Steps to reproduce

1.  Place the code `{{ craft.formie.renderJs() }}`anywhere on a twig page
2. Error :)

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.0

### Plugin version

2.0.20

### Multi-site?

No

**Comment by engram-design** [comment]
I'd had hoped to get a release out quicker, but these are brand-new functions not in the 2.0.20 release, but are in the `craft-4` branch to address exactly the SPA use-case people have! I'm still writing some docs about SPA usage.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tomdeleu** [comment]
Awesome. Thank you for the quick reply.

Do you have some quick pointers as for the SPA usage? We always seem to double-initialize recaptcha. Any quick tip to avoid that?

**Comment by engram-design** [comment]
So typically, instead of initialising Formie's JS automatically, you'd do it on-demand. I'm not familiar with Swup.js, but it's likely similar to other SPA's.

In your <head> you can add:

```
{{ craft.formie.renderCss() }}
{{ craft.formie.renderJs() }}
```

Which should output the full CSS for any form, and the formie.js JS file for you to initialise as you navigate to a form in your SPA.

Next, when rendering the form, ensure that you don’t load the CSS/JS again. You could also use a Form Template to disable these if you prefer.

```
{{ craft.formie.renderForm(form, {
    renderJs: false,
    renderCss: false,
}) }}
```

Then, the last bit will be initialising the form’s JS when you navigate to it. Again, I’m not familiar with Swup.js, but if there’s a way to run JS when you navigate to a form, By default, Formie will auto-initialise any form that exists in the DOM at the time of render, but as you’re essentially lazy-loading the form, you’ll need to initialise it when you lazy-load it.

Even just something simple alongside your form render

```
{{ craft.formie.renderForm(form, {
    themeConfig: {
        form: {
            attributes: {
                id: 'my-form',
            },
        },
    },

    renderJs: false,
    renderCss: false,
}) }}

<script>
    var $form = document.getElementById('my-form');

    // Create an instance of our Formie JS library - the "factory"
    this.FormieInstance = new Formie();

    // Initialise a form from its DOM element
    this.FormieInstance.initForm($form);
</script>
```

But there is an example of the create/destroy behaviour using Vue as an example - https://verbb.io/craft-plugins/formie/docs/developers/javascript-api#importing-via-modules, as it’s important to destroy the JS instance when navigating away, otherwise you’ll be binding multiple times each time you navigate to your form. Again, I assume Swup.js will let you define onload/offload JS like this.

**Comment by engram-design** [comment]
Added in [2.0.21](https://github.com/verbb/formie/releases/tag/2.0.21)
