### ISSUE TITLE
"All Form Fields" not working in Email Notifications

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#1292]
### Describe the bug

Hello, I have a Craft Multi site set up (Don't know if that is a cause?!)

And I am using the "All form fields" variable in my notification template.

<img width="1163" alt="Screenshot 2023-02-10 at 11 23 21" src="https://user-images.githubusercontent.com/18699249/218080834-45987b49-7010-47dc-aa66-a8fb5563abea.png">

When I receive the notification in my inbox, although the fields are populated in the form they are not displayed.

manually adding each field works.

### Steps to reproduce

1. create notification template
2. add "all form fields" to template and save
3.  test email

### Form settings

- Multi-page form: No
- Custom Form Templates: No

### Craft CMS version

4.3.6.1

### Plugin version

2.0.20

### Multi-site?

yes

**Comment by engram-design** [comment]
Does the email notification preview work? Certainly can't replicate it on my end. Can you shoot through an export of your form to `support@verbb.io` by going to Formie > Settings > Import/Export?

**Comment by mark-chief** [comment]
Hey Josh, No the preview section doesn't work. Will send through now. Thanks

**Comment by engram-design** [comment]
Thanks for the export, I can see the issue is because you have conditions setup for the page, which makes the field conditionally hidden.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/1221575/218424476-f3edee35-b0ee-46f9-914b-bd3c3e1492fa.png">

This behaviour is different to outputting the fields individually, because "All Form Fields" takes into account more about the submission, like if fields are conditionally hidden at the final submission or not. Outputting the field manually bypasses that.

**Comment by mark-chief** [comment]
Yep, manually outputting was my work around, not knowing that that's how it should be working -makes sense now.

Thanks for your help and sorry to waste your time!
