### ISSUE TITLE
Calculated field not being rendered correct when outputting submission in template

### ISSUE THREAD

**Issue by jan-dh** [verbb/formie#1311]
### Describe the bug

I made a couple of calculated field doing some basic calculations based on 2 number input field. They work perfectly (super nice feature btw) and are being saved correct in the CMS. However, when I try to render them using this:

```
{% for field in submission.getFieldLayout().getCustomFields() %}
    {% if not field.getIsCosmetic() %}
      <li>
        {% set value = submission.getFieldValue(field.handle) %}
        {{ value }}
        <strong>{{ field.name }}</strong> -  {{ field.getValueAsString(value, submission) }} - <em>{{ field.handle }}</em>
      </li>
    {% endif %}
{% endfor %}
```

They all render 0, while the value is being shown correct in the CMS:

<img width="181" alt="image" src="https://user-images.githubusercontent.com/5801781/219693559-1a4544d4-865f-4d51-a434-a49db3939cb9.png">

vs

<img width="307" alt="image" src="https://user-images.githubusercontent.com/5801781/219693639-adf8ee26-545b-44d3-9a89-d2da46fac530.png">

I would need to access the values to render some charts.

### Steps to reproduce

1. Create a calculated field for some number fields
2. Try to render the results using the provided template example from the docs:

```
{% for field in submission.getFieldLayout().getCustomFields() %}
    {% if not field.getIsCosmetic() %}
      <li>
        {% set value = submission.getFieldValue(field.handle) %}
        {{ value }}
        <strong>{{ field.name }}</strong> -  {{ field.getValueAsString(value, submission) }} - <em>{{ field.handle }}</em>
      </li>
    {% endif %}
{% endfor %}
```

### Form settings

- Multi-page form: **Yes**
- Submission Method: **Ajax** 
- Client-side Validation: **Yes** 
- Custom Form Templates: **Yes**

### Craft CMS version

4.3.9

### Plugin version

2.0.22

### Multi-site?

No

**Comment by engram-design** [comment]
I'm using your exact code and not seeing that, sorry. 

Do note that calculations fields remain dynamic even after being used on the front-end, and their values don't become static. What this means is the source values for the formula used in the field need to still be there. From the looks of things, that still looks to be the case as per the screenshot of the submission in the control panel. They're also saved in the corresponding content table for the submission as static values (but then the formula takes over when editing the submission), which is why you can access the values using `getValueAsString`.

I'm not quite sure what's going on I'm afraid, as that's all working correctly for me.
