### ISSUE TITLE
Microsoft Dynamics API error: Undefined array key

### ISSUE THREAD

**Issue by alexjcollins** [verbb/formie#1324]
### Describe the bug

I've finally been able to test the updates for Dynamics (once again, thank you to you and @jamesmacwhite!).

When running `Refresh Integration` on a form with Dynamics enabled, I get:

```
Error: Request failed with status code 500
API error: “Undefined array key "cd054151-e0f0-46a7-ad42-5dc9b76bf7d0"” /var/www/html/vendor/verbb/formie/src/integrations/crm/MicrosoftDynamics365.php:614
```

I've tried looking for that UUID, but can't find it anywhere, so maybe that's coming from Dynamics?

If I comment out lines 612 - 614 in MicrosoftDynamics365.php, the error disappears. I'm not using a date field on the form in question.

```php
if ($type === 'DateTime' && $dateTimeBehaviourValues[$metadataId] === 'DateOnly') {
    $type = 'Date';
}
```

Is there anything I can check for you to help debug?

### Steps to reproduce

—

### Form settings

- Multi-page form: No
- Submission Method: GraphQL (but irrelevant for this)
- Client-side Validation: No
- Custom Form Templates: N/A

### Craft CMS version

Pro 3.7.67

### Plugin version

1.6.24

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
@alexjcollins Interesting. So that change is related to the fact that not all Date fields in Dynamics 365 actually support a Date/Time value, so that extra check was added to ensure any date field in Dynamics 365 that only supports date only values, gets set as `Date` not `DateTime` within the integration. So in this case the error is coming from a field in your Dynamics 365 environment.

I used the metadataid to lookup against as I figured it was pretty reliable. There are issues with logical and schema names, which make those unreliable.

I'd be interested to know if you can determine what field in Dynamics 365 that metadata ID is if possible. In theory it should be a date field, but if it isn't the logic needs reviewing to understand why the metadataid is not present in the date fields query used to build an array lookup

It won't matter if you aren't specifically mapping a date field on your form, it's coming from a specific field on the integration mapping.

**Comment by jamesmacwhite** [comment]
To debug, let's follow back the API query data to find that metadataid and check what it is:

Get all DateTime attributes on an entity e.g. for the contact entity:

```
{{webapiurl}}EntityDefinitions(LogicalName='contact')/Attributes/Microsoft.Dynamics.CRM.DateTimeAttributeMetadata?$select=SchemaName,LogicalName,DateTimeBehavior
```

{{webapiurl}} needs to be replaced by your CRM URL e.g. `{{crmurl}}/api/data/v9.0/`.

It might not be on the contact entity, so you might need to check `lead` maybe even `account` or `opportunity`

The easiest fix would be to do a null coalese when an array key lookup doesn't work, but I'd still be interested in understanding how a date field wasn't present in the DateTimeBehavior query to begin with. My theory without seeing your schema is the date field could be an excluded type which means it wasn't included in the fields loop for the integration.

You can also try this patch to confirm the problem:

```php
if ($type === 'DateTime') {
    $dateTimeBehavior = $dateTimeBehaviourValues[$metadataId] ?? null;

    if ($dateTimeBehavior === 'DateOnly') {
	$type = 'Date';
    }
}
```

**Comment by alexjcollins** [comment]
@jamesmacwhite Thanks very much for digging into my issue so quickly and for the guidance on fetching all the DateTime attributes; I'll give that a shot when I'm in the office later today.

I was able to quickly check, and I can confirm that the patch worked - no more error!

**Comment by jamesmacwhite** [comment]
@alexjcollins No worries, I've submitted that as a PR to the main integration class, although if we can get sight of your field info for a more detailed inspection we can understand why a field identified as DateTime wasn't included in the DateTimeBehaviour query to review the DateTimeBehavior as that's what failed I think, it's possibly a custom field or something that's not covered, but it is probably safer to make sure we null coalesce that lookup so we don't bring the house down on the refresh integration.

We do however need to make sure we still change any DateTime field that is set as `Date Only` within CRM to `Date` otherwise if ever used by the integration Formie will try and push a Date/Time value which will cause a 400 bad request error. 

It is annoying that Microsoft has chosen to use the Attribute DateTime on any date field but makes you further query the actual DateTimeBehavior, rather than just using Date or DateTime as a type itself.

**Comment by jamesmacwhite** [comment]
For further debugging, you might need to manually inspect the entity definitions for `contact`, `lead`, `account`, `opportunity`

You can do this with this example below (this is the same API query Formie uses), just switch the LogicalName value to look at each entity.

```
{{webapiurl}}EntityDefinitions(LogicalName='lead')?$select=Attributes&$expand=Attributes($select=AttributeType,IsCustomAttribute,IsValidForCreate,IsValidForUpdate,CanBeSecuredForCreate,CanBeSecuredForUpdate,LogicalName,SchemaName,DisplayName,RequiredLevel)
```

Then from the returned JSON, search for the metadataid value reported in the original error and that will identify what is, then we can begin to trace it back.

**Comment by jamesmacwhite** [comment]
To help run Dynamics 365 web API requests outside of Formie, I'd recommend Postman if not using already.

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-postman-web-api.

It's a bit of setup inititally, but once done, you can perform any Dynamics 365 web API queries at your environment with ease and I'd highly recommend it to help debugging and testing.

**Comment by jamesmacwhite** [comment]
@alexjcollins The more defensive fix has been merged by @engram-design into the craft-3 branch. If you want to get that fix now to prevent the refresh integration action being broken update the Formie composer dependency to: `composer require verbb/formie:"dev-craft-3 as 1.6.25"`

It would be good to get sight of the Dynamics 365 environment entity definitions to understand why a DateTime field in the fields loop wasn't included in the DateTimeBehaviour query. If the field isn't set to DateOnly then it probably isn't an issue, it's only required for DateTime fields that don't support time values, Formie when creating the integration field/mapping must set this to the Date type, otherwise the Dynamics 365 API is going to throw back 400 errors, because the time value won't be accepted.

**Comment by engram-design** [comment]
Updated in [1.6.26](https://github.com/verbb/formie/releases/tag/1.6.26)
