### ISSUE TITLE
Add possibility to show weekday name in date format

### ISSUE THREAD

**Issue by knufri** [verbb/formie#1325]
### What are you trying to do?

I would like to format the date preceded by the name of the day. Unfortunately, this option does not exist or I have not found it. I use the flatpickr to display the date field. With the flatpickr additional options I can format the date as desired but then no date is captured in the submission:

<img width="1051" alt="Bildschirm­foto 2023-02-28 um 08 34 20" src="https://user-images.githubusercontent.com/2785206/221784867-38222839-8613-4210-bfc3-9c921b384662.png">

My Formie Version: 2.0.23.1
My Craft Version: 4.3.10

### What's your proposed solution?

Add more options to the provided date formats:

<img width="406" alt="Bildschirm­foto 2023-02-28 um 08 36 07" src="https://user-images.githubusercontent.com/2785206/221785217-524819a6-dbf2-4e65-b9ad-665a02efc8d7.png">

**Comment by engram-design** [comment]
The best way to tackle this is to provide your own format options. You'll need to add this event code via a Craft module. See [docs](https://verbb.io/craft-plugins/formie/docs/developers/events#the-registerDateFormatOptions-event)

```php
use verbb\formie\events\RegisterDateTimeFormatOpionsEvent;
use verbb\formie\fields\formfields\Date;
use yii\base\Event;

Event::on(Date::class, Date::EVENT_REGISTER_DATE_FORMAT_OPTIONS, function(RegisterDateTimeFormatOpionsEvent $event) {
    $event->options[] = ['label' => 'DAY DD.MM.YYYY', 'value' => 'l d.m.Y'];
});
```

<img width="233" alt="image" src="https://user-images.githubusercontent.com/1221575/221836365-02623731-eda8-40e2-b2f2-59009e2c9fea.png">


We'll likely not incorporate that into the core format options. Otherwise, we'll end up adding every possible combination under the sun!

**Comment by knufri** [comment]
Thank you @engram-design,

I'll have a look onto your suggestion.

Kind Regards
Jan
