### ISSUE TITLE
Date/Time fields and email templates (1 hour time difference)

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1341]
### Describe the bug

I have a date/time field on a form, however this value is being output in a email template. In order to output a formatted date the following has been done in the Twig template.

`bookingDate|date('long')`

* Date/Time value from form submission: 26/04/2023 18:30 (correct)
* Value as stored in MySQL: `2023-04-26 18:30:00` (possibly wrong, shouldn't it be stored as UTC?)
* Value output in template: 26 April 2023 19:30 (wrong)

The time has been modified by +1 hour. I can understand what's happened as Craft CMS has formatted the date to be to the configured timezone when using the date filter.

I'm not sure if this is a bug, I can prevent the timezone modification occurring but just flagging if it's something within the core. Is the general rule with date/time values to be stored in UTC and then output with the configured locale?

### Steps to reproduce

1. Create a form with a date/time field
2. Create submission with date/time field
3. Link an email template that uses the date/time field value using the `|date` filter.
4. Observe the time value is 1 hour out.

### Form settings

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

### Craft CMS version

3.7.67

### Plugin version

1.6.25

### Multi-site?

No

**Comment by engram-design** [comment]
Date and time values are always stored as the value supplied in, not UTC. This is because we don't _want_ them to store timestamp information. Because this information is gathered from the front-end, it should **always** be used as per the user has provided. Not converted to UTC, the server timezone, the Craft timezone, etc. Otherwise, we would need to store the timezone from the client to convert to UTC, only for it to be converted back.

For example - what if you ask for someone's date of birth? I enter my date in Australia (+10), you might add it from the UK (+1). It would be worse with a time field. Even more of an issue, when two users in Craft look at a date in a submission with two different timezone settings for their account, the actual time provided for the submission is ambiguous, because it's adjusted to the current users' timezone setting. Converting this "client time" to UTC seems unnecessary.

So instead, we store the value as text, or as-is.

But, whenever you output it in templates of any kind, you'll want to use the `date` Twig filter. This will by default assume the time is UTC and convert it into the timezone according to either Craft's timezone settings, or the currently logged-in user timezone.

You can get around this by passing in an additional parameter: `myDate | date('long', false)`.

**Comment by jamesmacwhite** [comment]
Thank you for the clarification! That makes total sense, I will pass false for the timezone on any Twig or using getFormatter if calling in PHP code.

**Comment by jamesmacwhite** [comment]
Just for reference, if using the getFormatter() for PHP related code. You need to pass defaultTimeZone and timeZone as the same value to stop it modifying values. We are using this in the CRM integration mapping process.

```php

// Configure formatter to not modify date/time values
$formatter = Craft::$app->getFormatter();
$formatter->defaultTimeZone = 'UTC';
$formatter->timeZone = 'UTC';

// Use to format values as required
$formatter->asTime($dateTimeField, 'short');
```
