### ISSUE TITLE
Conditional pages: Tabs allow navigation without matching condition / Can submit with invalid value and empty required fields on hidden page

### ISSUE THREAD

**Issue by jannisborgers** [verbb/formie#1343]
### Describe the bug

Our client collects inquiries for a certain ZIP code areas. Other areas cannot be serviced by the company, so they want to show different pages based on ZIP code value. Our form has a ZIP code field (simple text field) on page 1. Page 2 is only shown if the ZIP code field value matches a certain condition.

This is supposed to work like an e-commerce checkout, where you cannot get to the payment step unless your delivery address is filled in completely and is valid.

# Client-side / server-side differences
I tried AJAX first, but as AJAX-rendering does not know about the theme config (I found some issues relating to this), and theme config doesn’t seem to have access to conditional or active/current state in the tabs, I couldn’t make the tabs behave like tabs in a multi-page-form should, nor style them to match the client’s site.

# Conditional pages/tabs
When using Formie Base JS to make tabs work with page conditions, the tab for page 2 always appears as soon as I type a valid value into the ZIP code field. This happens even when using server-side rendering. I expected this mode to work like a regular form that hands the information to the next form step or returns with an error message and doesn’t let the user proceed.

## Issue 1: Using tabs to navigate
I can now click on the tab for page 2, because the current ZIP code values is valid client-side (but not saved in the submission yet). The browser shows a warning that my form data will be lost. If a user doesn’t understand that message and continues anyway:
* The ZIP code value will not be saved (as per browser warning)
* Page 2 will be shown anyway (it shouldn’t)
* Because of the conditionals, only the tab for page 1 will be shown

## Issue 2: Submitting wrong field value successfully „saves submission“ even with empty required fields on other pages
I can also submit the form with an „invalid“ ZIP code field value, which shows a „Submission saved“ message and clears the ZIP code field, even though there are required fields on page 2 (which is not visible in the tabs because the ZIP code is invalid). As a user, I have no idea what just happened and only know that I have just submitted a ZIP code. The submission is saved in the CP, and shows empty required fields. 

# Custom rendering to the rescue?
If this is beyond what Formie can do, I’d be happy to know. From the feature tour, this seemed like a scenario that should be possible, but maybe I’m missing something.

I wanted to go the recommended way and only use theme config and not custom rendering. After some trial and error, I searched the docs for custom rendering, but the crucial part (multi-page forms and tabs) is missing from that section.

### Steps to reproduce

1. Page 1 with required text field
2. Page 2 with required fields and condition to only show if text field on page 1 matches condition

## Issue 1: Using tabs to navigate
3. Type into required text field on page 1 with matching value
4. Click on tab for page 2

## Issue 2: Submitting invalid field value successfully „saves submission“
3. Type into required text field on page 1 with invalid value
4. Click submit button

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.10 

### Plugin version

2.0.24

### Multi-site?

No

**Comment by engram-design** [comment]
> I tried AJAX first, but as AJAX-rendering does not know about the theme config (I found some issues relating to this), and theme config doesn’t seem to have access to conditional or active/current state in the tabs, I couldn’t make the tabs behave like tabs in a multi-page-form should, nor style them to match the client’s site.

Maybe we should start with that? Tabs should certainly support theme config classes, as the state of them is controller through data attributes. I can confirm that as you meet the conditions, tabs are toggled to be shown when they're supposed to be shown. They have a `data-conditionally-hidden` attribute removed.

> When using Formie Base JS to make tabs work with page conditions, the tab for page 2 always appears as soon as I type a valid value into the ZIP code field. This happens even when using server-side rendering. I expected this mode to work like a regular form that hands the information to the next form step or returns with an error message and doesn’t let the user proceed.

I understand the confusion for a Page Reload forms that the JS makes this "live", but for an Ajax form, I assume you expect the page to only be "visible" to the user once they've hit submit? The difference with an Ajax form is that you can move around to all pages as much as you like, even skip ahead if you want. You'll always hit validation at the very last step to ensure that you can't submit the form with invalid or missing content.

> I can now click on the tab for page 2, because the current ZIP code values is valid client-side (but not saved in the submission yet). The browser shows a warning that my form data will be lost. If a user doesn’t understand that message and continues anyway:

For an Ajax form, this will not happen. For a Page Reload, yes the user does indeed get in a bit of a weird state where they're on a hidden page. But clicking on tabs has always been a _navigation_ action. I think that warning is incredibly clear to a user that clicking on a tab will discard any unsaved changes they've made. The action is very much "skipping ahead", which is useful to have that warning.

So the solution here is to maybe not trigger tabs to be shown until a page has been submitted - at the very least for a Page Reload form.

> I can also submit the form with an „invalid“ ZIP code field value, which shows a „Submission saved“ message and clears the ZIP code field, even though there are required fields on page 2 (which is not visible in the tabs because the ZIP code is invalid). As a user, I have no idea what just happened and only know that I have just submitted a ZIP code. The submission is saved in the CP, and shows empty required fields.

What do you mean by invalid? What sort of field is the ZIP code field, a number field? Anything that triggers validation on a page will stop the submission process. Required fields on a hidden page will not be factored into validation.

For example, if I make the ZIP code field on page 1 required, I can't proceed without submitting with that value.

> I wanted to go the recommended way and only use theme config and not custom rendering. After some trial and error, I searched the docs for custom rendering, but the crucial part (multi-page forms and tabs) is missing from that section.

So the docs don't cover every possible aspect of custom rendering, because that's largely up to you. A good start is to check out the [raw template](https://github.com/verbb/formie/blob/craft-4/src/templates/_special/form-template/form.html) for the form, where you can dive into pages, row and fields along with tabs, etc. It's all geared toward using Theme Config with `tag()` calls, and you can keep using those, or go 100% manual with just Twig/HTML.

If that's confusing, I'd suggest taking a look at the [Formie 1.x](https://github.com/verbb/formie/blob/craft-3/src/templates/_special/form-template/form.html) templates that don't use Theme Config, and use just Twig/HTML for everything, and that's easily copyable.

But, this certainly should work out of the box, and sounds like we just probably need some tweaking to the user flow.

So for **Issue 1** I'm not sure what to propose here, other than don't have the tabs show in "live" (as soon as you type the conditions are evaluated). This will ensure that tabs aren't visible for Page Reload forms, and the user can't click away and potentially get stuck. How does that sound?

For **Issue 2** I'd love to know what constitutes an invalid value here, whether you're using custom validation or otherwise so I can reproduce this. That certainly shouldn't be happening (the submission should be marked as invalid and not proceed).

**Comment by jannisborgers** [comment]
Hi Josh,

first of all, thanks for taking the time to understand my gibberish. It took me three tries to articulate a reasonable report, but with a good night’s sleep I see that I failed at that.

I started from scratch and now have a solution I’m happy with and that is online: [The form in action](https://www.ried-blitzschutz.de/blitzableiter/blitzschutz-angebot) (use `65510` for valid, `12345` for invalid ZIP).

### Some key points:
* The tabs are always shown, even if the pages they refer to are hidden by a condition. I want to prevent users from navigating there. This is done with a combination of CSS visually and functionally (`pointer-events: none`) and custom JS (`tabindex="-1"` based on `[data-conditionally-hidden]`), both on ZIP code field change (`keyup` event) and `onAfterFormieEvaluateConditions`. This is probably not preventing programmatic spam bots, but humans should probably not be able to see the second page if their ZIP code doesn’t match.
* The form itself uses the theme. I manipulate/reset most of the tab and button styling with some custom CSS (using the `fui-`-classes and data-attributes) and the excellent theme config option.
  * If there is one thing, being able to target active elements and conditionally hidden elements from within theme config would be it.

### One question left.
* Can I prevent submission based on a condition? Right now, ”invalid“ ZIP codes like `12345` can be submitted successfully with the „Next“ button on page 1. I want to prevent submission if page 2 wasn’t filled out. 
  * The only way I can think of is to completely sidestep the first page, only use the second page in Formie without conditions, and wrap it all in an AlpineJS component that hides the whole form based on a custom template for the ZIP code input. The client would have to use a global field to manage the valid ZIP codes. Maybe there’s a way Formie can do this?

Thank you again for taking the time.

**Comment by engram-design** [comment]
Not gibberish at all - I appreciated the thorough detail! Also appreciate the example form, which helps with some context, I can see what you're trying to do.

Targeting active elements and other state is on my todo list for theme config as well.

You can only do this through some custom module code to create your validation rule. The validation rules for fields like single-line and number as pretty basic, and nothing as user-friendly as "can only accept numbers" or "must be in _this_ range" - which would admittedly be neat.

I'm not sure on your PHP or module skills, but here's an example! (and the [docs](https://verbb.io/craft-plugins/formie/docs/developers/field#custom-validation))

```php
use verbb\formie\elements\Submission;
use verbb\formie\events\SubmissionRulesEvent;
use yii\base\Event;

Event::on(Submission::class, Submission::EVENT_DEFINE_RULES, function(SubmissionRulesEvent $event) {
    $event->rules[] = [['field:zipCode'], 'number', 'integerOnly' => true, 'min' => 1000, 'max' => 9000];
});
```

Or if you want more control over the logic (see similar thread https://github.com/verbb/formie/issues/1305):

```php
$event->rules[] = [['field:zipCode'], 'string', 'message' => 'Postcode must valid', 'when' => function($value) {
    return $value > 1000 && $value < 9000;
}];
```

**Comment by jannisborgers** [comment]
Hi @engram-design — thanks again!

Just to clarify: The list of valid codes would have to be hard-coded/duplicated and we can’t use the conditions from the form, right? I’m already getting a couple of form submission emails every day with only „invalid“ ZIP codes in the email content.

Other than that, the form is up and running and I’m happy to close this issue.

Thank you Verbb, thank you Josh!

**Comment by engram-design** [comment]
@jannisborgers You could hard-code the list of valid codes, but you could also grab them from the field - I'm not sure where you store the list of valid postcodes?

Anyway, I'll be sure to take on some of these points to improve the UX of forms.

**Comment by jannisborgers** [comment]
Hi @engram-design — The valid codes are a set of conditions that I use to hide page 2 of the form:

![formie-page-conditions](https://user-images.githubusercontent.com/9452571/225073299-78a46191-04d4-456b-a7fc-c79efed7271d.png)

That’s why I was hoping these conditions could also be used to prevent submission of the form. 

If the customer enters a valid postcode, they get to page 2 of the form and can make a valid submission with all the data my client needs.

But from a user’s perspective, if they enter an invalid postcode, the forms just submits without any info as to what happens. The email notification only contains this one field because the contact data is on page 2 (by design: we don’t want to accept submissions from people who cannot access page 2).

**Comment by engram-design** [comment]
Ah, gotcha - that makes sense now. So yeah that's a different thing I'm afraid - these conditions just show/hide the page itself, they don't impose validation on the actual field value.

Still, the right approach here is to add custom validation rules to enforce a correct value for the postcode field. This will prevent submission, or moving on to the next page.

You could - in your validation rule - grab these settings from the page conditions and use them, so you don't have to manage them in multiple places.
