### ISSUE TITLE
Upgrade from V1 to V2: can't use anymore Twig in field Default Value

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#1358]
### Describe the bug

I've upgraded from `1.5.16` to `2.0.24` and was previously using an `Hidden Field` which contains this `Default Value`:
`{{ currentUser.photo.url ?? null }}`

This is not working anymore in Formie V2, the variable is outputted as plain text instead of getting the expected URL.

### Steps to reproduce

1. Setup an `Hidden Field` with `{{ currentUser.photo.url ?? null }}` as `Default Value`
2. Fill in the form on front-end and check what's saved

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.3

### Plugin version

2.0.24

### Multi-site?

Yes

**Comment by engram-design** [comment]
Yep, we've had to back-track the dynamic capabilities of the hidden field, due to security concerns. Because you could use _any_ Twig code as the default value, this meant that malicious Twig could be added/modified, because it is evaluated on-render. For example, you could modify the value of the hidden field, submit the form with invalid data, kicking in server-side validation, and when re-rendering the value for the hidden field, it would produce your Twig code.

As such, only Twig with single braces (shorthand) can be used, which can be used to refer to other fields, or simple things like `{now}`. This doesn't allow for access to the global Twig environment, Craft global variables (like `currentUser`) or other advanced behaviour.

While it was convenient to be able to use any Twig, you'll need to re-work things. I would suggest using [populateFormValues](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) in your template to do this.

This was also changed in [1.6.22](https://github.com/verbb/formie/blob/craft-4/CHANGELOG.md#1622---2023-01-30)
