### ISSUE TITLE
Inconsistent error behaviour on multi-page forms

### ISSUE THREAD

**Issue by dwheeldo** [verbb/formie#1359]
### Describe the bug

I have an issue with client-side validation on multi-page forms.

When submitting page 1 of the form, if there are any errors then the browser scrolls up to the error message at the top of the page (as expected).

But on page 2+, if there are any errors then the browser scrolls up to the first question-level error message, rather than the page-level error.

Scrolling to the top feels like the correct behaviour.

### Steps to reproduce

1. Complete page 1 of a multipage form
2. Try to submit page 2+ when there are validation errors

### Form settings

- Multi-page form: Yes
- Submission Method: Both
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.61

### Plugin version

1.6.23

### Multi-site?

No

**Comment by engram-design** [comment]
I'm not quite sure I follow, sorry. So you're saying you fill out the first page all okay (no validation errors), proceed to the next page, then try and submit the page, and instead of scrolling to the first field with an error, rather than the top of the form where the "global" error message is shown?

For client-side validation on **any** page, it'll always scroll to the first field with an error.

**Comment by dwheeldo** [comment]
Sorry if the issue wasn't clear, let me try to clarify! First I should say that this only occurs in certain browsers:

- Firefox (Mac and PC)
- Chrome (PC only)

This is the current behaviour we're getting:

- On page 1 of any form, if there are validation errors the browser scrolls to the **error alert** at the top of the page - eg. "Your form can't be submitted yet, please review the issues below and try again."

- If you try to submit page 2+ with validation errors, the browser scrolls to the first **field** with an error - eg. "This field is required"

**Comment by engram-design** [comment]
Thanks for clarifying! I'm certainly not seeing that behaviour on my end, and have just run a form with 20 fields (just to ensure it scrolls correctly) in Browserstack on Mac/Windows Chrome/Firefox and errors always trigger a scroll to the first field with an error. That's the correct and expected behaviour - it shouldn't really scroll to the global error message, as we'd want to provide users the fastest way to correct any errors. Particularly for large forms, we don't want users to have to go searching for their errored field.

So _something_ is going on with your form that must be different to mine. Would you be able to send a support request through via Formie > Settings > Get Support? That way I can double check your form on my end.

**Comment by dwheeldo** [comment]
Hmm, how strange. I'll have a proper dig into how the forms are set up and send a support request if I can't get to the bottom of it.
