### ISSUE TITLE
Word limit not working on Multi Line text field with Rich text enabled

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#1376]
### Describe the bug

The word / character limit is not counting down on a multi line text field with Rich text enabled. 
Works as expected on regular multi-line text field though.

See below. 500 limit displays but does not count down:

<img width="800" alt="Screenshot 2023-04-05 at 08 48 35" src="https://user-images.githubusercontent.com/18699249/230015790-0406abf9-8f0d-4b57-b10f-f94ab5705906.png">

Thanks!

### Steps to reproduce

<img width="1112" alt="Screenshot 2023-04-05 at 08 45 10" src="https://user-images.githubusercontent.com/18699249/230015265-6a3e4d44-1815-4e73-a7b5-c9dd4c78063f.png">
<img width="1124" alt="Screenshot 2023-04-05 at 08 44 51" src="https://user-images.githubusercontent.com/18699249/230015267-33b6674e-835d-41f3-861d-c2933a33f7f3.png">

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Custom Form Templates: No

### Craft CMS version

4.3.1

### Plugin version

2.0.18

### Multi-site?

No

**Comment by engram-design** [comment]
Strange, seems to be working on my end https://share.cleanshot.com/XFbwgh5G

Any JS errors? Is your field outputting the `data-max-words` attribute? 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/1221575/230022456-799d8c62-0039-4045-a24b-6bd75873007b.png">

**Comment by mark-chief** [comment]
No JS errors to report.

<img width="839" alt="Screenshot 2023-04-05 at 09 33 43" src="https://user-images.githubusercontent.com/18699249/230027716-394da874-6960-46c3-88bf-8aec931b47c8.png">

I've also stripped it right back to remove any JS libraries or other code.

**Comment by engram-design** [comment]
Hmmm, if you're up for debugging on your end, you can certainly spin up Formie's JS in "development mode" by navigating to `vendors/verbb/formie` and running `npm install` then `npm run frontend` which should start a webpack watch event. Any changes you make to the JS file for [text limits](https://github.com/verbb/formie/blob/craft-4/src/web/assets/frontend/src/js/fields/text-limit.js) will then show up in your console.

I might suggest stepping through some debug code to see what might be going on - and what's different to my testing!

Otherwise, I can keep at trying to replicate it.

**Comment by thatONEjustin** [comment]
This needs to reopened. Have the exact same bug. 

Looks like the Multi Line Rich Text field is appending unnecessary span tags and style attributes to the content input:

![2024-04-22_13:15:00](https://github.com/verbb/formie/assets/2763180/b7676542-696b-4e52-9ec2-81ec2cf47ed6)
![2024-04-22_13:16:11](https://github.com/verbb/formie/assets/2763180/6a680f89-5372-4150-b675-067451f43a17)
