### ISSUE TITLE
Data retention setting is not working

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1384]
### Describe the bug

I'm trying to use Formie as a replacement for Guest Entries. I've set up an Element integration and everything is working, except that I'm going to end up with lots of Submissions when I only need them stored as Entries. I tried to set the data retention to 1 minute, but the submissions are never removed.

Settings:
![image](https://user-images.githubusercontent.com/1250017/231139566-59c2c869-74cf-4704-97ff-f301d0abec6c.png)

I've visited the control panel minutes / hours later and the submission are still in there

### Steps to reproduce

1. Set Data Retention to 1 minute
2. The Submissions are never removed

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates:  No

### Craft CMS version

4.4.6.1

### Plugin version

2.0.26

### Multi-site?

No

**Comment by engram-design** [comment]
We use Craft's Garbage Collection mechanism to actually perform the deletions. This is because Craft doesn't have a scheduler (until Craft 5), so they can't be deleted at the exact point in time. Garbage collection only runs infrequently. 

We would otherwise need a process that continually runs to check whether these cleanup tasks (of which there are a few) need to be triggered without relying on someone visiting the control panel.

For now, you can force Garbage collection to run with `./craft gc/run`.

**Comment by darylknight** [comment]
That makes perfect sense - but it might be worth noting next to that setting that's how it works. Otherwise there are settings to "delete after 1 minute" which doesn't happen.

**Comment by engram-design** [comment]
Yeah, I wanted to keep the technical stuff away from the form builder, as clients shouldn't need to understand garbage collection. But I may hide that information away in a tooltip or similar.

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
