### ISSUE TITLE
All form fields not rendering the correct information in email notifications

### ISSUE THREAD

**Issue by hassanmah** [verbb/formie#142]
**Description**
Having All form fields in the email body of a notification sends the wrong information in the email. It sends the fields from another submission rather than the one just submitted.

![image](https://user-images.githubusercontent.com/3025707/94247988-c6a01f00-ff15-11ea-9fc4-1b93a00df486.png)

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation:  No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.18
- Craft version: 3.5.11.1
- Multi-site: No

**Comment by engram-design** [comment]
That's quite surprising. I see in your example you're using 'Your name' and 'name of pupil'. Are these correct values - therefor different from what's shown belong in the all fields output?

**Comment by hassanmah** [comment]
@engram-design yes 'Your name' and 'name of pupil' have correct values. What we have noticed is that, the emails all arrived at the same time and all the emails have the "All Form Fields" from the first submission of the day

Also a side note, I can't seem to add a multi-line text field to the email body. All the options available in the screenshot are of single line text 

![image](https://user-images.githubusercontent.com/3025707/94268807-9c5e5980-ff35-11ea-9cfa-931fb06e4602.png)

**Comment by engram-design** [comment]
So the emails all being delivered at once will likely have to do with email notifications using the queue. It'll only get triggered to be processed when someone visits the control panel - unless you have alternate queue processing setup.

I can see an issue where multiple emails are in the queue and processed at bulk, causing your issue.

Fixed in [1.2.19](https://github.com/verbb/formie/releases/tag/1.2.19)
