### ISSUE TITLE
Migrating submissions of a form from one multi-site to another

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1424]
### Question

I have a scenario where a form was originally created and used on the primary site on a Craft CMS site, but in the future it will be used on a different site and removed from the primary site. Currently all submissions are under the primary siteId of 1, new submissions I assume when used on the different multi-site will go under the that site, but the existing submissions will no doubt will remain under primary site.

What is the easiest way to migrate the existing form submissions elements from one siteId to another? Would they need to be resaved as new elements under the new siteId?

**Comment by engram-design** [comment]
The site that a submission is set to is controlled by the front-end templates (there's a `siteId` input), as forms aren't multi-site aware. This will use the current site as the value by default.

Rather than importing/exporting/etc with Feed Me (which you can do), it'd be far simpler to run a console command to move the submission to the other site (update the `siteId`). That's _if_ you want them moved to the other site, they'll still exist just fine as submissions continue to come through on the new site.

```
./craft resave/formie-submissions --set siteId --to 2
```

**Comment by jamesmacwhite** [comment]
Thank you! Yes they ultimately will be moved to another site, when a new site goes live, so it sounds like the console command to resave and update the siteId is the solution!

**Comment by jamesmacwhite** [comment]
Just for info, to set the raw value you'd need to quote it as `--to "=4"` for console command to work properly, but otherwise works.
