### ISSUE TITLE
Labels and helper text for Button field settings are confusing

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1462]
### Describe the bug

When editing the Button field, I find some of the setting field labels and helper text a bit confusing and inconsistent.

```
## Submit Buttons Position
How the submit buttons should be positioned.
```
The use of "Submit" is misleading because this applies to all three buttons: Back, Save, and Submit. Though the use of the plural "buttons" is a clue, it's not the most clear.

```
# CSS Classes
Add attributes to be outputted on this submit button’s container.

# Container Attributes
Add attributes to be outputted on this submit button’s container.
```
Given the wording, I would expect these to be added to the container (e.g., the `buttonContainer` in theme config lingo) of only the submit button. But they are added to the `buttonWrapper` which contains _all_ of these buttons.

---

A few small adjustments to the wording could help improve clarity:
- Give the field a more abstract name, e.g., "Button Group" or "Actions"
- Update labels/text to make it clear if the setting applies to the group or to a specific button

### Craft CMS version

4.4.13

### Plugin version

2.0.30

**Comment by engram-design** [comment]
More of an evolution than anything, as Back used to submit the page rather than discard any changes made (can be configurable), so it's technically a submission. But saving is indeed not really submit behaviour.

I've gone with "Form buttons" to try and keep things client-friendly with lingo.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`.

**Comment by engram-design** [comment]
Updated in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
