### ISSUE TITLE
How are usage stats calculated?

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1463]
### Question

The value of the "Usage Count" column in the Form element index seems quite off. How is this calculated?

I have a new form I've just created. Before I added it to an entry, the count was 0 as expected. After adding to one entry, the count increased to 6.

And although this is a multisite instance, the entry with the relationship to the form is not propagated to any other sites.

### Additional context

<img width="429" alt="usage-index" src="https://github.com/verbb/formie/assets/5922913/1201caa0-6dc5-461f-9bbe-cc7148de7cf5">

<img width="959" alt="usage-tab" src="https://github.com/verbb/formie/assets/5922913/c9441075-ea7b-4168-b580-d6faa7323e4e">

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.30"`. 

Do note that the element index counts will only show the outer element for performance. So in your case, it'll show it's used `1` times, denoting the "Test" entry. Rather than showing `2` as you may expect.

**Comment by chrismlusk** [comment]
Perfect. `1` is what I’d expect in the above case, so that’s great. Thanks!

**Comment by engram-design** [comment]
Fixed in [2.0.31](https://github.com/verbb/formie/releases/tag/2.0.31)
