### ISSUE TITLE
Possible to control how multiple checkbox values are formatted when populated from a URL?

### ISSUE THREAD

**Issue by engram-design** [verbb/formie#1464]
### Discussed in https://github.com/verbb/formie/discussions/1216

<div type='discussions-op-text'>

<sup>Originally posted by **jmauzyk** December 17, 2022</sup>
Wondering if there's currently any way to control how multiple checkbox values are formatted when populated from a URL into a form? Currently, if populated into a text field we get a format like `["abc","123"]`. Would like to use a more human-friendly format such as comma separated values if possible.</div>

**Comment by engram-design** [comment]
@jmauzyk Can you provide what you're doing on your end to reproduce? Seems to be working for me!

**Comment by jmauzyk** [comment]
From another page, the user selects items they want to add to the request form. This puts the items as query parameters in the GET request (`site.com/my-form?part_number%5B%5D=2154&part_number%5B%5D=2155`). The form setting successfully populates into the correct field, but always written out as an array, rather than something more human readable like a comma separated list. Any things I should try troubleshooting on my end?
<img width="612" alt="Screenshot 2023-06-06 at 2 17 18 PM" src="https://github.com/verbb/formie/assets/21298596/82565860-cb99-48e9-a057-e3450fa13a57">

**Comment by engram-design** [comment]
So is your "Part Number" field meant to be a Checkboxes field (or an element field with Checkboxes layout)? I assume you're just using a Single-Line Text field to illustrate?

If so, then that's exactly how it should work, provided you have Checkbox items in your Checkboxes fields with the values `2154` and `2155`.

Otherwise, if you want to populate a "plain text" field with array values (as you've shown here), that's out of scope of Formie's default behaviour to transform it to comma-separated values, because it doesn't assume to know what you want. Maybe you _want_ the array of values in the query string stored as an array.

If you want to populate fields yourself, I would recommend doing so [manually](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) where you've got full control over things.

**Comment by jmauzyk** [comment]
Sorry, I think I misunderstood what they code changes you made actually accomplished. I was trying to accomplish the latter. I'll populate the field manually as you suggested.
