### ISSUE TITLE
Unique email error classes/attributes disappear on blur

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1476]
### Describe the bug

When an email field is using the Unique Values setting and you trigger an error on the front end, the resulting CSS classes and HTML attributes on the form field disappear on blur.

### Steps to reproduce

1. Create a form with an email field that requires unique values.
2. Attempt to submit the form twice with the same email.
3. See the errors.
4. Click away from the email field.
5. See the errors go away.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.14

### Plugin version

2.0.31

**Comment by engram-design** [comment]
This is only an issue when "Validate When Typing" is enabled (please confirm if that's not the case). I'm not quite sure if that's something that'll ever be addressed, as it would require a call back to the server on-blur to check if the value is indeed invalid or valid. That's not something I'm overly keen on at the moment.

There are plans to revamp the client-side validation framework, but it probably won't handle this. There are a few different people who have opinions on how errors-as-you-type should work as well (once the form is first submitted). Some say errors should update in realtime, others say that errors should remain until the next submit.

I believe it's the former we're addressing, where say if you had a required field after hitting submit, the error would appear. But as you type, the error should disappear. But because this validation rule doesn't really exist on the front-end, there's a disconnect here.

**Comment by chrismlusk** [comment]
That's fair, and I agree with your position.

For context, what prompted this issue is that my password manager tries to be helpful but ends up hiding the error message. And of course clicking away to close it removes the error. 

Just an unfortunate clash.

<img width="550" alt="email error" src="https://github.com/verbb/formie/assets/5922913/6d792f26-b880-4a7e-bd59-96369285bec5">
