### ISSUE TITLE
"Configure Import" button label in import/export section is confusing

### ISSUE THREAD

**Issue by uandco** [verbb/formie#1477]
### What are you trying to do?

The submit button of the import section is confusing, why doesn't it just say "Import"?

<img width="771" alt="image" src="https://github.com/verbb/formie/assets/26996169/aec649cd-ace7-4df3-b808-6ac66ad91f5e">

### What's your proposed solution?

Rename "Configure import" to "Import"

**Comment by uandco** [comment]
I understand this is a 2 steps process, the first step being to "configure" the import (even tho it's not really a configuration, more a review of what is about to get imported) but from a user perspective, "configure import" sounds like something you would do prior to upload the file.

**Comment by engram-design** [comment]
The reason for not using just "Import" is indeed because it's a 2-step process. During user testing, we found some users reached the second screen, thinking it was a summary of what was imported and navigated away - not knowing they needed to confirm things.

As for lack of "configuration", that's fair and under interpretation. There is only a single thing to configure, which is the import action 
<img width="293" alt="image" src="https://github.com/verbb/formie/assets/1221575/cbf01db2-eb34-4255-9fc0-9d6fc28bc9d1">

And yeah, I understand the action of "configure import" can mean configuring the things needed to upload (before), or configuring the things about the thing you've uploaded (after).

I'll give it some further thought, but this one's a subjective topic!

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
