### ISSUE TITLE
Dynamic download on submit

### ISSUE THREAD

**Issue by mjniland1** [verbb/formie#1482]
### Question

I have a simple form that collects zip codes and depending on the zip code provided, the system will redirect to (or better yet, download) a file associated with that zip. I used https://verbb.io/craft-plugins/formie/user-guides/how-to-conditionally-redirect-users-based-on-their-input#event as a guide and I have a solution that successfully redirects to the proper file but I'm encountering a few hang-ups: 

1. After a successful submit and redirect, the form fails to reset and no subsequent submission can be processed. I'm using Ajax for my submission method and my Action on Submit is set to `Reset Form Values`. Ideally, the user would be able to submit the form as many times as they would like. 
2. I'd like to trigger the forms Error Message if the zip code isn't found.

Added context: 

1. The form is one of three formie forms on the page
2. The forms use the google recatpcha v3 integration
3. All three forms use the default renderer e.g. `{{ craft.formie.renderForm('zipCodeLookup') }}`

```
Event::on(SubmissionsController::class, SubmissionsController::EVENT_AFTER_SUBMISSION_REQUEST, function(SubmissionEvent $event) {
    $success = $event->success;
    $zipCode = $event->submission->zipCode;

    if ($success){
        if ($zipCode !== null && $zipCode !== '') {

            $category = Category::find()
                ->group('zipCodes')
                ->title($zipCode)
                ->one();
           
            if ($category){

                $fileName = $category->getFieldValue('fileName');
                
                if ($fileName) {

                    $filePath = Craft::getAlias('@assetBaseUrl') . '/downloads/' . $fileName;
                    $event->form->settings->redirectUrl = $filePath; // Download Preferred
                    
                }

            } else {
                // Trigger the forms Error Message
            }
        }
    }
});
```

**Comment by engram-design** [comment]
I'm confused if you're redirecting users or not, if you're having issues resetting the form fields? I would think that these are two incompatible methods. But resetting form field values is trivial JS (handled by Formie's JS) of `$form.reset()` with `$form` being the `<form>` element.

As for the error message, I would recommend creating a [custom validation](https://verbb.io/craft-plugins/formie/docs/developers/field#custom-validation) for that.

```php
$event->rules[] = [['field:myField'], 'string', 'message' => 'Postcode is invalid.', 'when' => function($value) {
    return $value->myField === 3000;
}];
```

**Comment by mjniland1** [comment]
My mistake I should have clarified. The redirect to the file opens in a new tab so the original form page is still open. I'll give the custom validation a shot, thanks for the prompt reply!

**Comment by IrateGod** [comment]
Piggybacking on this question since it seemed very topical for my issue, I currently have a very similar custom module for a form that I'm intending to populate dynamically with an ID passed through a query parameter.
I'm able to set the form's redirectUrl just fine, but it retains the query parameter on the URL I'm redirecting to, which I'd like to disable.
An example URL would be something like `https://my.ddev.site/download-form?entryId=123`, and I've added a Hidden Field which reads the `entryId` query parameter. Upon redirecting to a new URL that I've defined in the entry with the specified ID, I'd expect to be redirected to that URL, but the ?entryId parameter gets appended to the redirectUrl anyway. I'd expect to get redirect to `https://other.ddev.site/some-slug`, but I get redirected to `https://other.ddev.site/some-slug?entryId=123`.

Here's my custom module, I'm using Craft 4.4.14 and Formie 2.0.31:

```
Event::on(SubmissionsController::class, SubmissionsController::EVENT_AFTER_SUBMISSION_REQUEST, function(SubmissionEvent $event) {
    if (!$event->form->isLastPage()) {
        return;
    }

    if (!$event->success) {
        return;
    }

    $entryId = $event->submission->getFieldValue('entryId');

    if (!$entryId) {
        return;
    }

    $useCaseEntry = Entry::find()->section('useCases')->id($entryId)->one();

    if (!$useCaseEntry) {
        return;
    }

    if ($useCaseEntry->enableDownload && !empty($useCaseEntry->downloadUrl)) {
        $event->form->settings->redirectUrl = $useCaseEntry->downloadUrl;
    } else {
        return;
    }
});
```

I've identified https://github.com/verbb/formie/blob/69ecd11f226598a434b66e6dc260fa811674f6a6/src/controllers/SubmissionsController.php#L1012 as possible responsible code here.

I'm thankful for any advice in advance.

**Comment by engram-design** [comment]
@IrateGod This is probably a separate issue, but people want to be able to [retain query params](https://github.com/verbb/formie/issues/404) on the redirect - most commonly for tracking purposes like `utm`.

But for now, you can [disable this behaviour](https://github.com/verbb/formie/issues/1442#issuecomment-1553789963) 

```twig
{% do form.setSettings({
    redirectUrl: form.getRedirectUrl(true, false),
}) %}
```

Which in PHP would be:

```php
$event->form->getRedirectUrl(true, false);
```

**Comment by IrateGod** [comment]
@engram-design Thanks for the quick reply! I was able to resolve the issue I was facing by using `$event->form->setRedirectUrl($url);` in my PHP module, which as described in the linked issue sets the redirectUrl as provided.
