### ISSUE TITLE
Thousands separator in number fields

### ISSUE THREAD

**Issue by carolineboeykens** [verbb/formie#1503]
### What are you trying to do?

It would be nice to add a thousands separator on number fields so that large number can be visualised.

For example: in stead of 100000 it would be 100.000 or 100 000

### What's your proposed solution?

We thought of this because twig had an option for this, so maybe it would be nice in the input as well?

https://twig.symfony.com/doc/3.x/filters/number_format.html

**Comment by engram-design** [comment]
So my first instinct on this is to leave the presentation of values in the field as-is, according to native `<input type="number">` field implementations. We don't want to save value including those extra characters, because they change the content type from a number to a string. It also becomes a can of worms for internationalisation.

To achieve this, we'd have to roll our own JS to add this presentation to the field when typed/pasted/etc and remove it before storing the value. That's just extra complexity we don't want to introduce.

For that reason, I'm probably going to mark this as not planned. I'd encourage you to add your own JS libraries to your number fields if you'd like this functionality!
