### ISSUE TITLE
Final form submit on prev-button (multi-page with tabs)

### ISSUE THREAD

**Issue by TurboThomsen** [verbb/formie#1513]
### Describe the bug

I have a multipage form with selectable Tabs and next/prev-buttons. The Form is savable and can be reopened. The Bug can submit the form without validation and shows the success Message.

### Steps to reproduce

1. Open a ready form.
2. Save the form. (We are sending a email with a link to reopen the form)
3. Open the form in a new browser tab
url: {basePath}/formie-form?entryUid={entryUid}&submissionUid={submissionUid}
4. Select on both forms the second tab using the tab-selection. (Not the next-button)
(-> actions/formie/submissions/set-page)
5. Click on both forms the previous-button. (Not on Tabs)
-> on the second time, the form is submitted
The first request has the same next-pageId as the current. And on the second request: "null".

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.13

### Plugin version

2.0.33

### Multi-site?

Yes

**Comment by engram-design** [comment]
Clicking on tabs will not submit the page, it's purely navigational. So there's no validation, or values submitted.

Going back a page shouldn't trigger validation, but by default, it will save values (you can change that in a Formie setting).

Can you confirm what you mean in your steps when you refer to "both" forms? What two forms are there?

So long as the back button has a `data-submit-action="back"` attribute on it, that will tell Formie's JS that it's going back a page and not to do client-side or server-side validation. If you're on the last page of a form, and you submit that page, it will _always_ validate the entire form server-side, so you shouldn't be able to bypass validation anyway.

**Comment by TurboThomsen** [comment]
With both forms i mean the same submission opened twice (in 2 browser tabs).
First i go to page 2 in both opened forms. And then i click on back-button in both opened forms. 
The response of saving the submission includes the attribute "nextPageId". I dont now if thats the issue, but it seems that nextPageId is different the second time (null). Maybe there is a other issue that caused the submitting.

**Comment by TurboThomsen** [comment]
https://github.com/verbb/formie/assets/103662584/be1604bc-5515-44fd-8a99-27c2215c2cb5

**Comment by TurboThomsen** [comment]
https://github.com/verbb/formie/assets/103662584/ee05a69c-551f-4470-a3f8-47a332f81f83

**Comment by engram-design** [comment]
Thanks for clarifying! I see what you mean now, and is a complication on having the forms "synced" across the same session. So this problem crops up because you've already gone to the first page on one form, and you're trying to go back to the page before the first page - which doesn't exist.

This is somewhat awkward for other instances, where you might have more than 2 tabs. If you continue to navigate from say a 6th tab, to the 3rd one, and then go to the same form in another tab (also on page 6), and hit back, you'll end up on page 2, because the session for the current submission for the form will think you're on page 3. That'll still happen and something I'm looking to improve with session management improvements, so you can retain separate sessions per tab, per submission (if you wish to).

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.33"`.

**Comment by engram-design** [comment]
Fixed in [2.0.34](https://github.com/verbb/formie/releases/tag/2.0.34)
