### ISSUE TITLE
"Agree" field: make the "label" (text above checkbox) optional

### ISSUE THREAD

**Issue by tremby** [verbb/formie#1547]
### What are you trying to do?

I want to display a form with an "agree" checkbox whose purpose is already totally clear from the text alongside the checkbox, with no text above.

However, at present, what is called the "label" in the admin UI (which is the text which displays above the checkbox) is required.

It seems needless to have *two* separate required pieces of text for a single "agree" field.

### What's your proposed solution?

- Make the "label" optional in the admin UI
- If it is left blank, suppress the end-user-facing UI for the text which goes above the checkbox
- If necessary, adjust markup so that the text next to the checkbox is the `<label>` element. (Note I didn't inspect the current UI in detail; perhaps it already is this way.)

### Additional context

See #1501.

**Comment by engram-design** [comment]
I'll make the comment that firstly, it's to allow flexibility with the field and to keep the label consistent with other fields. Some users like to have both a label for the field and a label for the checkbox. The label can be hidden.

<img width="609" alt="image" src="https://github.com/verbb/formie/assets/1221575/9e6bb4fe-0648-4842-8209-902a83843d32">

Secondly, all fields require a label in order to be saved. To get around this, we would need to automatically generate the label, similar to a Section or Heading field.

Thirdly, people want to add rich text to the checkbox label, which is why there's a need for the description field. People want to include links and formatting - something which is impossible with the Label, due to how it's saved in Craft's `fields` database table. It needs to be its own setting.

Lastly, this will need to be opt-in to prevent breaking behaviour with people who _want_ to use both label and description.

**Comment by tremby** [comment]
> I'll make the comment that firstly, it's to allow flexibility with the field and to keep the label consistent with other fields. Some users like to have both a label for the field and a label for the checkbox

Absolutely. I'm suggesting it's made optional, not that it's removed entirely from the admin UI.

> The label can be hidden.

:laughing: I had forgotten this option exists! Still, if it can be hidden, why should the form author be required to enter something for it?

> Secondly, all fields require a label in order to be saved. To get around this, we would need to automatically generate the label, similar to a Section or Heading field.

Sure. That seems a technical limitation with a simple enough workaround that the form author needn't be concerned with.

> Thirdly, people want to add rich text to the checkbox label, which is why there's a need for the description field

Sure, I'm not suggesting changing anything about that field, except wrapping its output in `<label>` if it isn't already and the `<label>` would otherwise be the text above the checkbox but there is none.

> Lastly, this will need to be opt-in to prevent breaking behaviour with people who want to use both label and description.

Well of course. That's what "optional" means.

**Comment by engram-design** [comment]
All good points, will consider it!

**Comment by engram-design** [comment]
After working through some options, I think this is going to be too technical to implement - at least it a manner that I'm happy with. Mostly it's about generating a field handle based off the description, as opposed to the label. We can auto-generate the label from the description text, but being HTML, it's a little tricky without a lot of special handling just for this field.

If there's any more interest in this, I'll certainly reconsider. Particularly if it's annoying people.
