### ISSUE TITLE
different validation on character check

### ISSUE THREAD

**Issue by TurboThomsen** [verbb/formie#1549]
### Describe the bug

Character check on client is with unicode. But its different for validation on server.

https://github.com/verbb/formie/assets/103662584/fa40c541-8cea-42d9-8a9e-fb5234a1b45b

### Steps to reproduce

(see video) 
Examples: üöä€§

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.14

### Plugin version

2.0.34.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Yeah, this is a somewhat known complication of having to handle emoji's. Basically, any special characters are transformed to their HTML entity value and that's used as the length on the front-end.

We're basically following https://dev.to/nikkimk/converting-utf-including-emoji-to-html-x1f92f-4951 but looks like this affects special characters. For example, the character `ü` is represented as `&#252;` which is the reason for the discrepancy.

I'll see what we can do about changing the range to handle "normal" characters. The server-side library that handles converting emoji's isn't available client-side, otherwise we would match it exactly.

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
