### ISSUE TITLE
Input number field via GQL return *field* must be a string.

### ISSUE THREAD

**Issue by aodihis** [verbb/formie#1553]
### Describe the bug

I have a form with the number field inside it, and in front end we use mutation gql to submit the form.

On the Number field we post it as integer,  but it return an error that the field must be string.

This only happen in version 2.0.35. Work fine on older version.

### Steps to reproduce

1. Create an form with number field inside it.
2. Post the Form using GQL.

### Form settings

- Multi-page form:  No
- Submission Method: GQL

### Craft CMS version

4.5.3

### Plugin version

2.0.35

**Comment by engram-design** [comment]
Yeah, this is a good point, and maybe a little tricky. 

The [switch](https://github.com/verbb/formie/commit/c721d4da226938cfd50092c2c94345b188733041) was made to change the data type of the Number field to accept a string, rather than a number. Mostly because a number limits the value to an integer's max value (`2147483647`). People want to be able to use the Number field to enter ID's or account numbers, like `902476241` which are longer than the max allowed value, but still want to enforce it as a number.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.35"`.

**Comment by engram-design** [comment]
Fixed in [2.0.36](https://github.com/verbb/formie/releases/tag/2.0.36)
