### ISSUE TITLE
Possible to load JS/CSS from outside of cpresources?

### ISSUE THREAD

**Issue by baileydoestech** [verbb/formie#1561]
### Question

We are hosting our control panel on a separate domain to our main site(s) and this is NOT publicly accessible. As per https://github.com/craftcms/cms/issues/13628 we have changed the resourceBaseUrl to use this private domain (fixes some core Craft errors) but now presents an issue where the form JS/CSS files in cpresources cannot be accessed externally.

My initial thought was to manual load the JS myself, copying these files and dropping them on our own CDN which can be accessed. 

![image](https://github.com/verbb/formie/assets/3185073/33fe2837-c58d-4100-8e60-b6a98c82c7c6)

We then use a custom form template with manual CSS/JS loading

![image](https://github.com/verbb/formie/assets/3185073/8f66f63a-e3f6-48f1-ac02-60aa0cc0feec)

However this feels risky, we would need to keep up to date with all Formie updates and ensure that new JS/CSS copies across.

It also appears that the phone-country.css file still laods automatically with a form that uses custom CSS loading. you can see here that it is loaded when we haven't manually added anything ourselves

![image](https://github.com/verbb/formie/assets/3185073/55a21fdf-8213-44f6-bc45-8c844a9a9e41)

So ultimately the question is whether or not this is likely to succeed and if not is there is any another possible way to do it?

**Comment by engram-design** [comment]
So at the moment, this likely won't be possible to offload CSS/JS assets like you describe. There is an [issue](https://github.com/verbb/formie/issues/1010) already for supplying things via an NPM package that you could integrate wherever you want.

Otherwise, if you can't access the `cpresources` (which are totally valid to be accessed on the front-end, despite being labelled `cp`), then you might be stuck.

**Comment by baileydoestech** [comment]
ok thanks for the info - I think that probably makes alternate non public domain for the CP a no go then.
