### ISSUE TITLE
The "Agree" field is making a duplicate hidden input for field fields[agreepolicy]

### ISSUE THREAD

**Issue by KarelJanVanHaute** [verbb/formie#1580]
### Describe the bug

When I add an "Agree" field, then in the frontend it renders an extra hidden input with the same name. Don't know why. And also not always. 
What I get when I render the form. 
```HTML
<div class="fui-input-container">
  <input type="hidden" name="fields[agreepolicy]" value="" data-fui-input-type="agree">
    <div class="fui-checkbox">
      <input type="checkbox" id="fui-contact_learning-trpgjg-fields-agreepolicy" class="fui-input fui-checkbox-input" name="fields[agreepolicy]" value="1" required="" data-fui-id="contact_learning-agreepolicy" data-fui-input-type="agree">
      <label class="fui-checkbox-label" for="fui-contact_learning-trpgjg-fields-agreepolicy">
        I have read and agree with the EIT Food <a target="" href="https://eitedu.local.statik.be/privacy">Privacy policy</a>
      </label>
    </div>
</div>
```

### Steps to reproduce

Add an "Agree" field and check the HTML. 
Notice: sometimes it does it correctly. For now no idea when it happens or under which circumstance. 

### Form settings

- Multi-page form:  No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.5

### Plugin version

2.0.37

### Multi-site?

No

**Comment by engram-design** [comment]
This is the correct output, and is how we tell if the field is supplying us with an “on” or “off” value, particularly when editing a submission (un-checking the field).

Is the field not working correctly for you?

**Comment by KarelJanVanHaute** [comment]
Yes it is working. But my HTML validator starts screaming at this. Because now you have 2 inputs with the same name. And that is just invalid HTML. 
I get now why you are doing this. But isn't there a better way to do this? 
Also, I made the field required. So the field will always be submitted in the form, because it's required. So in that case you don't need an empty one I guess?

Ok after some extra thought. This is indeed not really a problem because the first one is hidden. So also no problem for screen readers I guess.

**Comment by KarelJanVanHaute** [comment]
Never mind this brain fart. I'll just ignore my HTML error.

**Comment by engram-design** [comment]
Yeah, not sure why the HTML validator is kicking up a fuss here. 

Let's say we remove the hidden input, and I can illustrate the issue. I believe this may be a Yii/Craft-ism, which is why Craft does the same sort of thing.

We submit the form with the checkbox checked, which equates to the following payload:

```
fields: {
    agreepolicy: true,
}
```

If we were to submit un-checked then the payload would be empty:

```
fields: {
}
```

Now, say we're on the 2nd page where we've checked the Agree field, but want to go back a page and un-check it. We do so, and the empty payload is sent, but the Agree field stays checked. This is because there is no supplied value for the `agreepolicy` field, so it leaves the field value untouched.

**Comment by KarelJanVanHaute** [comment]
Indeed. I get it now. 
Sorry for bothering you.
