### ISSUE TITLE
Unable to find the template “formie/_components/actions/set-status/trigger”.

### ISSUE THREAD

**Issue by pascal-blaser** [verbb/formie#1585]
### Describe the bug

I'm working on a module to trigger the send-notification action on the Submission::EVENT_AFTER_SAVE event.

My code: 
```
Event::on(Submission::class, Submission::EVENT_AFTER_SAVE, function(ModelEvent $event) {
    if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'wb'));
    //Craft::info('notify', 'formietest');

    Notify::$plugin->getinstance()->controllerNamespace = 'verbb\formie\console\controllers';

    $params = [
        submission-id' => 445,
        notification-id' => 1
    ];
    $command = Notify::$plugin->getinstance()->runAction('submissions/send-notification', $params);
});
```

Now whenever i use the "Set status" button on the submission overview, i get following error message: 
![image_480](https://github.com/verbb/formie/assets/116191091/f3909f39-8b8b-45b3-894a-234ef158206c)

- The notifications do get triggered/mails are sent out.
- The subscription-status does change (but it's only noticable after reloading the page).

So everything seems to work just fine, except for the error message.

Editing single submissions does not trigger this error message.

Is this my fault or is this a bug in the formie-plugin?

### Steps to reproduce

1. Create and register an empty module/plugin.
2. Implement my code snippet in the init() function of the plugin (error only occures upon calling the runAction() function).

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.5 & 4.5.6.1

### Plugin version

2.0.37

### Multi-site?

Yes

**Comment by engram-design** [comment]
Are you able to provide your entire module (send to `support@verbb.io` is that's easier)? It may very well be due to the template roots being changed in your module, and when calling `formie/_components/actions/set-status/trigger`, it's trying to resolve it through your module, not Formie's files.

By the way, it might just be easier to send the notification through your event hook, rather than calling the console command. It's really just 3 lines of code and might address the controller namespace changing you're doing (in case that's the issue).

```php
Event::on(Submission::class, Submission::EVENT_AFTER_SAVE, function(ModelEvent $event) {
    $notification = Formie::$plugin->getNotifications()->getNotificationById(1);
    $submission = Submission::find()->id(445)->one();

    Formie::$plugin->getSubmissions()->sendNotificationEmail($notification, $submission);
});
```
