### ISSUE TITLE
FR: Ability to create a new form when editing an Entry

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1592]
### What are you trying to do?

When you're editing a Craft entry and have a Formie field to add a new form, you first have to leave the page, go to the Formie section of the control panel and create the form there, then come back to add it.

### What's your proposed solution?

Would love to be able to create forms while editing an entry, similar to how slideouts work (Freeform also does this). Appreciate that this may not be possible or just unfeasible, but thought I'd suggest it anyway.

**Comment by engram-design** [comment]
Sure! The only reason this isn't implemented is because of screen real-estate for the form builder, and all the extra bit like email notifications/integrations/etc. Even editing the fields roll their own UI with Vue, so there's some complexity there (it might look a bit janky with the slideout and a modal.

Correct me if I'm wrong, but doesn't Freeform just give you a dropdown to pick a form from?

**Comment by darylknight** [comment]
Ah you're right, I'm sorry - Freeform provides a dropdown, not a modal to add new ones.

![image](https://github.com/verbb/formie/assets/1250017/8b26293c-b6b5-4d27-adbb-6796a7ab6f93)

Yeah - I figured it was because it takes up a lot of screen space. Guess it's not a big deal to just middle click open a new tab and create the form there, given how often we actually create new forms!

**Comment by engram-design** [comment]
Never say never to this one, I agree it's a better author-flow, but we'll see what we can do!
