### ISSUE TITLE
Neither html nor markdown supported in success message

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#16]
### Description
Form displays unconverted success text

### Steps to reproduce
1. Select form option "Action on Submit" = "Display a message"
2. Add `<strong>Thank</strong> you for your **message**!` as form Submission Message 
3. Submit form in FE

### Expected
Text is formatted **bold**

### Actual
Text is displayed as "source code"

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Additional info

- Plugin version: 1.0.4
- Craft version:

**Comment by engram-design** [comment]
I remember now why this was left this way. We decided against having HTML and Markdown support for this field, because its just not user-friendly - again, our goal of the plugin.

As such, I've changed this to a rich text field to allow this functionality in [1.0.5](https://github.com/verbb/formie/releases/tag/1.0.5)

In addition, this also leads a larger change where you now have configurable rich text settings. By default, this field only includes Bold and Italic - but you might want to add more. Check out the [docs]() if you need more flexibility.

**Comment by mizmiz** [comment]
Thanks, I will look into it. My use case is a link to a PDF.
