### ISSUE TITLE
Agree field unchecked/checked conditional values

### ISSUE THREAD

**Issue by dian-kaagman** [verbb/formie#1614]
### Describe the bug

I have a problem with the agree field when used as a conditional. When creating a conditional that uses an agree field, the checked/unchecked actually return 1 and 0.
<img width="476" alt="Scherm­afbeelding 2023-10-30 om 14 31 22" src="https://github.com/verbb/formie/assets/56150605/36faac7d-ce72-446f-8e6e-a82701f35bb5">

While the checked/unchecked values by default are yes and no. This way my conditional will never work because it's comparing the `1` to `yes` and vice versa.
<img width="530" alt="Scherm­afbeelding 2023-10-30 om 14 31 45" src="https://github.com/verbb/formie/assets/56150605/25a43ee8-d6b5-4f90-aa6c-0434f8d10587">

So if I want to use a conditional on my agree field I always need to set these values to 1 and 0, which makes those input fields my opinion useless. Why don't they work just like checkboxes, where the conditional options represent the actual values of the input field? So instead of `checked/unchecked` for example `yes/no`, `true/false` based on what the user set in the agree field's checked and unchecked input fields.
<img width="451" alt="Scherm­afbeelding 2023-10-30 om 14 33 15" src="https://github.com/verbb/formie/assets/56150605/b9dde2dd-404a-4ff8-b90b-646af21b46db">

### Steps to reproduce

1. Add an `agree` field, (with default `checked` and `unchecked` values `yes` and `no`)
2. Add a field with a conditional based on the agree field
<img width="1086" alt="Scherm­afbeelding 2023-10-30 om 14 25 08" src="https://github.com/verbb/formie/assets/56150605/07f1f9e1-ebf8-4b6d-a2c4-3d0fd07a039a">

3. The dropdown `checked` or `unchecked` returns `1` or `0`, which will never be equal to the `checked` or `unchecked` value passed in the `agree` field (`yes` and `no`).

Workaround:

1. Replace the `checked` and `unchecked` values of the `agree` field with `1` and `0`

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.6.1

### Plugin version

2.0.38

### Multi-site?

no

**Comment by engram-design** [comment]
For Agree fields, the Checked/Unchecked values are _purely_ visual, and are used in email notifications and when viewing a submission. This just gives you a bit more flexibility for just a yes/no. As for the underlying value for the field, it indeed is a boolean 0/1 or true/false value. As such, there's not a massive need to show the Checked/Unchecked values in the conditions builder settings, but it probably would be too harmful. But inherently, an Agree field is either on or off.

As for conditions not working, that doesn't seem to be the case for me - Agree fields are working as expected for me when being used to toggle other fields.

To illustrate, this is the output of the `<input>` element:

```
<input type="checkbox" class="fui-input fui-checkbox-input" name="fields[agree]" value="1" data-fui-input-type="agree">
```

Where the value is indeed `1`, but that cannot be changed, and isn't supposed to reflect the changes you set in those checked/unchecked values. This is just to simply the field which saves its data as true/false, rather than the values you set. There's a few reasons for this, but the main one is so that we know when the field is "true" for things like integrations where it's relied on for opt-in. It's true that we could look up the checked value and if the value equals that, it's true - but because that setting can be changed, it's not reliable.

As for why it's not working, it's possibly related to other [conditions](https://github.com/verbb/formie/issues/1615) issues.
