### ISSUE TITLE
Captcha settings per-form don't show up on the live site

### ISSUE THREAD

**Issue by darylknight** [verbb/formie#1627]
### Describe the bug

I've set several captcha types with .env variables to choose whether they're globally enabled for each environment:

![image](https://github.com/verbb/formie/assets/1250017/60b19116-d010-475e-b1de-5522d6d4162b)

In a local dev environment, I then have those options show up when editing a form:
![image](https://github.com/verbb/formie/assets/1250017/a14408e7-727b-4afe-897a-a8e41d5e5795)

However, on the live site, none of them show up:

![image](https://github.com/verbb/formie/assets/1250017/b4f98539-e91f-4688-a6bb-7f4fb85717a6)

### Steps to reproduce

1. Set up captchas
2. They don't appear on a site where allowAdminChanges is false

### Form settings

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: No

### Craft CMS version

4.5.10

### Plugin version

2.0.42

### Multi-site?

No

**Comment by engram-design** [comment]
So that's certainly working for me. You can technically navigate to `admin/formie/settings/captchas` so you can double check the captcha settings (it's hidden because you can't make any changes here with `allowAdminChanges = false`.

Can you confirm if your reCAPTCHA settings are picking up that .env variable? If those integrations aren't showing up for a form, then they're not considered enabled at the global plugin level.

**Comment by darylknight** [comment]
It's working fine today 🤦 Sorry! I guess I must have either changed the variable names, or not deployed when I thought I had. Sorry for interrupting you.
