### ISSUE TITLE
The mailer service failed to send the notification: “”."

### ISSUE THREAD

**Issue by brandondeweese** [verbb/formie#1629]
### Describe the bug

Getting error: "Failed to send notification email: {"error":"Notification email “Website Inquiry” could not be sent for submission “3319”. The mailer service failed to send the notification: “”."}."

It works fine on my local machine but won't send in production. I'm using Postmark App as the system mailer.

### Steps to reproduce

Just fill out the form on production and it doesn't send.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

### Craft CMS version

Craft Solo 3.9.5

### Plugin version

1.6.35

### Multi-site?

no

**Comment by engram-design** [comment]
I've been trying to get this PR (https://github.com/craftcms/postmark/pull/24) accepted so that more logging can be provided by the mailer, as right now it's tricky to know what might be the issue specifically. There's something tripping up Postmark, but without seeing what the error is, it's tricky to figure out what.

Are there any logs in Postmark?

**Comment by brandondeweese** [comment]
No logs in Postmark,

**Comment by engram-design** [comment]
I'm going to ping Brandon again about getting that PR accepted, because things aren't being logged to Postmark properly otherwise...

**Comment by angieherrera** [comment]
<strike>I've just encountered this same issue (also using Postmark). But this site is on Craft 4.5.5 and Formie 2.0.36. Is there a fix I've missed somewhere?</strike>

Never mind—found #1346—checking the web.log helped.
