### ISSUE TITLE
Multipage form tab's link doesn't validate the form's page

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#163]
On multipage forms, clicking the _next page_ button validates the current page. So the user can continue to next page only when current page is filled out correctly. That is correct.

But when user clicks on the _next page tab lin_k, there is no validation and current page is submitted even with errors (required fields are not filled).

**Both links – next page button and next page tab link – should work the same.**

**Comment by engram-design** [comment]
I disagree - clicking on the link to go to a specific page doesn't submit the form at all. If you're on say page 4 of a form, and click on the page 2 because you've forgotten something in a previous step, its a navigation, not a form submit behaviour. 

Similarly, you _could_ skip ahead to the last page of a form right from the very beginning. If you try and submit the form at the last step, you'll get a validation error, because the last step of the form always validates the entire form to prevent these scenarios.

So, the links in page tabs are purely for navigation purposes.

**Comment by lexislav** [comment]
Well, I got Your point. It makes sence, at least for scenarios when user is going back trought the pages.
 
But going forward, from page 1 to page 4 without filling the pages 2 and 3 and then trying to submit the form on page 4 leads to form’s submit error.
The tabs are not marked which pages contain these errors - afaik- To navigate to the page with error(s) is not easy then. And the fields are not highlighted with error when going trought tabs/pages.

But I might be too opinionated with specific case. And as #150 would be done, I can easily apply desired logic to tabs – disable next tabs, make only passed tabs navigable.

**Comment by engram-design** [comment]
Yeah, showing errors on fields in other pages might be tricky - for page-reloading at least. Because once you change the page, you've lost the state of the Submission and its errors. But it's a clear requirement for UX for users. This is probably a separate issue in that errors aren't shown on page tabs, or highlighting fields in other pages.

And yes, I did consider making an option for tabs to allow "Navigate to incomplete pages", but figured the settings were getting a bit out of control.

**Comment by engram-design** [comment]
I've improved a bunch of things for the next release which should help this.

1. When on the final page and there are errors on previous pages, tabs now show an error indicator for the pages with an error. This handles the case where you might have 2 pages with required fields, you navigate to the last page via clicking a tab, and hit submit. It will fail, but the user doesn't really know why.
2. No matter if you use Page Reload or Ajax, if you do the above scenario, you'll be automatically redirected to the first page with an error, so make it plain to see what action needs to be done.

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.21.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by lexislav** [comment]
Nice job!

**Comment by engram-design** [comment]
Added in [1.4.22](https://github.com/verbb/formie/releases/tag/1.4.22)
