### ISSUE TITLE
Repeater field with entries field inside doesn't pre-populate an entry based on query parameter

### ISSUE THREAD

**Issue by DenyEs** [verbb/formie#1642]
### Describe the bug

I have a repeater field on my form with entries field inside, I choose the minimum instances to be 1 on repeater field itself and I set to pre-populate entries field based on a query parameter. When I visit the URL with correct parameters, it doesn't pre-populate the field.

I wen't through this closed issue and if I do it this way, it works, but when I want it purely based on query parameter, it won't pre-populate.

https://github.com/verbb/formie/issues/1190

### Steps to reproduce

1. Create a form
2. Add repeater field and choose minimum instances to be 1
3. Add entries field inside repeater field and set pre-populate value to match query param you'll be passing through
4. Visit a page with form with correct query parameters in the URL

### Form settings

- Multi-page form: Yes - my repeater field that needs pre-populating is on the first page
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.5.11.1

### Plugin version

2.0.43

### Multi-site?

No

**Comment by engram-design** [comment]
Repeater fields (or their inner ones) don't really support populating via query parameters. This is mostly because it becomes overly complex with handling multiple rows. It also get's really tricky to figure out how to define data for element fields.

For example, say you have a URL like `/my-form?entries[]=123&entries[]=456`, where you want to populate the `entries` field in a Repeater field. The Repeater field doesn't know if you want 1 row with two entries, or 2 rows with one entry in each.

There's also ambiguity for other fields. Say you have a Single-Line Text field you want populated `/my-form?text=Some Text`. Firstly, that's not provided as an array, so we convert it to one. But should that value be used for _every_ row in the Repeater, or just the first one? We could change it to `/my-form?text[]=Some Text`, but doesn't really address the problem.

For now, you'll need to handle this yourself with Twig.

```twig
/my-form?entries[]=123

{% do craft.formie.populateFormValues(form, {
    repeaterField: [
        {
            entriesField: craft.app.request.getParam('entries'),
        },
    ],
}) %}
```

**Comment by DenyEs** [comment]
Thanks for clarification Josh, I had the same thoughs thinking as to how would it actually work but like you said, it would be way too tricky to accomodate all possible scenarios and combinations.

In my head, I saw the option to pre-populate the field even if it was inside the repeater field and it didn't work so I logged an issue just in case I missed something.

I've done it in a similar way as you described at the end so it all works as it should. Cheers for that! 😊

**Comment by engram-design** [comment]
Very open to suggestions for ideas on how you _think_ it should work, but yes - the field settings within a Repeater field aren't contextual - they don't change if they are in a Repeater or not (maybe they should!).

I'll keep this open for that scenario to implement, to save confusion like this.

**Comment by DenyEs** [comment]
I'd be happy with that solution. If field settings would change if they're withing repeater field, that would be great

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
