### ISSUE TITLE
Send notification to user who submitted a form

### ISSUE THREAD

**Issue by drifteaur** [verbb/formie#1649]
### What are you trying to do?

When submitting a form that has _Require Logged-in User_ set, I want to be able to select the submitting user's email as a recipient for the notification email. The + button only allows me to select _System Email_ or _System Reply To_

![CleanShot 2023-12-05 at 14 50 06](https://github.com/verbb/formie/assets/3732/4741f73f-bb67-48ad-8599-77503d9d9676)

### What's your proposed solution?

By trial and error I figured out using `{userEmail}` will work nicely; but it would be great if the dropdown would include this option as it is hard to find.

**Comment by engram-design** [comment]
So that's a good point, in that if you don't have an Email field in your form, but are opting to use "Collect User", it should populate user values to pick from, as a user would be associated with the submission.

For now, this would require adding a hidden field, [populating](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) it, and picking that in the email variable picker.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
