### ISSUE TITLE
How to prevent integrations from creating duplicate submissions and records within that service

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/formie#1652]
### Question

We have a client using the Salesforce integration within Formie to map submissions to leads in their Salesforce database. However, if a user submits the form, and they already exist in Salesforce as a lead, it creates a duplicate record.

Is there a way in Formie to check if a record already exists within Salesforce before creating a new one? Or is there a better solution to this problem I'm overlooking?

**Comment by engram-design** [comment]
We already check if there are [duplicate leads](https://github.com/verbb/formie/blob/760b13b2d96e3217b3cdc0a65861a1284a89f247/src/integrations/crm/Salesforce.php#L430), but that's only if an error is thrown by Salesforce that prevent duplicate leads. From memory, there are some Salesforce rules you can set to prevent duplicate leads based off attributes like the email?

I suppose we don't pre-emptively check if there is a duplicate, because that would require us to nominate a field (or multiple fields) to be used as that duplicate check. Commonly, it's an email, but it might not be.

We've found that people like to create a task when a duplicate is encountered, which is why we have a setting for that.

**Comment by aaronbushnell** [comment]
Thanks, @engram-design, that's very helpful!
