### ISSUE TITLE
Email notifications are not sent due to submission (wrongly) being marked as spam

### ISSUE THREAD

**Issue by Sjouwke** [verbb/formie#1679]
### Describe the bug

I have an issue where users can successfully fill out and submit forms in the front-end. All data is correctly captured and visible in the back-end, but the email notifications for a specific user are not sent.

If I check the Formie log files, it's apparently because the submission is marked as spam.

```
2024-01-08 16:56:11 [INFO] Submission triggered for subsidieaanvraagSociaalTolkenEnVertalen.
2024-01-08 16:56:11 [INFO] Submission marked as spam - "Failed Captcha "Javascript": "Value mismatch :659c1a7ad97cb7.34056883."" -
```

I think it's because the user filled out an email address that contains uppercase characters. I also tested it with my email address, both with and without uppercase, and it appears that the submission with uppercase characters is indeed also marked as spam and won't trigger any email notifications.

Is this expected behaviour and/or should we configure some things differently? 

### Steps to reproduce

1. Create form with email field
2. Configure email notifications
3. Fill out form in front-end with valid email address containing uppercase characters, ex: Sjouwke@LittleMissRobot.com
4. Check back-end: submission comes trough
5. Check mail box / email server: no emails are sent 

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: No
- Custom Form Templates: Yes 

### Craft CMS version

4.5.7

### Plugin version

2.0.38

### Multi-site?

No

**Comment by engram-design** [comment]
Using uppercase characters in an email should be completely fine, unless your mailer has specific rules setup that don't allow that. What mailer does Craft use for this project?

I can see the JS captcha has failed, which would be preventing the email notification from being sent but the submission still coming through. Is the submission in the control panel being marked as spam?

Usually, a `value mismatch` means that the token on the server and the client are out of sync. This can happen if the form isn't reloaded after submitting the form (and a new token is generated). This was actually added in [2.0.39](https://github.com/verbb/formie/releases/tag/2.0.39) where once the form is submitted, new tokens for CSRF and captchas are fetched. 

I just wanted to confirm if you've been testing by refreshing the page, or just by filling out the form again? It may be that it's just because the second time you fill out the form, the tokens are invalid, and that's triggering a spam response.

**Comment by Sjouwke** [comment]
> ...unless your mailer has specific rules setup that don't allow that. What mailer does Craft use for this project?

Thanks for pointing that out. We use Postmark as mailserver, but we also wrote a custom [Flexmail](https://flexmail.be/en/) integration and apparently Flexmail doesn't like capitals in emails, which caused the submission being marked as spam. So changing `$submission->email` into `strtolower($submission->email)` in our custom module did the trick. 

Thanks for the help!

**Comment by engram-design** [comment]
Good call, we should be doing that ourselves. Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.
