### ISSUE TITLE
Formie with sprig

### ISSUE THREAD

**Issue by samuelbirch** [verbb/formie#1697]
### Describe the bug

When loading in a form with sprig and using `{{ craft.formie.renderJs(true) }}` it seems to load ok. But when i submit the form i can see the validation kicks in and highlight the relevant required fields in red, but the form submits anyway.

### Steps to reproduce

1. load a form with sprig
2. use `{{ craft.formie.renderJs(true) }}`
3. have required fields
4. submit form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.6.0

### Plugin version

2.1.2

**Comment by engram-design** [comment]
From my understanding of Sprig, it's not going to work with Formie's JS. This is because Formie will try and initialize the Ajax request to the `formie/submissions/submit` endpoint, but Sprig will be taking over that and doing its own thing. As such you miss out of plenty of what Formie will do for its on-submit tasks, such as waiting for client-side validation to be actioned, captchas, payment gateways and more.

With Sprig, you're essentially hijacking the submit for a form and telling it to route through Sprig to handle the "normal" for submit to make the page not reload. But you don't really want that to happen in the case of an Ajax-enabled Formie form. 

I'm _pretty_ sure the two aren't compatible.

**Comment by samuelbirch** [comment]
got it working :)

just needed to add:
`{{ craft.formie.renderFormJs(form) }}
    {{ craft.formie.renderFormCss(form) }}`

**Comment by engram-design** [comment]
Oh! Well, I stand corrected! Glad you got it working
