### ISSUE TITLE
novalidate should not be added to form if output javascript is off

### ISSUE THREAD

**Issue by leevigraham** [verbb/formie#170]
**Description**

novalidate is applied to the form when javascript is not output which overrides the default browser HTML5 validation.

**Steps to reproduce**

1. Create a form using a new template with the settings below
2. Render the form

### Form settings

Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No
- Output Javascript: No

### Template Settings

![image](https://user-images.githubusercontent.com/25124/95731794-aa4d0200-0ccb-11eb-8a60-21b85ecd8918.png)

**Comment by leevigraham** [comment]
See: https://github.com/verbb/formie/pull/171

**Comment by engram-design** [comment]
I've gone ahead and removed `novalidate` altogether. Whenever Formie's JS kicks in (if you're using it), it'll add `novalidate` on the form so that JS-based validation can occur. If you're not using the Theme JS, you'll get native HTML5 validation, rather than none at all.

See [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20).
