### ISSUE TITLE
The percentage of the progress bar does not take into account any page hidden by condition.

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1705]
### Describe the bug

The percentage of the progress bar does not take into account any page hidden by condition.

I am working on a complex form with several pages.
A checkbox on the first page decides which pages should be displayed.
After the evaluation of the condition is done, the tabs are updated but not the progress bar.

![image](https://github.com/verbb/formie/assets/10438940/8ccd7cf5-f8ae-4e55-8dab-e3a7a6e3a8b2)
Should be 50%

--- 
It would be great to have an event to know if the page index has changed.
I currently use the `onFormiePageToggle` event to update my custom page index in addition to the progress bar.
Design:
![image](https://github.com/verbb/formie/assets/10438940/8b2b6f98-8b63-4b6b-adaf-87fa22e3aa0f)

Best regards

### Steps to reproduce

1. Create a form with 3 pages 
2. Add a checkbox to the first page
3. Make the page 2 only visible if the checkbox is checked via conditions
4. The progress bar indicates 33% even though only 2 Steps are visible.

### Form settings

- Multi-page form: Yes
- Submission Method: Both

### Craft CMS version

4.7.1

### Plugin version

2.1.3

**Comment by engram-design** [comment]
The page tabs being hidden are different to changing values for things like the progress bar. That's because we can output the conditional rules to show/hide a page tab, whereas if we want to update the progress bar value, we need to know how many pages are visible. Yes, we could watch the page tabs' visibility, but we can't guarantee tabs will be there - we can't rely on that being enabled. 

There's no concept of that in the front-end JS, and no plans to add that extra potential bloat for this, and some large refactoing. At least, not anytime soon. Using the `onFormiePageToggle` event is a great idea here.

**Comment by Megafry** [comment]
Thanks for your feedback, I now understand the complexity this can add.
I was able to solve it differently, I have changed the conditions to hide groups instead of pages.

best regards
