### ISSUE TITLE
Personalize Notifications With Multiple Recipients

### ISSUE THREAD

**Issue by medoingthings** [verbb/formie#1711]
### Question

I just added multiple recipients to a notification. I would like to personalize the notification with the names. But I can’t figure out how to send each recipient a personalized email. Is this currently possible?

### Additional context

The goal is to send multiple emails using the notification in one go. So after submitting the form, multiple recipients would get an email like: 
`Hi [name], …`
That would involve that each email notification has only one email address in the `To` field. Right now it includes a comma separeted list of the given email addresses.

I need to populate the recipients before template rendering, because they need to be dynamic. Currently I’m using a recipients field with type `hidden` and populate it via `populateFormValues()`.

**Comment by engram-design** [comment]
That's not possible at the moment, sorry. This would probably be very specific to the Recipients field, as you'd need some method to be able to get both the label (`[name]`) and the value (the email) related to one another, and for them to be iterated over, instead of shown in a list as comma-delimited values.

This might actually be tricky with how the "To" value works for sending emails with SymfonyMailer, because I don't think they're actually multiple emails that are sent out, they just have multiple "To" recipients in a single email. We might need an option to send multiple emails vs a single one.

But that would still require us to loop through the Recipients field to generate the email notification and use the value in the recipient and the content as name. It's almost like we want to have dynamic email notifications themselves.

**Comment by medoingthings** [comment]
Alright, thanks for the heads-up! I’ll code myself around this for the moment :)
