### ISSUE TITLE
Import Form with same UID overrides current form

### ISSUE THREAD

**Issue by Tim-Wils** [verbb/formie#1725]
### Describe the bug

Hi!

We just had a problem with a form import that we changed on a staging website (also changed the title and the handle) and later imported this form to the live site.
Because of the same UID that also got exported, the old form with that UID lost his fields, which was not expected.

### Steps to reproduce

With a staging-site that's a copy of the live site:
- Edit the same form to your wishes. Also rename the handle and title, beacause it has to act like a totally different form.
- Export the form
- Import it to the live site
- The new form is created as expected
- Go to the form that the form was originally made from and see that this form lost his fields

### Form settings

- Multi-page form: Yes

### Craft CMS version

4

### Plugin version

latest

**Comment by engram-design** [comment]
Bah, this was changed to include UID's specifically so that people's imports weren't getting [messed up](https://github.com/verbb/formie/discussions/1696). This is where were might need to opt-in to including the UID for exports for this reason. I actually don't think we should include the UID, as it's tied to the form, and you get to choose at the second step of import how to handle it (replace the existing or create a new one).

I'll look at reverting this behaviour to fix this.

**Comment by Tim-Wils** [comment]
Didn't realize it was this new, somewhat makes sense :)

I think rolling back and to the old behaviour as the default for now is alright, but: 

Maybe an option with additional checkbox, at the second step of the import (where summary of the form imports are shown) would be friendly. That should behaves as a "Found an exisiting form [form-title]:[form-handle] with the same UID, would you like to override the existing form?" (checked = overwrite, unchecked = default behaviour/creates new form)

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`. I've actually just added a case where if you have it set to create a new form, and an existing form exists for that UID, to generate a new UID.

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
