### ISSUE TITLE
Uploads get duplicated in multi-step forms

### ISSUE THREAD

**Issue by pl-mnm** [verbb/formie#1729]
### Describe the bug

When authors create a multi-step form with grouped upload fields, the uploaded files get duplicated at each page of the form. It sounds a lot like [this issue](https://github.com/verbb/formie/issues/1590), however updating the plugin doesn't seem to fix it.

### Steps to reproduce

1. Create a multi-page form
2. Add multiple upload fields inside a grouped field on the first page
3. Create a second page with some other fields
4. On the front-end, fill up the form and proceed to the next page
5. In the assets library, assets are duplicated

### Form settings

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Craft CMS version

4.6.1

### Plugin version

2.1.3

### Multi-site?

No

**Comment by engram-design** [comment]
Looks to be happening for non-nested File Upload fields too, but I believe this is unique to Ajax fields. This is because the file is still populated on the field when submitted on the next page, creating a new asset.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)
