### ISSUE TITLE
File upload inside repeater field not renamed as per the Filename Format setting (only the first one is)

### ISSUE THREAD

**Issue by melissadoyon** [verbb/formie#1745]
### Describe the bug

I have an issue with a file upload field inside a repeater field. I have set a desired filename format but only the first row of the repeater is using it. Other rows keep the original filename and adds timestamp followed by an underscore and 4 random letters.

### Steps to reproduce

1. Create a repeater field (max 15 instances) with a file upload inside it with limit number of files of 1
2. Specify a Filename Format (ex. Submission ID-attachment-Timestamp)
3. Submit form with more than one uploaded file
4. Check submission data

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.8.0

### Plugin version

2.1.5

### Multi-site?

No

**Comment by engram-design** [comment]
Ah, I see the issue here, is that there's no unique suffix for the files across the repeater. It's essentially trying to save all the assets in the repeater field with the same name, which is failing, and hence falls back to the original filename. So in this instance, we're going to need to include a suffix when being used in a Repeater.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.5"`.

**Comment by melissadoyon** [comment]
Updated to version 2.1.6. It works perfectly now. Thank you!
