### ISSUE TITLE
Start / End Date mapping broken in Solspace Calendar Event Integration

### ISSUE THREAD

**Issue by markdrzy** [verbb/formie#1804]
### Describe the bug

After the Solspace Calendar 5 update, start and end dates are not being set correctly via the CalendarEvent Element Integration.

It appears that Solspace changed the location of their DateHelper, and this change needs to be reflected in Formie's CalendarEvent Element Integration.

PR forthcoming.

### Steps to reproduce

1. Set up a Formie form -> Solspace Calendar Element Integration
2. Submit a form that includes startDate and endDate
3. Verify that the Calendar Event entry does not reflect the submitted startDate and endDate

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.8.7

### Plugin version

2.1.9

### Multi-site?

No

**Comment by engram-design** [comment]
Thanks for PR! I'm wondering if we might have to factor in the different versions of the Calendar plugin though. But because this helper is used so little, I'm going to remove it altogether to prevent errors across both v4 and v5 of Calendar.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.9"`.

**Comment by markdrzy** [comment]
@engram-design You're totally right! Sorry, I was just so happy that it was this simple to correct in v5 that I didn't consider those still on v4. Really appreciate the speedy response!

**Comment by engram-design** [comment]
Fixed in [2.1.10](https://github.com/verbb/formie/releases/tag/2.1.10)
