### ISSUE TITLE
Translations of message

### ISSUE THREAD

**Issue by DavidKabelitz** [verbb/formie#1813]
### Describe the bug

Hi we are running multiple sites with formie,
since some time the error and success message on top of the form (not at the fields) is not translated anymore.
Messages and strings at language files never changed. Field messages are still fine.

### Steps to reproduce

1. Use a Success Message like: **Thank you very much! Your message has been sent.** or error message like **Please double-check your data.**
2.  Put both into the lang file (tested both formie.php and site.php)

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

Craft Pro 4.8.6

### Plugin version

2.1.9

### Multi-site?

Yes

**Comment by engram-design** [comment]
That would be due to the change where the text produces proper HTML with paragraph `<p>` tags. As such, when translating you'll need to provide a respective string in HTML, not just the raw text.

See https://github.com/verbb/formie/issues/1766 and my comment in https://github.com/verbb/formie/issues/1771#issuecomment-2006515719

**Comment by DavidKabelitz** [comment]
ah ok, thx...missed that one. Will change it! Feel free to close this ticket!
