### ISSUE TITLE
New dependencies for Formie 3.x.x

### ISSUE THREAD

**Issue by martinhellwagner** [verbb/formie#1848]
### Question

I've just updated Formie to `3.0.0-beta.8` with Craft `5.0.5` in order to test out the new version. I was surprised to see that Formie now requires the `verbb/auth` and `verbb/base` packages. What's the reason for these new dependencies, and will these packages be required after the beta version as well?

### Additional context

```
"craftcms/cms": "5.0.5",
"verbb/auth": "2.0.0-beta.2",
"verbb/base": "3.0.0-beta.3",
"verbb/formie": "3.0.0-beta.8"
```

**Comment by engram-design** [comment]
Formie has always required the `verbb/base` just like every other Verbb plugin.

We also use the `verbb/auth` module to streamline the integrations that use OAuth. In Formie 2.x, we had all the handling of tokens and auth in Formie itself, which seems like a lot of double-handling, and something that could be better handled through a dedicated and abstracted package.

Is there an issue with these dependencies for you? They're otherwise here to stay though.

**Comment by martinhellwagner** [comment]
If I'm not mistaken, those dependencies were never required explicitly in the `composer.json` file? We're using multiple Verbb plugins successfully in a range of projects, but never until Formie `3.x.x` we had to require the `verbb/base` dependency separately. I understand the issue about `verbb/auth` – is the functionality of this package used in another plugin too?

In general, we want to keep our `composer.json` file light and add new packages only when we really have to.

**Comment by engram-design** [comment]
You certainly shouldn't have to include it specifically in your own `composer.json`, it's part of our [dependencies](https://github.com/verbb/formie/blob/73a22b5aa5a061ea5c6bd067559c9adea5799ab2/composer.json#L41-L42)

It _might_ be due to the beta status of the package - what method did you use to install Formie 3.x? Did you get a warning about `verbb/base` and `verbb/auth` when you installed Formie?

**Comment by martinhellwagner** [comment]
I guess that notion with the beta status makes sense, yes. I updated the version number of Craft and Formie, then tried to run `composer update` – this is what I got:

![Screenshot 2024-04-25 at 08 41 05](https://github.com/verbb/formie/assets/19146752/a13211d3-30f9-406a-a354-dd62decd9503)

**Comment by engram-design** [comment]
Ah right, installing with `composer require "verbb/formie:^3.0.0-beta.8" -w` should be enough to get things sorted I believe!

**Comment by martinhellwagner** [comment]
While this works for Formie, the same issue arises with all other Verbb beta packages. It is satisfactory for me to know the reason though, and I'll be eagerly awaiting the non-beta versions of those packages. Thanks so much!

**Comment by engram-design** [comment]
I _think_ using the `-w` flag will get around that, but non-betas won’t be far away anyway
