### ISSUE TITLE
Issue with nested conditions

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#1855]
### Describe the bug

The conditions don't work properly with nested fields.
I'm not sure how easily this can be fixed.
please follow the steps to reproduce it.

### Steps to reproduce

1. Import the example JSON  [formie-colors.json](https://github.com/verbb/formie/files/15150059/formie-colorsForm-4a3f3011-1972-46b1-9983-91688195e5c9.json)
2. Check the option red and then green.
3. The group with the condition (color is red) is now visible and also the child element with the condition  (green is checked)
4. The group with the condition (green is checked) is also visible but not the child element with the condition (color is red) 
5.  Click the option red, now the child element red is visible
6. The opposite happens if the order of action is reversed.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload

### Craft CMS version

4.8.10

### Plugin version

2.1.13

### Multi-site?

No

**Comment by engram-design** [comment]
I see the issue here, and it's because we don't evaluate all conditions for the entire form anytime _anything_ has conditions on it. But then you run into these issues where the fields inside a Group field do need to be evaluated along with their parent.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.13"`.

**Comment by engram-design** [comment]
Updated in [2.1.14](https://github.com/verbb/formie/releases/tag/2.1.14)
