### ISSUE TITLE
File Upload throws error in 3.0.0-beta.15

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#1934]
### Describe the bug

When I use the File Upload field inside of formie with Client Side validation, I get a 500 error. Looking into the network tab, it throws the issue on FileUpload.php

![Screenshot 2024-06-17 at 15 20 23](https://github.com/verbb/formie/assets/20947573/b73f46b9-1d44-4026-ae29-34e1a6171980)

### Steps to reproduce

1. Drag File Upload on my form builder
2. Fill in all fields and select a file
3. Save fails

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.2.0

### Plugin version

3.0.0-beta.15

### Multi-site?

No

**Comment by engram-design** [comment]
I assume you have the throw-error-on-deprecation [setting](https://craftcms.com/knowledge-base/preparing-for-craft-4#fix-deprecation-warnings) enabled? A deprecation warning shouldn't otherwise throw an error like this.

But the underlying deprecated should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.15"`.

**Comment by cookie10codes** [comment]
Exactly, I have the deprecation check on DEV_MODE. Thanks 👍🏼

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.16](https://github.com/verbb/formie/releases/tag/3.0.0-beta.16)
