### ISSUE TITLE
JS Validation Event not firing on server side validation ajax

### ISSUE THREAD

**Issue by mattcdavis1** [verbb/formie#195]
**Description**
When client side validation passes but server side validation fails the onFormieValidate JS event does not fire and the Formie JS does not scroll to the error.

**Steps to reproduce**
1. Create a scenario where client side validation passes but server side validation fails

**Comment by engram-design** [comment]
`onFormieValidate` is not the correct event to listen to in this instance, and is primarily for client-side validation. Captchas also hook into this. You should instead be raising a `onFormieSubmitError`, which represents a server-side error - validation, or otherwise.

**However**, this event wasn't being thrown correctly in this scenario anyway. Should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.24",
  "...": "..."
}
```

Then run `composer update`.

**Comment by mattcdavis1** [comment]
Great - thanks!

**Comment by engram-design** [comment]
Fixed in [1.2.25](https://github.com/verbb/formie/releases/tag/1.2.25)

**Comment by thijskaspers** [comment]
Anything going on with the events? We can't get the 'onFormieSubmitError' to trigger (using AJAX form submission) with the latest Formie (v1.4.27)

Our code:

````
$("form.fui-form").on('onFormieSubmitError', function(e) {
    console.log('error!');
    e.preventDefault();
});
````

Above code never shows 'error!' in the console log. When we switch to another event, for example `onBeforeFormieSubmit` or `onFormieValidate` it works immediately with the same code. But when we switch to `onAfterFormieValidate` or `onFormieSubmitError` it doesn't fire.

**Comment by engram-design** [comment]
@thijskaspers Seems to be working for me. For example, adding a form with a required field, and disabling client-side validation will show your console error when submitting the form completely blank - correctly triggering `onFormieSubmitError`.

If you have "Validate Form on Submit" enabled (client-side validation) this even will never fire, because client-side validation will trigger before a submit-to-server has ever occurred.

Was it working differently on a previous version?
