### ISSUE TITLE
Shortest Data Retention possible

### ISSUE THREAD

**Issue by svondervoort** [verbb/formie#1954]
### Question

What is the best setup to have the shortest Data Retention possible?

Currently we are using the `afterSaveSubmission` event to do some magic mapping and sending data to AFAS (CRM). There is no mail notifications being send (as of now) and we would like to keep the submission and files as short as possible.

We have Data Retention set to 10 minutes and a cronjob setup to prune every 10 minutes `*/10 * * * * ./craft formie/gc/prune-data-retention-submissions`. But I am wondering if this can be even shorter since we use the `afterSaveSubmission` event since the magic logic uses the submissions data to map.

**Comment by engram-design** [comment]
I would say that if you can help it, to use a Daemon or similar rather than a cron job for speedy execution. With this approach you have a listener on your server continually listening to the queue and running jobs as soon as they are added.

But if your after submission code isn’t using the integration or email notifications stuff then there’s no reason you can put that retention down as low as you can.

You’ll also want to force garbage collection to run with `./craft gc`

**Comment by svondervoort** [comment]
Do you advice using `craft gc` instead of the build in formie `prune` command?

**Comment by engram-design** [comment]
Sorry, my mistake. Using the `./craft formie/gc/prune-data-retention-submissions` is the more direct way to action pruning. In fact, it's this command that is added to Craft's garbage collection service, which is only run at certain times. Running this command will ensure that submissions are pruned immediately.
