### ISSUE TITLE
More Top Level controls

### ISSUE THREAD

**Issue by svondervoort** [verbb/formie#1961]
### What are you trying to do?

Since it is possible for the client to create forms themselves (if we configure it that way) they can sometimes create scenarios which we would like to prevent.

### What's your proposed solution?

A few examples are:
- No data retention set (already an existing [issue](https://github.com/verbb/formie/issues/1223).
- A default upload directory for File input fields (so the root of the first alphabetic volume doesn't get flooded with uploads.
- Default behaviour configuration so at least each for has a thank you page if we would like to force that.

**Comment by engram-design** [comment]
This will be handled with the [field defaults](https://github.com/verbb/formie/issues/863) feature, where you can essentially setup a default form for all fields, integrations and form settings.

Still working on how this will look and act, but may very well be introduced similar to a Stencil, but instead of needing to apply the stencil, it's just the default of what the form looks like when it's created.
