### ISSUE TITLE
Failed to send notification email: Failed to authenticate on SMTP server with username \"office@****.at\" using 2 possible authenticators

### ISSUE THREAD

**Issue by steve-p96** [verbb/formie#1973]
### Describe the bug

Our client changed the password for its smtp server. I updated the current password and if I test it in the Control Panel under Settings -> Mail -> Test. I got a successful sent message. 

However, all "Sending form notification" tasks in the Craft Queue are failing with the following error message:

`Error | Failed to send notification email: {"error":"Notification email “User Notification” could not be sent for submission “1477001”. The mailer service failed to send the notification: “Swift_TransportException: Failed to authenticate on SMTP server with username \"office@****.at\" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code \"535\", with message \"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect.`

As a result, our client and the admins are not receiving notification emails for submitted forms.

(Info: The *** is used to hide clients informations)

### Steps to reproduce

1. Submit any form on the website

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

3.9.5

### Plugin version

1.6.35

### Multi-site?

Yes

**Comment by engram-design** [comment]
Formie doesn't mess around with the mailer settings for Craft, so typically if you can send a test email from Craft, it should work for Formie. Does the "test email" function in Formie work for the notification?

One other thing to check for is the sender address. This is default to the Craft-wide email, but can be overridden in Formie. Just in case that's a deciding factor.

Otherwise, I would be looking at any sort of caches to try and clear - possibly OpCache - although I would be surprised if it's a cache issue.

Seeing as though email settings are stored in project config, and typically you have `allowAdminChanges = false` on production, how are you testing the Craft email settings on production without access to the email settings? I guess I might also ask to check if the project config is indeed being applied correctly, just in case you've made this password change locally, and it hasn't applied on production. I'm not sure if you're using .env variables for the passwords, which would make that less or an issue.

**Comment by steve-p96** [comment]
@engram-design Thanks for your answer!

The "test email" function works for the notification.

<img width="368" alt="Bildschirmfoto 2024-07-09 um 09 23 35" src="https://github.com/verbb/formie/assets/149867553/814d9e3c-bc51-4a25-8103-8a47ae795729">
This is inside Formie, and it uses the variables stored in the .env files, so it should not have been overridden.

We tested it on stage with allowAdminChanges = true and encountered the same problem. For the credentials, we use .env variables, and they work so far; otherwise, the "Test" button in the Craft settings would fail.

The SMTP server is smtp.office365.com, so there might be some restrictions on Microsoft's side causing this behavior?

**Comment by steve-p96** [comment]
@engram-design 

Update: 
It was indeed a problem during our deployment. Our deployment process only updated the credentials for the web server, which is why the test mail worked as expected. However, the queue had a different PHP instance that was not restarted, so the queue continued to work with the old credentials.
