### ISSUE TITLE
GQL representation of Date field's available weekdays is an opaque string

### ISSUE THREAD

**Issue by tremby** [verbb/formie#1989]
### Describe the bug

This isn't actually problem for me since my implementation ignores this option, but it could potentially be a pain for others who are using it:

I noticed during development that the "available days of the week" option on the Date field comes back in GQL requests as an opaque JSON string.

I imagine that's not as intended, and it was meant to come back as a `[String!]!`, or something stronger typed.

### Steps to reproduce

1. Query via GQL for `availableDaysOfWeek` on a Date field
2. Receive for example `["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]` as one string.

### Form settings

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

### Craft CMS version

4.10.6

### Plugin version

2.1.22

### Multi-site?

yes

**Comment by engram-design** [comment]
I think this was just me being lazy, to be honest! It's probably a _tiny_ bit of a breaking change, so I might shift this to Formie 3.x, just because it's going to mess with people's handling of it from being a JSON string to an array.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.18"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.19](https://github.com/verbb/formie/releases/tag/3.0.0-beta.19)
