### ISSUE TITLE
Hubspot Integration API Error (HUTK)

### ISSUE THREAD

**Issue by carinameissl** [verbb/formie#2013]
### Describe the bug

Hey!
I have set up a CRM Hubspot integration in formie for my client and selected all the required scopes:
<img width="867" alt="Screenshot 2024-08-07 at 16 50 08" src="https://github.com/user-attachments/assets/a017e07f-d2f3-47d4-99be-7a7f04e1005f">

Setup and field mapping (map to form) was successful and the forms can also be submitted successfully. However, the data in Hubspot does not trigger a form submission, but somehow generates new forms with form and field handles.
<img width="515" alt="Screenshot 2024-08-07 at 16 56 16" src="https://github.com/user-attachments/assets/03da5de0-1b2d-4b4e-9756-10577c76a83e">

When triggering the integration manually using the dropdown in the form submission, it shows a server error pop-up and in the log files I get the following error: 
"Hubspot: API-Fehler: “{"status":"error","message":"The request is not valid","correlationId":"0c21d2b1-306e-401e-9aa8-8552d120af21","errors":[{"message":"Error in 'context.hutk'. '37184' is not a valid Hutk","errorType":"INVALID_HUTK"}]}” /app/current/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113"

<img width="2103" alt="Screenshot 2024-08-07 at 16 50 56" src="https://github.com/user-attachments/assets/d67639d1-9423-48d7-8acc-3bf943d94214">
<img width="2554" alt="Screenshot 2024-08-07 at 16 48 29" src="https://github.com/user-attachments/assets/8d1ba99a-3087-4645-bafd-cfd0f50c070e">

In the formie [changelog](https://plugins.craftcms.com/formie/changelog) i found the following in a beta version: 
HubSpot CRM integration now automatically saves the hubspotutk cookie at the time of submission, to be sent with API requests. This means you now no longer need to map a form field to ensure the hubspotutk tracking cookie is sent.
Could that be the issue / is there a workaround without adding bigger updates?

Thanks for support!
Carina

### Steps to reproduce

1. add hubspot integration
2. map to form
3. submitt + test Hubspot data
4. trigger integration manually

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes or No
- Custom Form Templates: No

### Craft CMS version

4.10.3

### Plugin version

2.1.20

### Multi-site?

No

**Comment by engram-design** [comment]
So firstly, HubSpot is going to try and be smart by automatically adding any form used on your website as a submission on their end. While a neat idea, this creates duplicates and those selector-style submissions in HubSpot. This is because HubSpot's JS is monitoring form submissions and sending it to their server. That's not anything to do with Formie.

So you'll want to disable that, and let Formie send the data to HubSpot. In HubSpot, go to Settings > Marketing > Forms > Non-Hubspot Forms. Ensure that `Collect data from website forms` is disabled.

Resources:
- https://community.hubspot.com/t5/Lead-Capture-Tools/Hubspot-Automatically-Creating-a-Form-and-Causing-Duplicate-Data/m-p/407323
- https://knowledge.hubspot.com/forms/use-non-hubspot-forms

Secondly, on the error with the tracking code can you let me know what field you're mapping to the "Tracking ID" in the integration settings for the form?

You're correct that in Formie 3 for Craft 5, we've improved this handling to be automatic, for Formie 2 you'll need to be careful about what you map to that. It has to be a proper HubSpot token. I've written suggestions [here](https://github.com/verbb/formie/issues/1225#issuecomment-1786457575) on how to achieve this, as it requires getting the token from client-side to server-side.

**Comment by carinameissl** [comment]
Thanks for the quick response! Will make sure that `Collect data from website forms`  is disabled. 

As for the "Tracking ID", I am currently mapping the "ID" field of the form:
<img width="1272" alt="Screenshot 2024-08-08 at 09 17 29" src="https://github.com/user-attachments/assets/0e672295-5a3e-46b6-a948-8c96c988633a">
Will try to add a hidden field as you suggested thanks!

**Comment by engram-design** [comment]
So yep, the "Tracking ID" has to be the HubSpot Tracking ID, it can't be anything else like the Submission ID, which is why it's going to complain. The other issue I linked to is going to take the Tracking ID that's generated via [HubSpots JS Tracking](https://knowledge.hubspot.com/reports/install-the-hubspot-tracking-code#install-the-tracking-code-on-your-website), add it to a hidden field, and you map _that_ hidden field to "Tracking-ID" in your HubSpot integration settings.
