### ISSUE TITLE
Updating flags.png

### ISSUE THREAD

**Issue by joepagan** [verbb/formie#2015]
### What are you trying to do?

Improve page speed performance scores, flags.png is not a "next-gen" format.

![image](https://github.com/user-attachments/assets/9112a7f6-a631-46ed-bbc3-a0d1ea5776a6)

### What's your proposed solution?

It looks like you use: https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/img/flags.png 

However, webp and a 2x version was introduced in `v23.5.0` of this library.

If the lib is used could you perhaps update intl-tel-input?

If just the URL it used, doesn't look like cloudflare cdnjs has a later version of this lib so you could update to use these urls instead:
- https://cdn.jsdelivr.net/npm/intl-tel-input@23.8.1/build/img/flags.webp
- https://cdn.jsdelivr.net/npm/intl-tel-input@23.8.1/build/img/flags@2x.webp

**Comment by engram-design** [comment]
Nice one, glad they've updated the library with those image versions. 

I'm probably going to keep this restricted to Formie 3, as it _might_ be a breaking change. It's also where we last updated the `intl-tel-input` library, as the flags did change slightly. 

I'm quite protective about browser support for the front-end, because unlike Craft's control panel, we need to cater to a lot of users. I'm aware the [support](https://caniuse.com/webp) is good for webp, but there are some edge cases like quite recent Safari versions and iOS.

So we'd need a way to support a fallback for the PNG files, and that requires feature detection on Formie's end. I'm not exactly thrilled about including the required JS for this, and from what I've found the browser detection methods load about 3-4 fake WEBP images to see if it's supported. That's not an amazing solution if I'm honest, especially from a third-party plugin like Formie enforcing that - it starts to feel a little intrusive.

With that in mind, Formie 3 will now serve WEBP flags by default, and no WEBP support detection. To opt out of this behaviour, you can add a `no-webp` class anywhere in the document (with something like [modernizr](https://modernizr.com/) or your own detection). This will be up to the end user of Formie to determine if they need extended browser support.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0"`.

**Comment by engram-design** [comment]
Updated in [3.0.1](https://github.com/verbb/formie/releases/tag/3.0.1)

**Comment by thisisjamessmith** [comment]
I must be doing something wrong here...? I've upgraded from 3.0.0-beta to 3.0.3 but I'm still seeing the old blurry flag icons -  and also the dropdown looks like this, with the other flags cut off (using default templates/rendering with no overrides): 
<img width="210" alt="image" src="https://github.com/user-attachments/assets/2a0a79ce-2666-4c92-b2e8-89fb8bde33da">

Edit to add: sorry, the cut-off flags are caused by my base stylesheet, but can't figure out why they're still blurry/lo-res.

Aside: it would be even nicer if I could disable this functionality altogether - I'm not convinced it's worth an extra 39Kb of JS just for this.

Edit again: sorry again, realised now that it is in fact using a (very large) .webp image sprite, it's just blurry.

**Comment by engram-design** [comment]
As in you’d like an option just to disable the country flags, but still use the JS input, or remove the JS handling for the phone field entirely?

**Comment by thisisjamessmith** [comment]
Optionally disable the functionality entirely (in Settings > Forms > Fields) - so just a text input with `type="tel"`. If a client wants a fancy area-code selector they should pay extra for it in my opinion.

**Comment by engram-design** [comment]
So that's pretty much the functionality of the "Country Enabled" setting on the field, it'll just disable the phone field's JS. Adding that as a global setting is something [we're working on](https://github.com/verbb/formie/issues/863)

**Comment by thisisjamessmith** [comment]
Thanks Josh - being able to set some global default settings will help a lot - even better if you can bake-in the ability to visibly remove certain settings (and/or field tabs?) altogether. The problem for me ultimately is that in an ideal world I don't want to use any of Formie's CSS or JS (which obviously you've made perfectly possible in lots of different ways), but going down that route then means the CP UI is full of vast amounts of advanced functionality that I'll need to painstakingly re-implement on the front end.

From a commercial perspective, each of those bits of advanced functionality - whether it's conditional field branching or repeater fields or multi-page functionality, or even simply the ability to reposition the submit button, should, for us, be a chargeable piece of work. (I realise I can disable fieldtypes on a case-by-case basis, but unfortunately that only gets me half-way where I'd like to be).

Semi-related (and sorry to hijack this GH issue, maybe better as a Discussion), just wondering if you have ever considered creating a (hugely!) cut-down "lite" edition of Formie? Apologies it's my first time trying this plugin after years of Freeform so I'm not familiar with its history etc. Your blog post about why you created Formie in the first place rang very true for me, but Formie as it is remains equally if not more feature-rich than Freeform. Yet 80% of the websites we build just need an extremely simple form builder (this niche used to be reasonably well-filled by Solspace's Express Forms, but they've discontinued it).

**Comment by engram-design** [comment]
That referenced issue is going to cover just about every bit of UI for the form builder to customise for that reason.

We've actually purposefully stayed away from editions unlike Freeform/Express Forms/Sprout Forms. Purely because we want to pack everything into Formie to give users bang for buck without having to switch between editions, pay for more functionality later on, and just keep things simple. From a cost perspective, it's why Formie is priced the way it is, and there's lots more big features to come like Quizes, Survey and Polls all without an additional cost or plugin. For the lowest cost at $99, you get more functionality than any other plugin for the same feature set.

I totally get how you're handling things with your client, but Formie is all about giving power to the content editor, without going too far in the Wordpress-end (clients can and will make a mess of things), and without the need (too much) of a developer. 

Formie indeed came out of the idea that for 80% of sites we were doing, we just wanted a simple contact form, that a client can edit and love to use, and just work. In that instance, we want to install something that content editors can use with ease and grow. Our experience often started that a client wanted a simple contact form, 4 fields and an email - done. But 2 months later - they want Mailchimp connected to it, or they're getting lots of spam and need a captcha, or they need multiple emails to go to places. They were never impressed when they wanted more than one form, they need another version, or if they want integrations, they need yet another version.

We've _sort of_ toyed with a free version of a single contact form, or even a $49 version, but there actually hasn't been much of a demand (at least to use directly) about it. Never say never though! We always love to hear feedback from the community on this sort of thing.

**Comment by thisisjamessmith** [comment]
I don't think there's any value in a free version that's limited to a single form - as you hint, even for the simplest of sites, there's a still a reasonable probability they'll at some point want more than one form (this is why I would never choose Freeform's entry-level version, confusingly named the same as their old Express Forms plugin). The _old_ Express Forms plugin worked very well though - ultimately it was just the absolute basics, with enough events/hooks that a developer can extend the functionality with custom module code.

Our project scopes are tightly defined, so if it doesn't specifically say that, e.g., Mailchimp integration is included then it won't be, and they'll not be surprised to have to pay us more to have that part built.

**Comment by engram-design** [comment]
It’d be my aim to keep a single version but just give you a lot more control over a bunch of aspects about access and features exposed to your clients. Unless of course the pricing is the issue (understandably for low budget sites $99 can be a lot)
