### ISSUE TITLE
Cleanup translations

### ISSUE THREAD

**Issue by jeroenlammerts** [verbb/formie#2063]
### What are you trying to do?

I think the Formie (en) translations should be cleaned at some point. The file is way to bulky to check manually.

### What's your proposed solution?

There are a lot of country names added as translations. Maybe formie could make the advantage of this package.
https://github.com/commerceguys/addressing/blob/master/src/Country/Country.php
Craft uses this for the country field, it includes translations for a lot of languages.

There are some redundant messages which could possibly stored in a different way. For example:
```
'Enter your {name} App Key here.'
'Enter your {name} Application ID here.'
'Enter your {name} Auth ID here.'
'Enter your {name} Auth Secret here.'
```

**Comment by engram-design** [comment]
There's bulk in there for the [Bulk Options](https://github.com/verbb/formie/tree/craft-5/src/options) we have, which does include countries. I believe this was well before the address field came to Craft, so it can indeed be streamlined more now with the Craft native Address field. We already use the `commerceguys/addressing` package as well.

As for the `Enter your ...` values, you're probably right these can be streamlined.

I've just undertaken a bit of review of things
- Removed Countries, States (Australia, Canada, US), Weeks, Days, Months from translations
- Streamlined integration settings instructions to use `Enter your {name} {label} here.` vs `Enter your {name} API Key here.`
- Streamlined integration form settings instructions to use `Whether to map form data to {name} {label}.` vs `Whether to map form data to {name} Contacts.`
- Most integration descriptions are now dynamic.

There's a few others I'd love to handle like Languages and Currencies, but these rely on other packages that aren't locale-aware, and we'd have to provide them as translatable in Formie anyway. Looking into options.

Otherwise, yes there is a lot of text to translate, but it is a big plugin! Let me know if you see anything else that's glaringly inconsistent and can be improved.

Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.29"`.

**Comment by engram-design** [comment]
Updated in [2.1.30](https://github.com/verbb/formie/releases/tag/2.1.30)
