### ISSUE TITLE
JS Error when using Repeater Field in Multi-Page form

### ISSUE THREAD

**Issue by veronika-g** [verbb/formie#210]
**Description**
I created a Multi-Page form. On one page I added a repeater field. The error occurs on each page, where the repeater item isn't integrated.

![Bildschirmfoto 2020-11-10 um 14 56 25](https://user-images.githubusercontent.com/71814882/98683136-f93a9580-2364-11eb-8615-9661d09e0bfd.png)

**Steps to reproduce**
1. Create a Multi-page form with 3-4 pages
2. Add a Repeater item to the 2nd Page
3. Go through page form and check the console logs

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.25
- Craft version: 3.5.14

**Comment by engram-design** [comment]
This should probably be changed to a warning, as in this case, it's okay the JS can't find the repeater field, because it's in a page that hasn't been loaded yet.

In addition, we might add some better handling to make JS page-aware when "Page Reload" is the submission method. For Ajax-based forms, the entire form content is loaded on-page, so it's not an issue in that scenario.

**Comment by engram-design** [comment]
Fixed in [1.2.27](https://github.com/verbb/formie/releases/tag/1.2.27)
