### ISSUE TITLE
Console error on multi-page form with phone number fields

### ISSUE THREAD

**Issue by jwrudzin** [verbb/formie#246]
**Description**
I have a multi-page form with phone number fields on one of the pages. When I'm on a different page of the form (a page that does not have the phone number fields), I'm getting a console error for each phone number field:

`VM8610 phone-country.js:1 Unable to find #formie-form-262030 #fields-assignment-submission-ins-related-office-phone`

**Steps to reproduce**
1. Add a phone number field with country dropdown to multi-page form.
2. Navigate to a page of the form that doesn't have the phone number field.

### Form settings
- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.2
- Craft version: 3.5.16
- Multi-site: No

**Comment by engram-design** [comment]
Are you sure you're using Ajax submission? This is somewhat of a known issue with page-submit forms, because there's no nice way to determine if the field is on the current page, or a future page, so it plays well with Ajax forms.

I can't replicate this for Ajax, but I can for page-submit, which is fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3). This overhaul of JS fields fixes many issues, but also addresses my former issue.
