### ISSUE TITLE
Setting unknown property: craft\behaviors\CustomFieldBehavior[field] when trying to preview a notification in a stencil

### ISSUE THREAD

**Issue by Antimated** [verbb/formie#263]
**Description**
Installed formie and looked at the default stencil's notifications. I keep getting a 500 error "Setting unknown property: craft\behaviors\CustomFieldBehavior[field]". Doesn't matter if it's a new stencil or the default one provided when installing the plugin.

![Image 2020-12-15 at 3 34 00 PM](https://user-images.githubusercontent.com/2869409/102228456-04945a00-3eeb-11eb-8215-491dd93df892.png)

**Steps to reproduce**
1. Install formie
2. Open the default contact stencil or create a new one
3. Add some fields (if you create a new one)
4. Open up a notification

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax (does not really matter)
- Client-side Validation: Both
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.3
- Craft version: Craft Pro 3.5.16
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [1.3.4](https://github.com/verbb/formie/releases/tag/1.3.4)

However, you may need to re-save your name fields (and the stencil/form). There was a bug that was flipping the name fields from not being a multiple field after a notification modal was opened.

Let me know if you still have this issue though.
