### ISSUE TITLE
Option 'Output JavaScript' = off still includes 'formie-base-form.js' in FE

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#27]
### Steps to reproduce
1. Create custom template in CP
2. Set option 'Settings' > 'Output JavaScript' = off
3. Apply template to form
4. Visit form in FE

### Expected
`formie-base-form.js` and `formie-form.js` are no longer included in FE HTML

### Actual
`formie-base-form.js` is still included in FE HTML

### Use case
I would prefer to include these files as JS imports in my main JS file
```
import '../../vendor/verbb/formie/src/web/assets/frontend/dist/js/formie-base-form';
import '../../vendor/verbb/formie/src/web/assets/frontend/dist/js/formie-form';
```

### Form settings
- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

### Additional info
- Plugin version: 1.0.7

**Comment by engram-design** [comment]
This is expected behaviour. The base JS contains critical JS to allow for reCAPTCHA to work, along with a few other things like form event hooks.

See https://verbb.io/craft-plugins/formie/docs/developers/front-end-js#disabling-js

To completely remove this, you'll need to override the templates with custom templates. At least for the time being. We'll consider better ways to handle this, but it might end up being a significant support issue if people don't understand the ramifications of removing the base JS.

I can see how in your case it's valid.

**Comment by engram-design** [comment]
Let's keep this open as I'd like to circle back to a better solution on this.

**Comment by engram-design** [comment]
Things have gotten an overhaul in [1.1.1](https://github.com/verbb/formie/releases/tag/1.1.1), and this addresses this specifically, along with a few other improvements that should handle your use-cases better.

Have a read of the [docs](https://verbb.io/craft-plugins/formie/docs/developers/advanced-js) and let me know!
