### ISSUE TITLE
User Integration and no password field type

### ISSUE THREAD

**Issue by mark-chief** [verbb/formie#281]
**What are you trying to do?**

I am using Formie to create a user registration form on the front end. Full Name, Email etc.. It's the workhorse behind this member app. But the fundamental issue is that there is no Password type field in the form builder.

In a poor attempt to get around this I used a text input and set `type="password"` and then mapped that field to the Craft user password field in the integrations tab of that form. But then of course the issue with this is that the password stored as plain text in Submissions for everyone to see, or seen output on the site!

Mapping the fields to the user registration:
<img width="883" alt="Screenshot 2021-01-07 at 17 52 42" src="https://user-images.githubusercontent.com/18699249/103926832-63777880-5111-11eb-87f6-531a8407bebb.png">

Password in plain text in Submissions
<img width="721" alt="Screenshot 2021-01-07 at 17 53 06" src="https://user-images.githubusercontent.com/18699249/103926828-62464b80-5111-11eb-98d1-01a23fce4333.png">

This is a big deal as I was planning on leveraging Formie forms to run this app. have i approached this incorrectly or is there a solution i have missed? Thanks!

**Comment by engram-design** [comment]
I'll need to give this some further thought. I'd rather not create a Password field, which is extremely specific (gotta keep those fields wieldy), so I think the plan would be to add a method of obscuring the content.

We can't _not_ store the content from the user, because integrations can happen after the submission is submitted (being in a queue), but it's certainly not great storing that in any case. We might even need to provide a means to opt-out of storing content per-field, or obfuscating content per-field.

My other, maybe more simple approach is that once the user element is created, Formie can update the submission to wipe out the field being mapped to the password field, that way, it's gone for good. Do you think that might be an adequate solution?

**Comment by mark-chief** [comment]
Hey Josh, thanks for your ideas. 

I think once a User account is created, there is no need for that password data to be stored as it’s been sent to Craft. So I think your later suggestion might work best for this use case? 

I’m not sure how you could implement that because it’s just a text input with a type of password, so perhaps a setting that says “wipe this fields data after submit” in that fields settings. 

Thanks!

**Comment by engram-design** [comment]
I was thinking I could look at whatever field you're mapping to the password attribute on the user element, and wipe that content. Formie at least knows what content and field you want to go into the password attribute of a user.

I'll go with that for now! I think a Password field, while useful, is pretty limited as a niche use-case. But, we'll let others comment here if this needs to be developed.

**Comment by engram-design** [comment]
Added in [1.3.9](https://github.com/verbb/formie/releases/tag/1.3.9)

**Comment by engram-design** [comment]
FYI, password field on the roadmap - https://github.com/verbb/formie/issues/366
