### ISSUE TITLE
FR - being able to drag and drop existing fields or current form fields into a group 

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#3]
### Description
Title says it all! You can't currently drag and drop into a group either:
* a field on the current form
* an existing field

### Steps to reproduce

1.
2.

### Additional info

- Plugin version:
- Craft version:

**Comment by engram-design** [comment]
This likely won't be implemented, sorry - there's some complications to this. Mostly, because we have to deal with also moving submission content from one content table to another, and it's a bit risky for my liking.

Under the hood, Group and Repeater fields act like Matrix fields, with their own content tables for the fields they contain. That's the reason you can't freely drag and drop fields in and out of the fields, because you'd be trying to do the equivalent with Matrix. I'm aware Neo allows you to re-use fields, but that's another story.

This _might_ be a bit more feasible with Craft 4/5 having field instances, so we'll likely revisit that after a major refactor on Formie's end.

For now, and the near future, Group/Repeater fields will their own collection of fields.
