### ISSUE TITLE
Add SharpSpring Native Form Integration

### ISSUE THREAD

**Issue by strandofgenius** [verbb/formie#332]
**What are you trying to do?**
SharpSpring has recommended connecting to form endpoints especially when there is more than one form on a page otherwise the their native scripts could conflict. 

Currently you can map fields to create a new contact, but aren't able to map them to forms natively in SharpSpring. Since this is one of our main CRMs we would find it really handy to connect directly to a form and map the fields. It would be nice to have the ability to work with page reload or and ajax form submission.

**Comment by engram-design** [comment]
After some investigation, I'm not quite sure how to tackle this one. There's no API endpoint to fetch forms or their fields, and the method they provide to directly post submissions to native forms is pretty client un-friendly. From what I can tell, you add their embed code to the page and then supply the fields you want to map - but this is a manual step, you can't fetch the fields automatically, so that's **very** likely prone to error, and not ideal for clients to manage.

Unless I'm missing something obvious, and you might have a better idea of how this can be implemented?

In particular, looking at the [GravityForms](https://help.sharpspring.com/hc/en-us/articles/115002760192#h_118550907141525719201409) page, you can see with their code generator, we'd have to allow free-text fields to supply the SharpSpring field name in the form settings.

It looks like there's a "mapping process" described [here](https://help.sharpspring.com/hc/en-us/articles/115001067968-Mapping-Native-and-3rd-Party-Forms) but that required adding their JS embed code, filling out the form, then mapping the values in _SharpSpring_. And if your form in Formie changes, you have to do this again.

**Comment by strandofgenius** [comment]
>There's no API endpoint to fetch forms or their fields, and the method they provide to directly post submissions to native forms is pretty client un-friendly. 

Yes, I totally agree on this part. When using Gravity Forms in the past we had to create a new function specific to each form so that we could send the body response to a form endpoint which would show us the fields from the form and then could map it to custom fields within SharpSpring.

Again, here is the doc that helped me with [Submitting Directly to Native Form](https://help.sharpspring.com/hc/en-us/articles/115002321292-Submitting-Directly-to-Native-Form-Endpoints#h_696513482141525961674752).

Here is how they create a function for [Gravity Forms](https://help.sharpspring.com/hc/en-us/articles/360029624032-Connecting-Gravity-Forms#h_30582fb6-9bfd-4f2d-8959-20b18d3d76d8). It seems as though the PHP example has changed some from what it used to be. They are specifying the baseURI and endpoint within form fields now. But this is an example of what we've used in the past.

```php
add_action( 'gform_after_submission_2', 'post_to_third_party_2', 10, 2 );
function post_to_third_party_2( $entry, $form ) {
	$baseURI = 'https://app-XXXXXXXX.marketingautomation.services/webforms/receivePostback/XXXXXXXXXXX/';
	$endpoint = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX';
	$post_url = $baseURI . $endpoint;
	$body = array(
		'First Name '=> rgar( $entry, '4.3' ),
		'Last Name' => rgar( $entry, '4.6' ),
		'Email Address' => rgar( $entry, '9' ),
		'Phone' => rgar( $entry, '11' ),
		'trackingid__sb' => $_COOKIE['__ss_tk']
	);
	$request = new WP_Http();
	$response = $request->post( $post_url, array( 'body' => $body ) );
	GFCommon::log_debug( 'gform_after_submission: response => ' . print_r( $response, true ) );
}
```

I think two things could be helpful to us.

1. Relate a Formie submission to a SharpSpring form submission to understand the life of the lead.
2. Potentially have a way to have a select option to assign leads to a list created in SharpSpring.

I am proposing that there would be a way to add a SharpSpring form endpoint and baseURI to the CRM integration settings. This would allow each form to have its own unique endpoint and allow multiple forms to be on one page.

<img width="1329" alt="Screen Shot 2021-03-05 at 10 29 43 AM" src="https://user-images.githubusercontent.com/11370639/110144396-ea597200-7d9d-11eb-8880-9a22256b5c94.png">

For the second point, in the case of event registration, I've needed the ability to add people to a "transactional" list that captured multiple emails at a time. It first created the lead and then added them to the list. This may be out of scope of a core feature, but could end up being something we come across again when developing in Craft instead of WordPress.

There are things such as double opt-in to consider. If they checked a box then let them be subscribed to a list. SharpSpring does allow us to do workflows that can send emails to people and confirm their email addresses or added to a list if they filled out a particular form. But again that means that connection needs to be setup first.

**Comment by strandofgenius** [comment]
@engram-design since the release of `1.4.0` any idea when this might be looked at again?

**Comment by engram-design** [comment]
@strandofgenius Didn't make it for the `1.4.0` release, but I'll need to wrap my head around this one again and it looks like a complex solution.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
