### ISSUE TITLE
Allow environment variable as Email Notification recipient

### ISSUE THREAD

**Issue by marionnewlevant** [verbb/formie#341]
**What are you trying to do?**
I would like to be able to have the recipients of email notifications vary based on the environment. They should go to me for testing in development, and to someone else in production

**What's your proposed solution?**
The most standard way to do this is with environment variables: [https://craftcms.com/docs/3.x/config/#environmental-configuration](https://craftcms.com/docs/3.x/config/#environmental-configuration)

**Comment by engram-design** [comment]
I'll look into a way to handle this for sure. For now, I'd recommend using the [testToEmailAddress](https://craftcms.com/docs/3.x/config/config-settings.html#testtoemailaddress) general config setting.

**Comment by engram-design** [comment]
So I probably should've looked at the code before answering, as this is already possible at the moment. Just use the usual `$VARIABLE_NAME`.

I'm not looking to add the auto-suggest behaviour like elsewhere in Craft because it can suggest **any** environment variable - most of which aren't emails. As such, it'll make little sense to clients.
