### ISSUE TITLE
Add  ability to trigger notifications for submissions on status change

### ISSUE THREAD

**Issue by mrtomtom** [verbb/formie#367]
**What are you trying to do?**
A user submits a form, its status is "New", the submission is reviewed by admin and is has it's status changed to  "Approved" or "Rejected" (or similar). On change if there are conditional 

**What's your proposed solution?**
Have a second option when saving "Save and send notifications" or an option to select and send one of the notification emails.

**Comment by engram-design** [comment]
I'm a little bit concerned by the implications of this request, and it might prove unexpected results, or be prone to mis-firing of emails from clients changing statuses of submissions. The status condition is hidden away from view, so it's not always evident changing a status will immediately trigger an email notification.

As a general rule, email notifications are only done on initial submit. After this, if you want to re-trigger notifications (or integrations), it should be a direct and deliberate action. There's no telling if changing the status of a submission will re-send or trigger emails. This is especially true if you're toggling between statuses multiple times - that means multiple emails!

I suppose we could introduce a warning that shows when you're about to make a status change that would result in an email notification being triggered, but that's not going to work for bulk actions to change the status in the submissions index.

As of [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21) when editing a submission, you can select any email notification and send that on-demand - nothing tied to conditions or statuses which might help the second part of your issue.

**Comment by amphibian** [comment]
This came up with a client today, which led me here. A couple of thoughts:

- Craft Commerce already works this way - changing an order's status will by default trigger that status' email. So there's precedent for this behaviour.
- I don't see this as being very dangerous in terms of unintentional emails, since it would require that someone had already explicitly set an email to be triggered only when a specific status was met as a condition. SO presumably they'd know what that status change entailed?
- You could _not_ trigger the email when a status is changed _and_ the new status is also the default status, to prevent "initial" notifications from being re-sent.

**Comment by engram-design** [comment]
I’ll mention this has already been implemented in Formie 3 for Craft 5!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
