### ISSUE TITLE
Custom rendering: render submit button 

### ISSUE THREAD

**Issue by SanboKyo** [verbb/formie#406]
I would like render the submit button, because I need the value of the label. 

I try it with the "field.handle == submit", but that does not work.

**Comment by engram-design** [comment]
The submit button isn't treated like a field. It depends on your templating you're using, overriding the entire form, or using hooks, or otherwise. Can you share your template code so far?

The submit button(s) are actually derived from the form pages, particularly for multi-page forms, where you can have multiple buttons. If you need to get the settings from them, from the control panel, you'll need to fetch them from the current page.

If this is a single-page form:

```
{% set currentPage = form.getCurrentPage() %}

{{ currentPage.settings.submitButtonLabel }}
```

Or for multi-page forms, where you're looping through multiple pages:

```
{% for page in form.pages %}
    {{ page.settings.submitButtonLabel }}
{% endfor %}
```

You might also find it much easier to create a "Form Template", set it to a directory of your choosing in your project, and supply a `_includes/submit.html` template, so you can override the submit button template.

**Comment by SanboKyo** [comment]
Thank you, "currentPage.settings.submitButtonLabel" was what I needed! (That is not in the documentation, is it?)

**Comment by engram-design** [comment]
It's not, I'll add some documentation about submit buttons shortly. Currently, this is only shown in the [default templates](https://github.com/verbb/formie/blob/craft-3/src/templates/_special/form-template/_includes/submit.html)

**Comment by medoingthings** [comment]
@engram-design is there a way to set the submit button label? I need to change it, depending on a template condition. Something like:
```twig
  {% do page.setSettings({
    submitButtonLabel: 'New Button Label',
  }) %}
```

**Comment by engram-design** [comment]
@medoingthings This is only possible in Formie 3.x, but you'll be able to do:

```twig
{% do form.setPageSettings(0, {
    submitButtonLabel: 'New Button Label',
}) %}
```
