### ISSUE TITLE
Allow 'Dropdown' field labels/values to be dynamically populated prior to rendering the form

### ISSUE THREAD

**Issue by anchovy** [verbb/formie#415]
**What are you trying to do?**
Want to programmatically populate the options for a dropdown field before using the default form render tag, as the current `craft.formie.populateFormValues` function doesn't work for dropdown fields.

**What's your proposed solution?**

A new formie function to poulate option labels/values i.e. `populateFormOptions()`

```
 {% set form = craft.formie.forms({ handle: formHandle }).one() %}
 {% do craft.formie.populateFormOptions(form, { dropdownField:  [{"label": "One", "value":"1"},{"label": "Two", "value":"2"}] }) %}

 {{ craft.formie.renderForm( formHandle ) }}
```

**Additional context**

**Comment by anchovy** [comment]
Ok - found another way to do this via...

```
{% do form.setFieldSettings('dropdownField', {
    options: [{"label": "One", "value":"1","isDefault":false},{"label": "Two", "value":"2","isDefault":false}],
}) %}
```

As per https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-fields#override-field-settings, maybe the docs for populateFormOptions could be updated to point to setFieldSettings for dropdowns etc.

**Comment by engram-design** [comment]
Yep, that'd be the correct way to go about it, as you're _technically_ editing the settings of the field, not the values. Then again, it's a bit of a weird case for dropdowns and other option fields in that these could be seen a "values" to pick from.

I'll add a note to the docs!

**Comment by anchovy** [comment]
@engram-design - sorry to open this again. Now with my dropdowns being populated dynamically on form render, I'm getting a validation error on submitting the form?

 `Select your FILEL_LABEL is invalid.`

Seems like unless the selected value actually exists in the options defined in the form dropdown field, any dynamically added values are rejected?

To test this out - I added one option to the dropdown with the value that will match one of the dynamically injected options.
Options, 1 'real' option:
![image](https://user-images.githubusercontent.com/599005/113951421-a3144480-9867-11eb-8d42-bfcc5039dc8b.png)

If I select this and submit for it works.
![image](https://user-images.githubusercontent.com/599005/113951448-b2938d80-9867-11eb-98f1-156f129b7000.png)

If I select one of the other options that do not actually exist then it's rejected.
![image](https://user-images.githubusercontent.com/599005/113951458-b9220500-9867-11eb-8e2e-30b8f97e48cb.png)


These options are being generated by specific categories with some exceptions - I tried adding a categories dropdown field assigned to the correct category thinking that this would 'contain' all the correct values. But dynamically inserting the options doesn't work for this type of field. 

Any tips on how to get this to work? I know I could set this field to be a text field and replace it with a dropdown at rendering, but I'd prefer to continue to use the `{{ craft.formie.renderForm( formHandle ) }}` - I don't particularly want to have to loop through the fields individually etc.

Thanks in advance.

**Comment by engram-design** [comment]
Yeah, that's a great point. You can't select from an option if that option doesn't exist, but dynamically adding them circumvents that to a degree, but isn't really "adding" them as options to the field. I'll see if there's anything I can do about this.

You mentioned trying out a Categories field, with the display set to dropdown, which should work. You can use an event to modify the categories query to exclude certain options, if that helps?

You could also override the hidden field template if you wanted to go down that route, without having to loop through fields. Create a Form Template, and point it to a folder you nominate (`_forms` for example). Then create a file `_forms/fields/hidden.html` with the following:

```

{% set attributes = {
    type: 'hidden',
    id: options.id,
    name: field.handle,
    value: defaultValue
} | merge(field.getInputAttributes()) %}

{% if field.handle == 'myFieldToOverride' %}
   ...
{% else %}
    <input {{ attr(attributes) }} />
{% endif %}
```

That way, you can override _just_ the template for a hidden field, and control how that's rendered

**Comment by engram-design** [comment]
The more I think on this, the less inclined I am to make this work, from a data consistency point of view.

Say you have a Dropdown field with values "Item 1" and "Item 2". I can allow setting these options dynamically in the template, and can fix the validation issue. You might dynamically add "Item 3", but once saved to a submission the value won't be valid, or even appear. This is because we need some way of storing the dynamic options you've set, at that specific time in your templates against the submission. Right now, there's no way to handle that.

Say you keep modifying this dropdown field for all sorts of dynamic values. You'd end up with values in the dropdown field that were never defined in the field, and technically invalid. Looking at these values across multiple submissions, and the values for this field will not be in the options you've defined, so it'll be inconsistent. I'm thinking of when people export submission content, they'll get values that are invalid, which is pretty common.

This also begs the question on the scenario - what if the client removes values from a dropdown field? We'd get the same scenario. That's probably something for another day.

And finally, this is all the same concerns for Checkboxes or Radio fields.

So at the moment, the recommended approach is to use a hidden input field with some template alterations, or a Categories field, with some tweaks to the element query.

**Comment by engram-design** [comment]
So - this will now be possible to override field settings properly, and they'll even persist after the submission has been made, in 1.5.0 (see https://github.com/verbb/formie/issues/478).

**However** I'd recommend anyone wanting to achieve this to really, **really** think about potential consequences of this from a data consistency point of view, as you're essentially creating on-demand options for fields (Dropdown, Checkboxes, Radio Buttons). As I've mentioned in https://github.com/verbb/formie/issues/415#issuecomment-815438161 this can lead to a multitude of different possible options for your fields across submissions. At that point, you're almost mis-using the purpose of option-based fields (as being able to only pick/check from a set, defined list of options).

Overriding other fields, or other settings is totally fair game, it's more around altering the options for some fields.

But, if you're aware of this, and want to throw caution to the wind, you'll be welcome to going forward!

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
