### ISSUE TITLE
Allow Mailchimp Email list ID to be set through front-end

### ISSUE THREAD

**Issue by shoored** [verbb/formie#419]
**What are you trying to do?**
In a multi-site setup the client often uses different email lists for different target audiences, for example Dutch and German visitors. 

We usually create one specific form that we use for multi-sites, where labels and such are translated. 
It's currently not possible to map the Mailchimp Email list ID to something dynamic. We would have to create duplicate forms for all sites to be able to have a different List ID assigned.

**What's your proposed solution?**
It would be great, if the value of the Mailchimp Email list ID could be set on the front-end with a hidden field or a Form option override, or something. 

```
{% set form = craft.formie.forms.handle("formHandle").one() %}
{% set listId = someCustomLogic ? "12345" : "54321" %}

{% do form.setSettings({
  mailChimpListId: listId
}) %}
{{ craft.formie.renderForm(form) }}
```

**Comment by engram-design** [comment]
Hmm, this might be tricky in practice, just because of how the mapping is setup. For instance, one list might have one setup of fields, another list might have another. It therefore makes it a bit tricky to setup mapping correctly, if the destination list is dynamic.

In addition, it probably won't be able to ever work in the way you propose, despite it being ideal, as that value needs to be saved against the form for use in the queue job, which happens after the initial render and submission. As such, when it gets to processing the integration to send to Mailchimp, the dynamically set setting will no have persisted.

I'm thinking I'll need to add a property to map a field value to, so you'll need a hidden field to provide the List ID of the list you require. It still doesn't address the difference in list fields, but I'll leave that for another time.

And lastly, you can probably achieve what you need right now using events, specifically `beforeSendPayload` - https://verbb.io/craft-plugins/formie/docs/developers/events#the-beforeSendPayload-event - where you could alter the `$event->payload` and `$event-> endpoint ` to resolve to the values of your hidden field where you'd supply this listId.

```
Event::on(Mailchimp::class, Mailchimp::EVENT_BEFORE_SEND_PAYLOAD, function(SendIntegrationPayloadEvent $event) {
    $listId = $event->submission->listId;
    $emailHash = md5(strtolower($event->payload['email_address']));
    
    // Update the endpoint to resolve to our list
    $event->endpoint = "lists/$listId/members/$emailHash";
});
```

**Comment by shoored** [comment]
Thanks for the quick response. If that event hook can achieve the same thing, I can definitely try and work with that. 

The way you describe the adjustments that need to be made, and the pitfalls, make this sound more like custom logic and probably not something that should be a core feature? The whole mapping of the fields does make this very tricky, although in my case I don't need the difference between lists. But, that's obviously something you have to think about when you provide the option to have dynamic list ID' at all.

If you do consider this a nice feature, then by all means, go for it. But I'm okay with closing it for now and try to fiddle with the event hooks.

**Comment by engram-design** [comment]
I'll leave this open as I think we'll implement this. The caveat will be that if you want to go down this option, you really need to ensure your lists are the same, but I think that'll be extremely common such as your scenario.

Have a go at hooking into the events for the time being, but we'll add this to our todo list.

**Comment by engram-design** [comment]
Added for the next release. You can now use the following:

```twig
{% do form.setIntegrationSettings('mailchimp', {
    listId: '123456',
}) %}
```

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
