### ISSUE TITLE
Misleading 'Saving' animation in CP

### ISSUE THREAD

**Issue by mizmiz** [verbb/formie#45]
### Description
If I change the select in Form > Appearance > Form Templates the 'saving' animation is displayed on the 'Save' Button. But nothing gets saved.

### Steps to reproduce
1. Select custom template in Form > Appearance > Form Templates
2. Reload page

### Expected
Setting is updated or no 'saving in progress' animation

### Actual
Setting is not updated

### Form settings
CP

### Additional info
- Plugin version: 1.0.8

**Comment by engram-design** [comment]
I think this is semi-expected behaviour as the fields available for a form can potentially change. We wanted to at least show some sort of indicator that _something_ is happening when you switch this option. Maybe we just move that loading indicator elsewhere, to beside the actual dropdown field.

This field acts the same way as changing the entry type on an entry by the way. cc @jaydensmith

**Comment by engram-design** [comment]
Fixed in [1.1.1](https://github.com/verbb/formie/releases/tag/1.1.1)
