### ISSUE TITLE
Getting Failed Captcha “Javascript”: “” on quite a few submissions

### ISSUE THREAD

**Issue by nitech** [verbb/formie#460]
**Description**
Launched site the 1st and discovered today that quite a lot of the submissions were marked as spam because of **Failed Captcha “Javascript”: “”**

Turned off the JavaScript integration and now things work fine. I don't really need the JavaScript integration since I enabled ReCaptcha, but perhaps other users have problems with this. 

### Form settings

- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.27
- Craft version: Craft Pro 3.6.11.2
- Multi-site: Yes

**Comment by nitech** [comment]
Actually also getting some submissions marked as spam because of duplicates - although the submissions are not duplicates. I ended up also turning off the duplicates detection integration.

**Comment by engram-design** [comment]
Tricky to troubleshoot as it does depend on a whole lot of factors with your setup. It's not immediately reproducible on my end.

Does your site use static caching? Or even Craft's caching? 

For duplicate submissions we actually don't check the content of the submission each time (maybe we should), but we check a unique value that's generated when the page loads. For ajax-based forms, this is tricky because this token is only created once, so if the user tries to submit another form straight away without refreshing the page, that'll be marked as a duplicate. Granted, there's not much "smarts" to this captcha mechanism.

**Comment by nitech** [comment]
I am using Blitz for static caching and I have implemented Formie using the [Static Caching Template Guide](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms#static-caching) (although I now see I forgot to include the polyfill for fetch and promise.)

**Comment by engram-design** [comment]
@nitech Ah, that may the key to this. I'll need to expose some endpoints to refresh the tokens for various captchas (JS, Duplicate and Honeypot) for this to work on static-caches sites, just like we do for the CSRF token.

And yep - I've had one or two sites have issues with `fetch()` due to clients being on older browsers, so figured best to include that for an easy copy-paste solution.

**Comment by nitech** [comment]
Okay, thanks for the reply. I thought everybody used static caching ;-) Great plugin btw. I am enjoying using it.

**Comment by jhealey5** [comment]
Using the same approach as OP here and getting the same issues, only way I found to prevent it so far is to disable the JS & Duplicate spam filters.

**Comment by engram-design** [comment]
For the moment, yes disable the captchas if you use static cache. I'll introduce endpoints to refresh these captchas for static cached sites.

**Comment by engram-design** [comment]
This should be much improved for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.21.1",
  "...": "..."
}
```

Then run `composer update`. Refer to the [updated docs](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms) on handling static cached forms which includes a centralised token-refreshing endpoint that handles CSRF tokens and any captchas that need it (Duplicate and JavaScript).

I've also added better "Spam Reason" text for these captchas when they fail, rather than the _super helpful_ `“”`.

**Comment by engram-design** [comment]
Added in [1.4.22](https://github.com/verbb/formie/releases/tag/1.4.22)
