### ISSUE TITLE
Max character count on text field is 1 too short

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#463]
**Description**
I have a text field with a 25 character limit.
When validating the field while typing, everything goes ok.
But when hitting submit while the field has the maximum amount of characters allowed, the validation fails.
So it seems the field counts 1 character too short.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.27
- Craft version: 3.6.11.2
- Multi-site: Yes

**Comment by engram-design** [comment]
I can't seem to replicate this behaviour, even downgrading to 1.3.27.

Just to clarify, you're getting this on the front-end?

![image](https://user-images.githubusercontent.com/1221575/117520967-944bb980-afee-11eb-92da-d812f54cce79.png)

And then submitting this, the error returns `Limited to 25 characters.`?

I've tested with a 24 and 25 character string. Trying to enter anything longer won't work, due to the `maxlength` property being set on the input itself.

**Comment by TomDeSmet** [comment]
Yes on the frontend. And only when hitting submit. Very weird. I’m not doing anything special with it either. 

Could it be a combination of fields or is there anything that could have an influence I need to check?

**Comment by engram-design** [comment]
Very strange. If you could post the exact error you're getting? 

Also, just to confirm its:

- an Ajax form
- a single-line text field
- Validate Form on Submit enabled?
- Validate When Typing enabled?

If you can provide a video recording, that's be amazing too - only if not too much trouble. I've tried just about every combination I can think of.

I'm interested if this is a client-side error, or a server-side error as well. It'd be great if in your testing when you hit Submit, the Network tab of developer tools could be open, just to see if it's hitting the Formie endpoint, and its a server-side error?

**Comment by TomDeSmet** [comment]
I'll close this issue for now because I'm not able to reproduce it locally either.
Maybe it's a server side thing. Very strange. It's for a competition that'll end very soon, so it's no big deal.
