### ISSUE TITLE
Notification emails are sent only when submissions is called

### ISSUE THREAD

**Issue by SanboKyo** [verbb/formie#486]
**Description**
Notification emails are sent only when formie's submissions is called in control panel

**Steps to reproduce**
1. Send a form
2. No email is sent
3. Call formie's submissions 
4. Email will be sent

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.4.5
- Craft version: 3.6.16
- Multi-site: No

**Comment by engram-design** [comment]
If you're referring to how you need to visit the control panel in order for email notifications to send, that's by design.

Formie’s email notifications use Craft queue system. This is for good UX when people submit a form, that they don’t wait for the email to be delivered (which is notoriously slow) and any integrations that are fired. However, by default, Craft’s queue will only be run when you visit the control panel.

Have a read through the [docs](https://verbb.io/craft-plugins/formie/docs/feature-tour/email-notifications#sending-emails) which describes this behaviour.

But you can turn off running things via the queue via the [Config settings](https://verbb.io/craft-plugins/formie/docs/get-started/configuration) or through Formie’s settings in the control panel. I’d strongly advise to look at keeping this on, and using a cron job, or daemon to run the queue as suggested in this article - https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

**Comment by SanboKyo** [comment]
Sorry, I have overlooked that.

I have now set up a cron job and it works great. Thanks!
