### ISSUE TITLE
Loading forms dynamically

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#51]
### Description
Looking at the docs, it doesn't look like there's an easy way to load forms dynamically and the accompanying JS etc. For example on a site using barba.js

I assume it's kind of like loading a cached form, in that you need to render the JS dynamically, but the tag `{% do craft.formie.registerAssets('form') %}` only seems to work within a page with a body tag.

If there's a 'nice' way to do that I'd love to know!

### Steps to reproduce

1.
2.

### Form settings
Please pick from the options below.

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Additional info

- Plugin version:
- Craft version:

**Comment by engram-design** [comment]
I'm not actually familiar with barba.js - looks neat!

Without diving into an exact example setup (which I'm happy to do), what will be the ideal outcome for your needs? Would it still be a Twig tag to output the HTML for the form, and separate Twig tags to insert the CSS and JS respectively a the given place?

For instance, you might just want to dump the require JS inline, in the `<head>` or before the `</body>` tag. With this direct way to output the JS - that'd be ideal right?

**Comment by bleepsandblops** [comment]
> Without diving into an exact example setup (which I'm happy to do), what will be the ideal outcome for your needs? Would it still be a Twig tag to output the HTML for the form, and separate Twig tags to insert the CSS and JS respectively a the given place?

Yes exactly.

> For instance, you might just want to dump the require JS inline, in the <head> or before the </body> tag. With this direct way to output the JS - that'd be ideal right?

Yes but I would still do it on a "need to know" basis:

- a person might go on the site but never visit the form page, so I don't want to load that JS for them
- with "ajax transitioners" like barba.js or highway, the HTML content within the main div changes dynamically, so I don't think then the formie JS would pick that up. Hence it needs to be loaded every time a form is added dynamically to the page, so that formie can register its even listeners etc.
- but otherwise yes, I would just dump it whenever a form is loaded, not just by default in the head or body.

FWIW I've been doing it in Freeform using this https://docs.solspace.com/craft/freeform/v3/developer/js-plugin.html#loading-freeform-js-manually

**Comment by engram-design** [comment]
Excellent, thanks for the clarification, I'm currently setting things up to better deal with async modules like Vue, so this will be timely to include with that

**Comment by joeRob2468** [comment]
Just wanted to chime in on this, since this plugin looks amazing, and adding support for dynamic forms would let me use this plugin on our sites. I use Highway.js and a matrix block system for content, and forms would most likely be added as one of those content block types. 

In my case, I tend to hook into page transition events, check to see if a block that needs a specific JS setup exists on the new page, then run initialization scripts. Then, when a new page is loaded afterwards, I run destroy methods on all the JS for the previous page, to clean up any event listeners and libraries that were added before, then run through the initialization process for the new page. I use Webpack to import all the libraries I need on specific pages asynchronously, and create ES6 classes for each of the larger sections. 

 In a perfect world, it'd be super helpful to be able to just output the form HTML inside a block template, then on the JS side, check if a Formie element exists on the new page, and asynchronously load the Formie scripts (in a es6 module if possible) and initialize them for each form on the page (saving each instance of a form in an array). Then, when a new page is changed, I'd use a destroy() method on each of the form instances to clean up any listeners and prepare for the new page. 

I think I'd suggest creating a base CSS file for all forms that could be included in a theme, and scoped style tags inside the form HTML template for each form (to avoid needing to inject any form-specific CSS asynchronously). For the JS, it'd be helpful to have a JS library for Formie that would let developers create individual instances of each form that can be initialized, listened to for Formie events, and destroyed at any point. I think that would work pretty well with Vue and other frontend libraries as well, since all the JS functionality could be decoupled from the page templates. Setting up the library as an ES6 module would help futureproof it as well, and could allow it to be easily loaded asynchronously using Webpack bundling. 

That library could grab the JS config for each form using data attributes, or adding an API route to get the config info using AJAX or GraphQL, or even by including a json object with all the settings for each form inside the form HTML template ([here's a way I've done that before](https://quipblog.com/efficiently-loading-inlined-json-data-911960b0ac0a)). That way, the HTML template could hold all the data and styles for each form, and the JS library could be loaded asynchronously and initialized/hooked into/destroyed without relying on injected code. 

To summarize:
-  no injected JS using craft.formie.registerAssets (since that probably won't work for dynamic forms)
-  Global generic CSS styles for all forms could be included in theme manually, or included on every page using craft.formie.registerAssets without including JS
-  Form HTML + form config data output using twig tag
-  Form-specific CSS included using <style> tags for each form in the HTML template
-  Formie scripts in separate file/module, to load asynchronously, use config data for each form, and manually instantiate/use/destroy when needed. Could also expose global Formie JS object on all pages instead of writing separate library, but we'd lose async loading - would still need manual initialization and destroy() function. 

Really not sure if this is even helpful, and I might be way off on how to handle things, but maybe knowing my use-case will help!

**Comment by engram-design** [comment]
Excellent write-up @joeRob2468 and that's something I'm currently working on. There's a bunch of different scenarios to cover.

`craft.formie.registerAssets` will very likely be no longer applicable so much after these changes.

I haven't actually considered the CSS side of things, as that's far less dynamic and variable. I was going to provide a tag for `{{ craft.formie.renderCss(handle) }}` to allow insertion of the CSS where you need. This probably only needs to be output once, not really per-form.

We could have styles inline, but for multiple forms on the page, that's a whole heap of duplicated CSS.

`{{ craft.formie.renderForm(handle) }}` will remain to render just the HTML of the form, not including any assets. CSS/JS output can be disabled for the form template, to allow for manual output, or manual init.

What my current plan with the JS was to output the config of a form to `window.FormieForms`, as opposed to containing it within the form's HTML. Not sure which option I prefer, as we could easily do:

```
<form id="123">
  <div class="fui-form-config" data-json="{formId:123, settings:{etc...}}"></div>
```

I'll have to consider any potential issues with this.

From this, you'll have access to `Formie.getFormByHandle(handle)` which give you an instance to the form's JS to do whatever you like with it. You can also choose to initialise the form yourself with `Formie.initForms()` for all on a page, or `Formie.initForm(handle)` for a specific one.

There's also massive complications with dynamic CSS/JS depending on the fields used. For instance, if you have a Repeater field in your form, it'll require some CSS/JS included just for that form. If you don't have a Repeater field, then it won't be included. For this reason, I'm thinking we'll need to switch to more of a module approach with dynamic imports.

There's also currently race conditions with how the JS is being initialised currently, likely before Vue/React have spun up and created the v-dom. For instance, in your `mounted()` method in Vue, you might use `Formie.initForms()` to initialise all forms present on that page. That's also being addressed.

I like your outlined suggestions, as I think they're pretty developer-friendly when you want to get more advanced with things.

**Comment by engram-design** [comment]
Things have gotten an overhaul in [1.1.1](https://github.com/verbb/formie/releases/tag/1.1.1), and keen to see how it suits your use-cases.

Have a read of the [docs](https://verbb.io/craft-plugins/formie/docs/developers/advanced-js) and let me know!

**Comment by bleepsandblops** [comment]
Thanks a lot!! Just testing it out, having issues using the example from the docs in "Importing via modules".

This line (changed the path to match my folder structure - which may be the underlying issue):
`import { Formie } from '../../../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib';
`

getting lots of errors in my laravel mix:
`
ERROR in ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-form-theme.js
Module not found: Error: Can't resolve 'core-js/modules/es.array.filter' in '/Users/seb/sites/fml/vendor/verbb/formie/src/web/assets/frontend/src/js'
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-form-theme.js 4:0-41
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-form-base.js
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib.js
 @ ./js/main.js
 @ multi ./js/main.js ./scss/main.scss
`

and 
`
ERROR in ../vendor/verbb/formie/src/web/assets/frontend/src/js/utils/bouncer.js
Module not found: Error: Can't resolve 'core-js/modules/es.array.filter' in '/Users/seb/sites/fml/vendor/verbb/formie/src/web/assets/frontend/src/js/utils'
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/utils/bouncer.js 1:0-41
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-form-theme.js
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-form-base.js
 @ ../vendor/verbb/formie/src/web/assets/frontend/src/js/formie-lib.js
 @ ./js/main.js
 @ multi ./js/main.js ./scss/main.scss
`

and there's a few more.

**Comment by engram-design** [comment]
Interesting, I'm not getting this testing with another Laravel Mix setup.

Would you mind sending through your `package.json`, `package-lock.json` and `webpack.mix.js` file? There's no reference to `core-js` in these files.

**Comment by bleepsandblops** [comment]
Ah-ha!

It was an issue in my `webpack.mix.js` file (attached).

If I comment those lines:
`
.polyfill({
  enabled: true,
  useBuiltIns: "usage",
  targets: {"chrome": "58", "ie": "11"},
  debug:true
});
`
then the error goes away.

(I have to say I'm not entirely sure what I'm doing with those lines)
[webpack.mix.js.zip](https://github.com/verbb/formie/files/5050491/webpack.mix.js.zip)

**Comment by engram-design** [comment]
Depends if your project requires polyfill-ing. We use that often on projects. I feel like you might need to install `core-js` - maybe that's not installed? I feel like I've come across a similar situation.

However, this isn't to do with Formie, or it's JS (https://github.com/scottcharlesworth/laravel-mix-polyfill/issues/6#issuecomment-481754952) so closing

**Comment by joeRob2468** [comment]
Thanks so much for adding in this feature! I've tested it out on my setup, and it's working perfectly for the most part - I'll definitely be using this plugin for clients from now on. The only thing I was curious about is the destroyForm() method (I can open a new issue if you'd like). I've noticed in [formie-lib.js](src/web/assets/frontend/src/js/formie-lib.js) that the only things happening when a form is destroyed is that the script embeds are being removed - all the event listeners for the form remain active (most of them are on the document element, I think). 

I think most browsers will garbage-collect events when elements are removed from the DOM, but since most events for Formie are added to the document element, they stick around after the form element is removed.  

Ideally, when a form is destroyed, all the associated event listeners for validation, submission, recaptcha, etc would also be removed, to avoid any conflicts with other pages/forms and make sure things are fully cleaned up. That's particularly important when custom validations/integrations are added (especially anything that would poll for changes, or update regularly instead of relying on field change events, since they'll error out if their target DOM element is missing). Something as simple as just calling a destroy() method on each of the related scripts to remove listeners, and adding a way to destroy custom integrations, would be amazing.  

I know it's kinda a huge pain to keep track of each event listener and remove them, but it's pretty important. I know the Bouncer form validation library comes with a destroy method, and to make things easier, [this might be a good starting point for creating namespaced events, similar to JQuery's namespace feature](https://stackoverflow.com/a/44426162), which could be modified to let you add all events to a parent element (like document), then remove anything with a specific namespace with one function call.

**Comment by engram-design** [comment]
Probably best to open a new issue if possible.

Most events are bound to the `<form>` element, their fields, or some are on the document as required. It's my understanding that when the `<form>` DOM element is destroyed, these (custom) event will be garbage collected, like `onBeforeFormieSubmit` is bound to the form element. Granted, there are a few exceptions which can certainly be cleaned up.

> Something as simple as just calling a destroy() method on each of the related scripts to remove listeners, and adding a way to destroy custom integrations, would be amazing.

Not quite sure I follow on this point, specifically the "way to destroy custom integrations"?

But yes, I was eyeing a events class to help manage this sort of thing.

**Comment by engram-design** [comment]
@joeRob2468 See https://github.com/verbb/formie/issues/115
