### ISSUE TITLE
Access form submission field data in custom email template

### ISSUE THREAD

**Issue by joelzerner** [verbb/formie#530]
**What are you trying to do?**
For a custom email template, it would be great to have a bit more control over the output of the All Fields tag. Looking at the example template below, you'll see the way the fields output as text lines rather than table columns ends up looking fairly messy.
https://snipboard.io/W1VJvl.jpg

**What's your proposed solution?**
I'd like to see a way to loop through the fields using the Submission object so this could be hard-coded into a custom template. There doesn't seem to be a way to do this currently unless I'm missing something.
https://verbb.io/craft-plugins/formie/docs/template-guides/email-templates#available-template-variables
https://verbb.io/craft-plugins/formie/docs/developers/submission

**Comment by engram-design** [comment]
So the content produced by the "All Fields" tag is derived from the email template you provide for the field. Indeed, the defaults are pretty "standard" so you can totally customise them.

The first option is to start with [Custom Templates](https://verbb.io/craft-plugins/formie/docs/template-guides/email-templates#custom-templates) (just be sure to follow all the steps on that page to setup an "Email Template" in Formie). Here, you could replace _just_ the field you want to modify the HTML for (Address, Name for instance). Then, you'll still be able to use the "All Fields" tag.

Secondly, you could still use the variables one-by-one, rather than "All Fields", but that's a bit of maintenance work if you add/remove fields, you need to update the email notification content too.

Lastly, you can use Twig in the email notification content field, if you just want do DIY it, by looping through the fields of a submission.

**Comment by joelzerner** [comment]
Thanks @engram-design - by the way, I think you've done a great job with this plugin and can see the effort you've put into the user experience side of the form building process. I'm looking forward to introducing clients to this and I'm sure they'll find it nice to use.

I like the idea of the last option the most but am not quite sure what twig variables are available for access the submission and it's field. I've tried a few basic things but none of them seem to work. Could you please point me in the right direction here? I guess I want to avoid having to update a template for each field (first option) or individual field variables (second option).

**Comment by engram-design** [comment]
@joelzerner Thanks!

You'll have access to the following variables:

- `notification` | A Notification object, for current email notification.
- `submission` | A Submission object, for what the email is notifying about.
- `form` | A Form object, for what the email is notifying about.
- `contentHtml` | The HTML generated from the "Email Content" field for the email notification.

https://verbb.io/craft-plugins/formie/docs/template-guides/email-templates#available-template-variables

Something like the below should work:

```
{% for field in submission.getFieldLayout().getFields() %}
    {% set value = submission.getFieldValue(field.handle) %}
    
    {% if field.handle == 'someHandle' %}
        {# Output value #}
    {% endif %}

    {% if className(field) == 'verbb\\formie\\fields\\formfields\\Name' %}
        {# Output value #}
    {% endif %}
{% endif %}
```

As you can see, there's a lot to consider when outputting the value of the field, because each value has different values. Some simple strings, number, dates arrays, etc. Have a look at the [default templates](https://github.com/verbb/formie/tree/craft-3/src/templates/_special/email-template/fields).

You could also fall back on `{{ field.getEmailHtml(submission, notification, value) }}` for any field you don't want to modify from the default.

And I'll note that you don't need to update _every_ field's template, just the ones you want to override - in case that helps. I find that's by far the easiest method, and something you can apply to other projects if you like.

For instance, if you want to override just the Name field, you only need to provide the following template override folder:

- _emails
    - fields
        - name.html

That way, it's not so heavy-handed that you need to replace _everything_. You could then modify the [default template](https://github.com/verbb/formie/blob/craft-3/src/templates/_special/email-template/fields/name.html). It also keeps Twig away from client who won't understand it - but of course whatever works best for your scenario by all means.

**Comment by joelzerner** [comment]
Thanks for all that help and direction - much appreciated. That's given me the tools that I need to generate the output I'm looking for. Happy to mark this as closed now!
