### ISSUE TITLE
Name prefix select should have a default "Please select" option

### ISSUE THREAD

**Issue by joelzerner** [verbb/formie#531]
**What are you trying to do?**
The prefix field component included as part of the name field allows a default option to be selected but it doesn't currently have the option for an empty "Please select..." option to display as the default. I find this is often best practice for dropdown select fields as it forces the user to make an intentional choice rather than proceeding with the default value.

**What's your proposed solution?**
I'd recommend adding the "Please select..." option as a default to this dropdown field, and possibly to all dropdown fields in Formie. Maybe there's a way to enable/disable this as an option for each field?

**Comment by engram-design** [comment]
For this, and most other instances of dropdown fields in a field, you can use the "Placeholder" setting to set the a placeholder for the dropdown field. It'll add it as a blank, disabled option for the select field. The reason this isn't default is to allow you to turn this off, or change the text to what you like. 

On the prefix field in particular, it's also because the text "Please select..." is longer than all the values, so it does push the field width out a little. At least this way gives you the flexibility to change that to say "Select..."

**Comment by joelzerner** [comment]
Oh, that's perfect - I hadn't realised what the placeholder field was for and didn't event try it out. That's resolved it perfectly. No need to make any changes!
