### ISSUE TITLE
Sites dropdown list in the Submissions view seems useless

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#539]
**Description**
In case of Craft has multiple websites, the sites dropdown list in the _Submissions_ view (`admin/formie/submissions`) seems useless. This is even more useless as we can't setup Forms based on Craft's sites.

In my case, my other Sites were setup after Formie. When browsing the CP from another Site version than the Primary one, and then access to the Submissions view, I wasn't able to see the submissions until I switched to the Primary one.

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3 as 1.4.12
- Craft version: 3.7.7
- Multi-site: Yes

**Comment by engram-design** [comment]
It's not useless, submissions made on the corresponding sites are categorised into the site. Whilst forms and their fields can be site-specific, the submissions that are made on the form are.

For example, users might submit the form on "Contact Form" on Site 1. Then the user makes another submission on Site 2, using the same "Contact Form" (because it has to be the same across all sites - unless you create a new form for each site). 

These submissions would only be viewable in the submissions index by selecting the site they were made on.

This is the reason there's a `siteId` hidden input in the default template, so we can store the site the submission was made on. If you have custom templates, you'll want to add that too.

**Comment by romainpoirier** [comment]
Thank you for these clarifications!
