### ISSUE TITLE
GraphQL columnWidth always returns 12

### ISSUE THREAD

**Issue by cookie10codes** [verbb/formie#541]
**Description**
I'm trying to reach out to my form fields trough GQL, it seems like the columnWidth always returns 12. I have some fields that sit next to each other, so that should be columnWidth: 6 I suppose?

- Multi-page form: No
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.13
- Craft version: Craft Pro 3.7.8
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
`columnWidth` is deprecated (it's actually never been used). This is because during implementation we thought it presumptuous that people work to a 12-column grid system. There's no way to control the number of columns a field takes up, so they're always evenly spaced.

We don't even use this due to auto-column behaviour thanks to flexbox.

So best not to rely on this. In GraphQL, you'll want to query via `rows` then `fields` in order to get how many fields per "row" exist to get this number.

**Comment by engram-design** [comment]
Removed in [1.4.14](https://github.com/verbb/formie/releases/tag/1.4.14) FYI
