### ISSUE TITLE
"User full name" in notification bug

### ISSUE THREAD

**Issue by havardlj** [verbb/formie#559]
When using submission notification, the "User full name"-field produces a different user from who was submitting the form. All submission notifications so far has been the name of a user who has not made any submissions yet, nor does this user have admin access to Formie.

Edit: My name popped up on the latest notification, and my user doesn't have anything in common with the previous user on the notification.

**Steps to reproduce**
1. Create form
2. Add e-mail notification

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

- Plugin version: 1.4.14
- Craft version: 3.7.9
- Multi-site: No

**Comment by engram-design** [comment]
I assume you're talking about the "variable picker" in the "Email Content" field for an email notification?

The value of user-based content here highly depends on how you run your queue.

1. If you have `useQueueForIntegrations = false` these values will display as expected. If a user is logged in on the front-end and submits the form, their user values will be used.
2. If you have `useQueueForIntegrations = true` then it depends on if you have the queue processing set to be automatic, or run via the CLI.
    1. If `runQueueAutomatically = true` then whoever logs into the control panel will trigger the queue to run. This user will be used in content for this notification.
    2. If `runQueueAutomatically = false` things should work as expected, as you'll run the queue from a cron job or CLI. Hence, no user is available.

The main reason for this is because email notifications run in a queue environment (and can therefore be run potentially much later than submission) we don't save the user who made the submission on the front-end for later use.

To get around this, I would suggest:
1. Using hidden fields to record the User ID, User Email or anything else related to a currently logged-in user.
2. Enable "Collect User" on the form to have it automatically track a logged-in user (if there is one) against the submission.

I have made an improvement to this in the latest `craft-3` branch that will make these values work in any scenario so long as you enable "Collect User" on the form. This will save the currently logged-in user against the submission.

**Comment by engram-design** [comment]
Added the "Collect User" functionality in [1.4.15](https://github.com/verbb/formie/releases/tag/1.4.15), but all other cases are explained above.
