### ISSUE TITLE
Multiple page form with required fields failing on 'Next' click

### ISSUE THREAD

**Issue by dhmax88** [verbb/formie#56]
**Description**
Validation fails as pages of forms are hidden, therefore inputs aren't focusable.
`An invalid form control with name='fields[firstName]' is not focusable.`

**Steps to reproduce**
1. Create multi page form
2. Add required to fields in 2nd / 3rd page
3. Click first pagination button

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.1.1.1
- Craft version: 3.5
- Multi-site: No

**Comment by engram-design** [comment]
I can't seem to replicate this. Formie's JS should only validate the currently visible page. It's true for Ajax multi-page forms, each page is simply hidden and made visible when progressing to the next, but it should only be validating for the current page.

I've just done a quick example video where there's a required field on the second page. Can you let me know if there's anything that doesn't look right compared to your setup? If possible, shoot through a video (if you can), as I'd be interested if there's something critical I'm missing in my tests...

https://d.pr/v/EhBIXo

**Comment by dhmax88** [comment]
Hi Josh,

I'm using the implementation below:

```
{% set form =
	craft.formie.forms({
		handle: 'join'
	}).one()
%}

<form id="my-form" method="post">
	{{ csrfInput() }}
	{{ actionInput('formie/submissions/submit') }}
	{{ hiddenInput('handle', form.handle) }}

	{% for page in form.getPages() %}
		{{ craft.formie.renderPage(form, page) }}
	{% endfor %}
</form>

{{ craft.formie.renderFormJs(form) }}
{{ craft.formie.renderFormCss(form) }}
```

If I switch to only using `{{ craft.formie.renderForm('join') }}` then the form does work as expected.

**Comment by engram-design** [comment]
Ah, gotcha. The templates have changed a little on this point, so I need to update the docs to clarify. But then the docs are also incorrect in some places, so I've updated those - see https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-pages

You'll also want to make sure you're on [1.1.3](https://github.com/verbb/formie/releases/tag/1.1.3) where I've added these shortcuts.

You must have the correct `id` attribute on the form - at least for the moment. I may look at changing these to data-attributes down the track if people would like to use IDs for other things.

There's also a new compulsory `data-config` attribute in order to fire the JS, which sounds like it's not happening here.

If you can update, change your templates and let me know how that goes?
