### ISSUE TITLE
Import Form submissions from Database / Sheet

### ISSUE THREAD

**Issue by mariovass** [verbb/formie#585]
**What are you trying to do?**
One of our clients lost a bunch of submissions I think they accidentally deleted them. We have the backup, is there a way to import the submissions into the form?

**Comment by engram-design** [comment]
Due to submissions being elements, it's a little more complicated to restore from a backup, because you need to restore the records in the elements/elements_sites/content/formie_submissions/fmc_* tables, which can be tedious.

Submissions do support soft deletion, so you should be able to restore any trashed submissions - so long as they haven't been cleaned up.

We do plan on adding support for import/export of forms, which we might carry through to Submissions https://github.com/verbb/formie/issues/465 - either that or adding support for Feed Me.

**Comment by engram-design** [comment]
Added in [1.5.0](https://github.com/verbb/formie/releases/tag/1.5.0)
