### ISSUE TITLE
Form Template Success Message can't be altered only on AJAX

### ISSUE THREAD

**Issue by brandondeweese** [verbb/formie#588]
I created a Form Template to customize the appearance. Changed classes for "fui-alert-success". The changes happen fine on server on "Page Reload", but on "AJAX" the changes don't take effect. Am I missing something or is this a bug?

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax or Page Reload BOTH
- Client-side Validation: Yes 
- Custom Form Templates: Yes 

**Additional info**
- Plugin version:  1.4.18
- Craft version: Craft Pro 3.7.13
- Multi-site: No

**Comment by engram-design** [comment]
Yep, at the moment a `fui-alert` classed element is created when using Ajax because the alert (success and error) is generated through JS. I'll need to give this some more thought in how this can be editable and changed in JS.

**Comment by nordentwickler** [comment]
Hey there, any news on this issue?

**Comment by engram-design** [comment]
We've taken steps to remove opinionated classes in Formie 2 with theme config, but one last piece will be configuring the JS classes. We're almost there and should be finalised in the coming weeks.

**Comment by engram-design** [comment]
This now supports [Theme Config](https://verbb.io/craft-plugins/formie/docs/theming/theme-config) definitions.

```
{{ craft.formie.renderForm('contactForm', {
    themeConfig: {
        resetClasses: true,

        alertError: {
            attributes: {
                class: 'rounded-md bg-red-50 border border-red-200 text-sm text-red-700 p-4 mb-4',
            },
        },

        alertSuccess: {
            attributes: {
                class: 'rounded-md bg-green-50 border border-green-200 text-sm text-green-700 p-4 mb-4',
            },
        },
    },
}) }}
```

Using the above, Formie's JS will use the same classes that Twig uses to render the form.

If you're not using Theme Config (likely using template overrides), you'll still need to provide this to your render function, in the same way. Otherwise, Formie can't possibly know about your custom HTML - you need to tell Formie's JS what classes to use for components.

Added for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.10](https://github.com/verbb/formie/releases/tag/2.0.10)
