### ISSUE TITLE
Filter submissions by date range

### ISSUE THREAD

**Issue by torgeirbeyer** [verbb/formie#594]
**What are you trying to do?**
When changing the dates in the submissions pane I would like to only show the submissions within the date range. This would make it easier to make exports on a regular basis. 

**What's your proposed solution?**
I don't hav any solutions to this other than to build a custom front end template where our users can make the same export based on a date range. 

**Additional context**

**Comment by engram-design** [comment]
This is tricky in practice, because when you load the page it'll show _all_ submissions for the source you've selected in the sidebar, but these are paginated. You might have 1000 submissions, but only the first 100 are shown.

If we were to change the behaviour and only show the ones within the given date range in the chart area, there's no way to paginate submissions. You'd have to expand the date range, which could get cumbersome. It also makes it difficult to just see a total number of submissions for "all time" (it's shown in the pagination, e.g. `1-100 of 2,000`).

The chart is really there as an independent way to gain a snapshot of your submissions, and isn't a full-blown filter (which I believe is on the Craft roadmap).

I suppose there are two options:

1. Change the default date range for the chart to "nothing" so that it shows a chart of all time. This would then match the default output of submissions in the table. You could then restrict submissions using the date fields and the chart and table would match.
2. Add date range options to the export HUD, if this is only an issue for exporting.

**Comment by Kashkin** [comment]
One of our clients has raised these issues.

I do think the UI is confusing, particularly the "Total Submissions" label. The graph section looks like part of the overall UI, and not an isolated element.

Adjusting the presentation may clear up this confusion.

I think having a date range in the Export HUD would meet our client's requirements, if that's possible.

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/formie/releases/tag/2.1.0)
