### ISSUE TITLE
How we can get submissions based on multiple formIds ?

### ISSUE THREAD

**Issue by parwinderD4D** [verbb/formie#596]
**Description**
Hi Team, 

We want to display a list of all submissions done by users under different-2 forms. 
A. first user submit the form and we save the user id in the hidden field of the form which helps us to know user submit the form
B. Now we have a page where we have to show the list of all submissions done by the user.

**Step Followed**

Here is my code of what I am trying to do but not work.

`{% set ceFormHandleArray = ['23','213','43', '1', '10'] %} `
`{% set submissionsQuery = craft.formie.submissions()
						.formId(ceFormHandleArray)
						.orderBy('elements.dateCreated DESC')
				%}`

`{% set submissions = submissionsQuery.all() %}`

`{% for key, submission in submissions %}`
`{% if submission.userId == currentUser.id  %}`
`<tr><th scope="row">{{ submission.dateCreated|date("Y-m-d") }}</th><tr><th scope="row">{{ submission.name}}</th>`
`{% endif %} `
`{% endfor %}`
                                                 
But nothing display. Could you please check and let me know who I can make it workable or any alternatives. 
                                               

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method:  Page Reload
- Client-side Validation:  Yes
- Custom Form Templates:  No

**Additional info**
- Plugin version: 1.4.19
- Craft version: 3.7.13
- Multi-site: Yes  
 
 
 Looking Forward

**Comment by engram-design** [comment]
This can't be done, because submissions use the field layout defined in the form they belong to. Because you're using multiple different forms, the field layout can differ between forms, and in some cases clash (two different fields with the same handle). As such, it's not really possible to mix them, because you're asking submissions to combine when they have two different definitions.

My recommendation would be to loop through each submission, checking on the form. You could use group submissions by their Form ID.

The following example grabs all submissions for the current user, and uses the `| group` Twig filter to group them by their `formId` property. This is so that you can have all the submissions associated with a form grouped together. It's then a matter of looping through those grouped submissions.

```
{% set groupedSubmissions = craft.formie.submissions().userId(currentUser.id).all() | group('formId') %}

{% for submissions in groupedSubmissions %}
    {% for submission in submissions %}
        {% if loop.first %}
            {{ submission.getForm().title }}<br>
        {% endif %}
        
        {{ submission.title }}<br>
    {% endfor %}<br>
{% endfor %}
```

Producing something like:

```
Contact Form
Thu, 07 Oct 2021 14:12:32
Wed, 06 Oct 2021 10:27:30
Wed, 06 Oct 2021 10:14:23

File Upload Testing
2021-10-06 19:02:15
2021-10-06 18:59:51

Another Form
2021-10-01 11:48:12
2021-10-01 11:44:37
```

**Comment by parwinderD4D** [comment]
Thanks for the suggestion and its work for me 👍

**Comment by parwinderD4D** [comment]
@engram-design 

I am using the upgiven code which helps me to get all the submissions but I am not able to get the form filed value like : first name, Email, etc 

Please have a look at my code :


               
        {% set groupedSubmissions = craft.formie.submissions().userId(currentUser.id).all() | group('formId') %}{% for submissions in groupedSubmissions %}
        
        {% for submissions in groupedSubmissions %}        
            {% for submission in submissions %}
              <tr>
                 <th scope="row">{{ submission.dateCreated|date("Y-m-d") }}</th>
	         <td>{{ submission.title }}</td>
	         <td>{{ submission.firstName }} - {{ submission.email }}</td>
	      <tr/>
        {% endfor %}
    {% endfor %}

**Output Screen-shot** :

![image](https://user-images.githubusercontent.com/46927214/140894022-a5322998-0201-4448-972d-c1b05686d4db.png)


Here  `{{ submission.firstName }}`  `{{ submission.email }}` always display empty value. 
Could you please let me know how I can get these filed data?

Looking forward

**Comment by engram-design** [comment]
That's actually (somewhat) expected behaviour, because you're fetching subscriptions across potentially multiple different forms. As such, each form has their own field layout, and content table with where data is stored. Rather than take a massive performance hit by adding extra queries for _all_ submission queries to resolve the database and fields, you'll want to enforce the form for the submission query.

```
{% set groupedSubmissions = craft.formie.submissions().userId(currentUser.id).form('myFormHandle').all() | group('formId') %}
```
