### ISSUE TITLE
Consider marking Integration class "Request" methods as `public`

### ISSUE THREAD

**Issue by AugustMiller** [verbb/formie#599]
**What are you trying to do?**
We set up a Constant Contact integration in Formie to potentially send some data to a Client's account.

We'd _also_ like to use CC for some other custom features that Formie isn't well suited for (e.g. updating contacts based on user activity throughout the site, not bound to form submissions).

I thought I'd take a stab at loading up the Integration like this…

```php
$integration = Formie::getInstance()->getIntegrations()->getIntegrationByHandle(self::FORMIE_INTEGRATION_HANDLE);
```

…but when trying to call `->getClient()`, I discovered that the method was marked as `protected`, and inaccessible to the outside.

If this opens you up to security issues, I totally understand—just figured I'd ask, since you've done most of the hard work, already. The built-in OAuth/token management could be a huge time-saver—worth the license fee on its own!

**What's your proposed solution?**
Flag existing methods (or expose a new method) as `public` for plugins to interact with configured Integrations.

_Edit: This is probably better suited for a Discussion, huh? Sorry for the noise!_

**Comment by AugustMiller** [comment]
Ah, you know what—looking deeper, I see the entire OAuth token system _is_ accessible!

Going to keep digging here for a minute and see if this is truly moot. 🙃

**Comment by engram-design** [comment]
This is a good point, and something that came up in team discussions just the other day for another integration (also using OAuth).

So the idea is that rather than using the `getClient()` method directly, you'd use the `request()` method, which is a wrapper around Guzzle requests. This in turn uses the protected `getClient()` method to initialise the request.

```
$integration = Formie::$plugin->getIntegrations()->getIntegrationByHandle('myIntegration');

$response = $integration->request('POST', '/some/endpoint', [
    'payload' => [
        'data' => 'stuff',
    ],
]);
```

Here, you're grabbing the instance of the Integration, and calling the [`request()`](https://github.com/verbb/formie/blob/5d215d9ebc527c70c4ef4b6790f08b979251ba8e/src/base/Integration.php#L670-L675) function to do whatever you want, with the client already bootstrapped.

It's not really a security issue, and happy to open it up to third-party use-cases if that'll be easier for you to go nuts with it.

**Comment by AugustMiller** [comment]
Hey, thanks for getting back—and cool to hear I’m not totally off the rails with this. 😅

Unfortunately `Integration::request()` is also protected—but maybe if anything gets exposed, that’d be it?

In any case, I did end up being able to do exactly what we needed by reimplementing a bit of the `getClient()` method in our own service—so unless you are compelled to act on your own internal curiosity, I’m all for closing this or moving it to a discussion. Also happy to write up a little example of how we’re using it if it’d be helpful to others.

Thanks again, Josh! 😍

**Comment by engram-design** [comment]
I didn't even notice that, so great point. Consider it all opened up! https://github.com/verbb/formie/commit/688962a19543f62324b33a433c6390224eb7aaa2

**Comment by engram-design** [comment]
Updated in [1.4.21](https://github.com/verbb/formie/releases/tag/1.4.21)
