### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#641]
Is there a way to make login form with Formie, before visitor can fill fields.....

**Comment by engram-design** [comment]
Yep, you can make a login form with Formie, there's just a few things you'll need to do.

- Custom render the form, Formie's form templates are opinionated. We use `renderPage()` instead of `renderForm()`
- Change the field namespace
- Change the action input to go to the login controller, not Formie
- Field handles must be `loginName`, `password`, `rememberMe` as per https://craftcms.com/knowledge-base/front-end-user-accounts#login-form

```
{% set form = craft.formie.forms.handle('login').one() %}
{% do craft.formie.registerAssets(form) %}

<form method="post">
    {{ actionInput('users/login') }}
    {{ csrfInput() }}

    {% if errorMessage is defined %}
        <p>{{ errorMessage }}</p>
    {% endif %}

    {% if form.getRedirectUrl() %}
        {{ redirectInput(form.getRedirectUrl()) }}
    {% endif %}

    {{ craft.formie.renderPage(form, null, {
        fieldNamespace: '',
    }) }}
</form>
```

As we're submitting straight to the `users/login` controller, a submission won't be recorded.
