### ISSUE TITLE
[Question] Is it possible to use the label of a recipients field's selected option in a notification's subject line?

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/formie#657]
Hello,

I have a client who wants a "Reason for contact" dropdown on their form, and they also want the selected reason to appear in the notification's subject line and at the same time determine the notification's recipient.

Is this possible, using the recipients field? If not, is there a better way to accomplish this? So far, I haven't been able to find a simple solution. It looks like my best option is to set up multiple Notifications, one for each possible recipient and with the desired subject line, and use conditions to determine which notification to send.

Is there a better way of going about this?

(BTW, is GitHub the right place to ask questions like this, or would it be better to keep things like this on the CraftCMS Discord? I apologize if this wasn't the right place to ask!)

**Comment by engram-design** [comment]
That's a tricky one, and it's not supported yet, sorry! At least through the variable-picking functionality, because it assumes you want to refer to the value.

However you can achieve this through some Twig, which isn't ideal, but it might do in a pinch.

```
The subject {recipientsField.label}
```

Here, instead of using the variable-picker (which would essentially output `{recipientsField.value}`, you can use Twig to access the label attribute. You'd set this as the value for Subject.

This is the right place to ask questions I think some things can get lost in the Discord chat - particular if we're on different timezones. Always welcome.

**Comment by mtnorthrop** [comment]
@engram-design Thanks for your time and your response; this is exactly what I need!
