### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by redkrupp** [verbb/formie#663]
Multi-page form. The first page contains only the submit (or start the form text in my case) button. In the template I'd like to display some static content that will show up if forms' page equals to 1. I tried multiple conditionals based on docs but had no luck.

Please advise.

Additional question once the above works as expected (with your help of course) is there a way to manually trigger the form (by placing static button) to avoid first page of the form itself as it has no meaning or info other than a workaround I have to use in order to trigger the form and avoid displaying the form fields right away (self-assessment tool/quiz).

**Comment by engram-design** [comment]
Or reason to not use a hidden field on the first page (so that you can add another page), and then add a HTML field to add your static content on the second page?

Otherwise, if you do want to go for it and setup custom templates and conditionally check what page you're on, you'll want to use Form Templates to create an override folder, and override _just_ the `page.html` template.

In there, you might have something like:

```
{% if form.handle == 'myForm' and page.sortOrder == '1' %}
    My custom page template
{% else %}
    {# Render the default Formie `page` template #}
    {{ formieInclude('page') }}
{% endif %}
```

Here, we check if the form is the particular one you want to add your content to, and the `sortOrder` which is essentially the index of the page. The ID of the page won't work, which refers to the Field Layout ID.

You'll also notice the `formieInclude()` function, which actually falls back to the standard `page.html` template. This has the benefit of you not having to duplicate the Formie template and maintain that.

As for your second part I suppose there's a couple of different ways, although there's not an exact way to "skip" a form to a page.

1. You can set the form's current page to a speciflc page if you like. This is what the tabs behaviour does (if enabled), but you can also use it yourself.

```
{% set secondPage = form.pages[1] %}
{% set params = { handle: 'myForm' pageId: secondPage.id } %}

<a href="{{ actionUrl('formie/submissions/set-page', params) }}">Skip page</a>
```

2. Another option might be to create your "first page" completely outside of Formie in your templates. So the static text is part of the template, there's a button with a query string `my-form-page?start=true` (for example), and when clicking that button, the URL will update to that. You could then use `craft.request.getParam('start')` to check if someone has "started" the form by clicking the button, and then render the Formie form.
