### ISSUE TITLE
Allow miscellaneous integrations to register frontend HTML to forms

### ISSUE THREAD

**Issue by Mosnar** [verbb/formie#667]
**What are you trying to do?**
I needed to integrate [Chilipiper](https://www.chilipiper.com/) with Formie, so I wrote a "miscellaneous" integration. The service works by registering some Javascript and intercepting the form submit event to show a calendar. Currently, you can't register HTML to the form with anything other than a Captcha integration, as far as I can tell. To get around this, I had to use the "formie.form.end" hook in a module, check for the integration to to be active, and then inject my Javascript there.

**What's your proposed solution?**
Perhaps there's a way for integrations to either use the existing hooks or have the ability to render some HTML after the </form> tag simply with a function.

**Comment by engram-design** [comment]
I think the way you've approached it is the right way to go! It gets tricky with providing HTML from integrations, and only really works for captchas because they're slightly opinionated about the placement of their HTML (before the submit buttons on a page). My question would be in your scenario - where should the HTML end up being inserted?

**Comment by Mosnar** [comment]
I really just need to add some Javascript to load an external script and hook into Formie's frontend events. What if instead of rendering arbitrary HTML, there was a way to register some Javascript variables and perhaps an AssetBundle? That might do away with the HTML placement concern.

**Comment by engram-design** [comment]
Yeah, I think we can leverage what we have for some integrations (captchas) and fields, where they're loaded on-demand, only if the integration is included and enabled. I'll look into it!

**Comment by engram-design** [comment]
Added for the next release. You can now supply a `getFrontEndJsVariables()` function that defines the JS file that contains the scripts you require. This is the same behaviour as Payment, Captcha and AddressProvider integrations, alongside fields that require JS for functionality.

```php
public function getFrontEndJsVariables($field = null): ?array
{
    return [
        'src' => Craft::getAlias('@web/js/example-integration.js'),
        'module' => 'MyIntegration',
        'settings' => [],
    ];
}
```

Here, we tell Formie to load the file `js/example-integration.js` (in your webroot), and to look for a JS class in that file named `MyIntegration`. This is so that Formie's JS will lazy-load this script, rather than do it on render, before the form is potentially ready. It's also good for performance. We also supply a blank settings object, to tell Formie's JS to add some extra JS context to the JS class (optional).

The content in your `js/example-integration.js` file would look something like:

```js
window.MyIntegration = class {
    constructor(settings = {}) {
        console.log(settings)
    }
}
```

Which of course you're free to add whatever you like to that. Hopefully that helps in your scenario?

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
