### ISSUE TITLE
Trying to get asset filename in EVENT_AFTER_SUBMISSION event

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/formie#67]
**Description**
I'm trying to get the filename of an uploaded asset in the `EVENT_AFTER_SUBMISSION` event but I can't seem to be getting it. It looks like the `$submission->assetField` is an `AssetQuery` but when I try `$submission->assetField->one()->fileName` I'm getting
`yii\base\ErrorException: Trying to get property 'fileName' of non-object `.

I'm using the event like this:
````
        Event::on(Submissions::class, Submissions::EVENT_AFTER_SUBMISSION, function(SubmissionEvent $event) {
          $submission = $event->submission;
          $success = $event->success;
````

**Steps to reproduce**
1.
2.

### Form settings
Please pick from the options below.

- Multi-page form: Yes 
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes 

**Additional info**
- Plugin version: 1.1.7
- Craft version: 3.5.5
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
So yes, the field value will be an AssetQuery, just like a regular Asset field in Craft. I suppose it depends if there are validation errors, and it's best to check against those.

For instance, I've just tried the following which works as expected:

```
Event::on(Submissions::class, Submissions::EVENT_AFTER_SUBMISSION, function(SubmissionEvent $event) {
    $submission = $event->submission;
    $success = $event->success;

    $asset = $submission->fileUploadField->one() ?? null;

    if ($success && $asset) {
        Craft::dd($asset->filename);
    }
});
```

Also, and I don't think this is the error, it's `filename`, not `fileName`.

Can you try to deduce what `$submission->assetField->one()` is? It's saying it's a non-object, but I'd expect this to report back that it's `null`, if there was an issue with the file upload.

**Comment by bleepsandblops** [comment]
Thanks for looking into this.

Could it be that the event triggers before the file has finished uploading? As If I do:
````
          if ($success && $asset) {
              Craft::dd($asset->filename);
          } else {
            Craft::dd($submission->uploadYourPortfolioCv->one());
          }
````
The ajax query ends up showing 'null', and if I look at uploaded files, it's not there. If I remove the else clause though, it finishes the submission and I can see the file. (but the filename still doesn't get returned). So this to me points to the idea that at this point in the php, the file hasn't uploaded yet...

I was using a DO spaces location, and have also tried a local folder, same result.

**Comment by engram-design** [comment]
I'll double check what might be going on here, but it just strange that I can get the resulting asset okay. I'll double check the firing of this event.

If you can also update to [1.1.8](https://github.com/verbb/formie/releases/tag/1.1.8), I made a tiny adjustment to a potential issue with a stuck submission, that I came across when  testing this. I don't think It'll fix it, but always worth a short. Will keep looking into it.

**Comment by engram-design** [comment]
Have just put together a quick video showing what's happening on my end - https://d.pr/v/N2JbYU - anything I'm doing incorrectly compared to you? This was a 6mb image.

Only thing I haven't tested is a non-local volume.

I will make the point that the `Submissions::EVENT_AFTER_SUBMISSION` will fire whether the submission was successful or not, so you should always be checking against `success`. For example, if the submission was marked as spam by one of the captchas, or Formie's spam policies, this will still run, but `success = false`. This allows subscribers of this event to modify this behaviour and mark an unsuccessful submission as successful, and vice-versa.

Depending on what captchas you have enabled, or the spam policy, it might be marking it as spam? Although the submission seems to be getting created, so that might not be the issue.

The File Upload field also extends Craft's own Assets field, so we're deferring a lot of behaviour to how Craft normally handles assets.

**Comment by bleepsandblops** [comment]
Really appreciate the video, let me try and replicate it on my environment in a different form and see what happens.

**Comment by engram-design** [comment]
Any luck with this one and trying to replicate?

**Comment by bleepsandblops** [comment]
So sorry @engram-design I have not, the client has decided they did not want that file upload field in the end and so have not pursued it. I'll try and replicate on a new env possibly at some point, but maybe you'd like to close the issue for now?

**Comment by engram-design** [comment]
No problem, I'll keep an eye on it and continue testing on my end.
