### ISSUE TITLE
GraphQL - Handle multi-page form submissions by returning submissionId and introducing isIncomplete attribute

### ISSUE THREAD

**Issue by toddpadwick** [verbb/formie#671]
**What are you trying to do?**
We have a multi-page form in a headless set up. As it's a long form, some users may not reach the end but we'd still like to ensure we capture their emails and basic data that's requested at the start. We're using GQL to handle form submissions but it looks like you don't support this yet according to [this comment in your code](https://github.com/verbb/formie/blob/craft-3/src/gql/resolvers/mutations/SubmissionResolver.php#L102).

This would be a fantastic improvement for us enabling Formie to be used for lots of more dynamic, interactive multi-step campaigns which we've had to build from scratch in the past. 

**What's your proposed solution?**
submit a form page and receive the submission id in its response. 
Have the ability to set `isIncomplete` to true if the page is not the last.
use the submission id to append data to the same submission on the following form pages
if the last page is submitted, we'll set `isIncomplete` to false.

**Additional context**
We're using GraphQL with Apollo, Vue JS and Nuxt.

**Comment by engram-design** [comment]
This will probably come in 1.6.0 when we change the behaviour of how forms are submitted.

Right now, we rely on sessions to maintain the current page of a form, which in hindsight probably isn't ideal, because it assumes the state of the submission is the same across both client and server, which we know these days is a problem with headless sites.

Instead, we'll change the behaviour to pass in a `pageIndex` or `pageId` attribute for **every** submission to the `formie/submissions/submit` endpoint so that we're telling Formie what page we're submitting (and therefore what data to validate) for multi-page forms. Single-page forms likely won't have this at all, because it doesn't matter.

However, because this is a change in behaviour with submissions, and something **very** important to Formie, I'll need some time to test this out properly, and identify any issues, particularly with backward compatibility. 

This change will then be pushed to GraphQL mutations as well. I could potentially implement a stop-gap before then, but I'll see how many people require this, and the timing of 1.6.0 next year. Otherwise, will just be doing extra work _just_ for GQL that will be binned in the future.

**Comment by engram-design** [comment]
Added for the next release. You can now do something like the following:

```gql
// Query
mutation saveSubmission($id:ID, $isIncomplete:Boolean) {
    save_myForm_Submission(id: $id, isIncomplete: $isIncomplete) {
    	id
    }
}

// Query Variables
{
    "id": null,
    "isIncomplete": true
}
```

Would be what you want for your first page. You'll want to record the `id` that you get back for subsequent requests. For the last page, you can do:

```gql
// Query
mutation saveSubmission($id:ID, $isIncomplete:Boolean) {
    save_myForm_Submission(id: $id, isIncomplete: $isIncomplete) {
    	id
    }
}

// Query Variables
{
    "id": 1234,
    "isIncomplete": false
}
```

To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.11](https://github.com/verbb/formie/releases/tag/2.0.11)
