### ISSUE TITLE
Add option to disable scroll-to-top on multi-page forms

### ISSUE THREAD

**Issue by iDiegoNL** [verbb/formie#672]
**What are you trying to do?**
Since version 1.3.10, multi-page forms automatically [scroll to the top of the form
](https://github.com/verbb/formie/blob/580ae7cadecf4abb3e04723c65740d035eae6102/src/web/assets/frontend/src/js/formie-form-theme.js#L683) when continuing to the next page. In my experience, this can look either good or bad depending on the use case.
It would be awesome to see an option to toggle this behavior on/off in the form settings.

**What's your proposed solution?**
Adding an option to toggle scroll-to-top on/off in the form settings on the admin panel, or in the form rendering options.

**Additional context**

If there is any solution to (temporarily) bypass the scroll-to-top feature currently, please do let me know.

---

Possible implementations:

In the form settings on the admin panel:
![03h2lhdgy](https://user-images.githubusercontent.com/10339564/144754280-ef344db6-723d-47dc-ad7e-1bcba33b3809.png)

Or via a rendering option:
![Untitled-1(5)](https://user-images.githubusercontent.com/10339564/144754405-f33c16d2-28fa-41ef-a995-c812e13db9c5.png)

**Comment by engram-design** [comment]
Happy to add this option (to Appearance), the reason it does so by default is that this is triggered when:
- There's a submission error
- Submission was successful (and completed)
- Submission was successful, and navigated to the next page on a multi-page form
- Tabs (if shown) are clicked on

So for the most part, it's because there's an alert at the top of the form for error or success that you'd want to show users, but should totally be configurable.

Added in [1.4.28](https://github.com/verbb/formie/releases/tag/1.4.28)
