### ISSUE TITLE
craft.formie.submissions.form('myHandle') does not return submissions since the `1.4.28` update

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#674]
**Description**

`{{ craft.formie.submissions.form('myHandle').one() }}` does not returns any submission whereas there are at least one saved. `./craft resave/formie-submissions` + `./craft resave/formie-forms` does not fix this. This issue seems to occurs only for submissions of newly created forms since the `1.4.28` update.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.28
- Craft version: 3.7.23
- Multi-site: Yes

**Comment by engram-design** [comment]
I certainly can't replicate this in 1.5.0, by creating a brand-new form, making a submission and running:

```
{% dd  craft.formie.submissions.form('myHandle').one() %}
```

I can't see how this behaviour would've changed for that version. Does querying the submission directly via it's `id` work?

```
{% dd  craft.formie.submissions.id(1234).one() %}
```

And editing the submission in the control panel, it shows the form associated with the submission on the right-hand side?

**Comment by romainpoirier** [comment]
My ticket was opened under the 1.4.28 version. I'll try to update to the latest one, and will keep you update. Thank you.

**Comment by romainpoirier** [comment]
Unfortunately, after updating to `1.5.0` I get the same issue. FYI I am using `Craft Pro 3.7.23` version in a multi-sites env.

`{% dd  craft.formie.submissions.form('myHandle').one() %}` still returns nothing, even added at the top of the page, and while browsing the primary site on front-end, and while this handle can be browsed, edited, and get submissions in the control panel.

`{% dd  craft.formie.submissions.id(1234).one() %}` on the other side, returns something, and I can print the content of its fields values.

So there's only an issue using `craft.formie.submissions.form('myHandle')`.

**Comment by engram-design** [comment]
You mention a multi-site, which site was the submission made on? Are you fetching it for the correct site - if it was made on the non-primary site?

**Comment by romainpoirier** [comment]
The submissions are made from the primary website. And I'm trying to load the submissions from the primary website on front-end.

**Comment by romainpoirier** [comment]
Ok I think I've found the issue, there's a typo error:

- `craft.formie.submissions.form('myHandle').one()` is not working
- while `craft.formie.submissions.from('myHandle').one()` is

Following the documentation and your example, it should be `form` instead of `from`.

**Comment by engram-design** [comment]
Okay, worth checking about the site. And I think the typo might not be correct, because `from` is an invalid attribute on the SubmissionQuery object, so it's pretty much doing `craft.formie.submissions.one()` which will likely return something - the last submission made, which could be for _any_ form. It essentially discards `from()`.

Two things to try:

- `craft.formie.submissions.form(craft.formie.forms.handle('myForm').one()).one()`
- `craft.formie.submissions.formId(1234).one()`

**Comment by romainpoirier** [comment]
That's strange, because I can double confirm that `from` method returns something whereas `form` not (see first line):
- `craft.formie.submissions.form('myForm').one()`: returns `null`
- `craft.formie.submissions.from('myForm').one()` returns the first submission
- `craft.formie.submissions.form(craft.formie.forms.handle('myForm').one()).one()`: returns the first submission
- `craft.formie.submissions.formId(1234).one()`: returns the first submission

**Comment by engram-design** [comment]
Yeah, what I mean is that using `from` param for the query is the SQL `from` command that you'd use to lookup a database table. It doesn't throw an error, because it'll just fail silently ('myHandle' being a likely invalid database table for your site).

So interesting that using those last two work. Here's how we handle it

https://github.com/verbb/formie/blob/3c343d4da462394f2a3a0476457e03cada2194af/src/elements/db/SubmissionQuery.php#L40-L55

Where you can pass in a `Form` element, or a string as a handle to resolve to the correct Form. In both cases, all we want is the ID of the form, which you're setting manually in your last example.

Something like be clearly going wrong in:
```
$this->formId = (new Query())
                ->select(['id'])
                ->from(['{{%formie_forms}}'])
                ->where(Db::parseParam('handle', $value))
                ->scalar();
```

But I just can't replicate it on my end, which makes it difficult to know what's going on...

**Comment by engram-design** [comment]
One final thing to try it forcing the `siteId` for the query. with `siteId` below being the ID of the current site you're on, but also work checking all your other site IDs.

```
craft.formie.submissions.form('myHandle').siteId(1).one()
```

I'm otherwise at a bit of a loss!

**Comment by engram-design** [comment]
Any progress with this one? Not sure if it's related to https://github.com/verbb/formie/issues/679 ?

**Comment by romainpoirier** [comment]
Sorry for missing to answer. Under Formie `1.5.1` + Craft `3.7.25.1` it seems that I can't replicate the issue anymore. I can also confirm that `craft.formie.submissions.form('myHandle').siteId(1).one()` is working as expected.

**Comment by romainpoirier** [comment]
Wooops, sorry I hadn't tested correctly. Unfortunately, I'm still experiencing the issue under Formie `1.5.1` + Craft `3.7.25.1`.

I can also confirm that `craft.formie.submissions.form('myHandle').siteId(1).one()` still get an empty submission.

So currently I'm still sticking on this which works:
`{% set submission = craft.formie.submissions.form(craft.formie.forms.handle('myHandle').one()).one() %}`

**Comment by engram-design** [comment]
Thanks for confirming, this is such a weird one, but will look at it all with a clear head shortly.
