### ISSUE TITLE
More WYSIWYG options for notification body.

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#689]
**What are you trying to do?**
When adding tokens manually (because not all fields need to be shown in the e-mail to a client) it would be nice if we could have more layout options, such as a `table` and some headings.

We can use HTML inside the field, but I've noticed (especially with `table` elements) that this does not get rendered correctly.
Also, the field is not a HTML editor so it is slow to edit HTML inside of it.

**What's your proposed solution?**
Add Redactor options to the field.

**Comment by wmdhosting** [comment]
just info if it help >  there is https://plugins.craftcms.com/tinymce?craft4 
much better than redactor. 

![Snag_16b2ac49](https://user-images.githubusercontent.com/76176291/198316465-f5705c77-e5d3-4083-b688-c12547c3803b.png)

**Comment by engram-design** [comment]
Appreciate the suggestion, but we're not going to rely on a third-party Craft plugin to work with Formie - Redactor, TinyMCE, or otherwise. We'd also rather a bit more control (and give you all control) over the output, rather than storing HTML code, which is why we use [TipTap](https://tiptap.dev/) - which does support Table elements, just got to add support.

**Comment by engram-design** [comment]
I also want to clarify that there's plenty of formatting [options available](https://verbb.io/craft-plugins/formie/docs/get-started/configuration#available-buttons), but we'll add the Table buttons as an option.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/formie/releases/tag/3.0.0)
