### ISSUE TITLE
Single-line text inside group return 'No response.' in Email notification

### ISSUE THREAD

**Issue by watarutmnh** [verbb/formie#738]
**Description**
Single-line text field inside group field will return 'No response.' in Email notification when it have no value.
No issue with Multi-line text.

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**
- Plugin version: dev-craft-3 as 1.5.7
- Craft version: 3.7.30.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Looks like this is indeed incorrect, however for the Multi-Line Text. We think something like the below:

![image](https://user-images.githubusercontent.com/1221575/151527932-0d13392f-1536-45b5-ac0f-0baba34c3769.png)

Looks misleading because it looks to clients like there should be something there. This is the reason we've opted to include `No response.` in scenarios where no value was provided for a field, rather than showing "nothing" for the value. We could exclude the field heading if there is an empty value, but we've found clients saying "Why isn't my field X showing up in email notifications" only to explain it's because they didn't provide content for it in their submission.

Open to suggestions on your use-case and ideal AX for your clients and needs if this can maybe be handled another way? But just wanted to put forward that it's **correctly** showing `No response.`, and the issue is some fields **aren't**.

**Comment by watarutmnh** [comment]
@engram-design
Thank you for the explain. 

In my opinion, I prefer empty value instead showing 'No response'.
Since we can set field required or make it just an option, we don't need to care so much I think.

I am afraid that 'No response.' might misleading clients to think they got some errors.
And we don't know how the form to be used. If there is special cases where 'No response'is the specific answer for the field.

How do you think?
At least if it's consistent, I think it's okay to explain to the client.

**Comment by engram-design** [comment]
I agree with all your points, and something we've thought over a few times - especially if "No response" is an actual option.

In any case, we've just pushed some fixes to at least make this consistent. Now everything will show "No response." when empty.

If you'd like to remove this I'd suggest looking at [static translations](https://craftcms.com/docs/3.x/sites.html#static-message-translations) to change this on your site. Providing a file at translations/jp/formie.php with the following content should do the trick. Note you'll need to use the appropriate language value for your site.

```
<?php

return [
    'No response.' => '',
];
```

That way, if we decide to revisit this in the future to remove that, you'll be no worse off, and not require any changes.

**Comment by watarutmnh** [comment]
Thank you for the understanding and for suggesting an alternative. I'll do with a translation file.

**Comment by engram-design** [comment]
I'll very likely make this configurable in some fashion within Formie settings, so will tag that for a future release.

**Comment by watarutmnh** [comment]
`'No response.' => '',`
It still outputs 'No response'

I had to put a single space instead empty string to the trick works.
`'No response.' => ' ',`

**Comment by engram-design** [comment]
Added a config setting for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/formie/releases/tag/2.0.9)
