### ISSUE TITLE
Feature to remove uploaded file link in Email Notification.

### ISSUE THREAD

**Issue by watarutmnh** [verbb/formie#743]
**What are you trying to do?**
Regardless of whether the uploaded files have public URLs enabled or not, a link to the file will be added to Notification email content (using field variable), It is good for admins but not for public user.

**What's your proposed solution?**
I wish to have option in somewhere in advanced tab on 'Edit Notification' which I can configure removing the links for the files or not.

**Comment by engram-design** [comment]
I'm thinking that each field probably needs a setting to exclude from email notifications.

**Comment by watarutmnh** [comment]
That one also nice feature but it won't satisfy my needs. I wanted to have separate notifications between admins and users.

For alternative way, I created a Email template and put this code in to strip <a>tag.

`{{ contentHtml|striptags('<br><p><strong><ul><li>')|raw }}`

**Comment by watarutmnh** [comment]
I wasn't sure about template. file-upload.html was only thing I had to alter.

**Comment by engram-design** [comment]
So just so I'm clear on what you want - you have "All Fields" as a variable token in both your email notifications (for both client and user notifications). One field in your form is a file upload field, and in the email notification, it'll output the URL (if it has a public URL) or the filename of the asset(s) that are uploaded.

Are you saying you'd like to completely remove the reference to the asset(s) for just the client email, so it doesn't get shown?

If that's the case, I'm not sure if I'll add a setting to control that, because I'd probably have to add a setting for **every** field type which would get messy.

I would override the field template for the email notification - as you have - overriding _just_ the `file-upload.html` file. I would add the following content:

```
{% if notification.handle == 'clientNotification' %}
    My custom file upload template
{% else %}
    {# Render the default Formie `file-upload` template #}
    {{ formieInclude('fields/file-upload') }}
{% endif %}
```

Here, we're checking if the notification handle is our client form, add some custom template, if not, default back to what Formie provides. I would also recommend to create an Email Template so you could check against that, rather than relying on the handle of a single email notification. That way if you have several forms where you'd like this applied, you can use the email template for all your client email notifications.

**Comment by watarutmnh** [comment]
I agree that it is appropriate to use a template instead adding a setting feature.
I will deal with it by the method on your advice.

**Comment by engram-design** [comment]
I'll give this some further thought on if we can make this better as well.
