### ISSUE TITLE
Checkbox option values showing in email notifications instead of the checkbox option labels

### ISSUE THREAD

**Issue by Martinovdz** [verbb/formie#756]
**Steps to reproduce**
1. Add "Checkboxes" field to a form
2. Add options to the "Checkboxes" field
3. Add an email notification
4. In the "Email Content" field add the newly added "Checkboxes" field through the + icon (variables)
5. When sending or previewing the email the value of the checkbox is shown instead of the label of the checkbox

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.9
- Craft version: 3.7.32
- Multi-site: Yes

**Additional context**
<img width="507" alt="image" src="https://user-images.githubusercontent.com/9590628/153850193-2075da9e-364e-4f93-83a1-9a40d41b339d.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/9590628/153850245-945317d5-82d7-4221-b81a-9c98d97a39a4.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/9590628/153850454-717b20e7-74bd-49f8-9af9-4461ccdc9c61.png">

**Comment by engram-design** [comment]
So this is correct behaviour, at least for the moment, that when outputting values of option-based fields (Dropdown, Checkboxes, Radio) will show their option values instead of their option labels. I can see use-cases for both, as labels can be more client-friendly (and what clients see when filling out the form), but the option values can be different to the label.

I'll give this some further thought to make this configurable per-field. For now you can override the email template used by these fields to use the label instead of the value. This will otherwise be a breaking change.

For example, a `checkboxes.html` file in the email notifications could be:

```
<p>
    {% if not (options.hideName ?? false) %}
        <strong>{{ field.name | t }}</strong><br>
    {% endif %}

    {% if value | length %}
        <ul>
            {% for item in value %}
                <li>{{ item.label }}</li>
            {% endfor %}
        </ul>
    {% else %}
        {{ 'No response.' | t('formie') }}
    {% endif %}
</p>
```

Which is only a minor change from the default: https://github.com/verbb/formie/blob/craft-3/src/templates/_special/email-template/fields/checkboxes.html

**Comment by Martinovdz** [comment]
Hello

We used to override the checkboxes.html template for our email templates.
However, we found out that this setup used to work up until ~ March 2021. After that our emails reverted back to showing the checkbox values instead of the label so it seems like overriding the field templates is no longer working or we are using it the wrong way. (we only discovered this recently, but it has been broken for almost a year now)

After further testing we noticed that the overriding of the checkboxes.html only works when using the "All Form Fields" option from the variables dropdown in the email notification - email content

This is how we have it set up:

structure:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/9590628/154658679-ed9064dc-9cca-4935-8ef8-dcde60db119b.png">

index.html:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/9590628/154658727-9271c74d-5ce5-4c4b-a967-99e418ff4773.png">

checkboxes.html:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/9590628/154658776-36a35743-e632-4514-86f6-cb37314359fd.png">

email template:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/9590628/154660754-caa109a3-f2a7-4e07-918c-f5399248bea0.png">

form:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/9590628/154659301-c72a8dd0-3b84-4a0f-a661-6b608d1e6173.png">

email notification content:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/9590628/154659763-24ec2fa2-efed-4a18-a875-2dd41fe1d0da.png">

email notification email template:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/9590628/154661029-628a1562-14ac-4369-83b9-2deea9c1c7d9.png">

email result:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/9590628/154659974-d8ed39dc-1cef-4daa-879a-f85c0a08e280.png">

**Comment by engram-design** [comment]
I can't recall a time where the label of options would've been used, but as that was about a year ago, my memory would be a bit hazy on that. Regardless, changing it back would annoy more people (again) who are used to it. As I've mentioned, will give this some further thought to ensure we're meeting everyone's needs.

Good point on the single-use of the field. Due to this, I've come up with a better solution using events, which while I'm trialling just for Checkboxes, will eventually be the go-to method of modifying email content for fields going forward. Your request just brought this forward a little.

First, grab the latest changes by changing your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.9",
  "...": "..."
}
```

Then run `composer update`. You will be able to use the following event to change the values used in email notifications for Checkboxes fields.

```
use verbb\formie\fields\formfields\Checkboxes;
use verbb\formie\events\ModifyFieldEmailValueEvent;
use yii\base\Event;

Event::on(Checkboxes::class, Checkboxes::EVENT_MODIFY_VALUE_FOR_EMAIL, function(ModifyFieldEmailValueEvent $event) {
    // Fetch the raw value again, from the submission (`craft\fields\data\MultiOptionsFieldData`)
    $submissionValue = $event->submission->getFieldValue($event->field->handle);
    
    // Overwrite the value in emails to use labels instead of values
    $event->value = implode(', ', array_map(function($item) {
        return $item->label;
    }, (array)$submissionValue));
});
```

You will still need your custom HTML template, which only modifies the "All Fields" (and similar) behaviours.

Sorry for the hassle, hopefully this won't be needed in the coming versions, but being able to pick labels/values likely won't appear until 1.6.0.

**Comment by Martinovdz** [comment]
Thanks a lot for the workaround! Closing this issue.
