### ISSUE TITLE
Sometimes phone number validation is ignored

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#757]
**Description**
I've sent screencasts to the support address to better understand the issue.

**Steps to reproduce**
1. Set up a multi-pages form
2. Fill in a random phone number (example: using [Fake Filler](https://chrome.google.com/webstore/detail/fake-filler/bnjjngeaknajbdcgpfkgnonkmififhfo?hl=en)), which can content spaces and parenthesis
3. Fill in the page, sometimes you'll see errors showing up under the fields, but the form is still submitting like it's ignoring it
4. Get back to this page, try to submit again, then you'll finally be stopped by the validation errors

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.9
- Craft version: Craft Pro 3.7.32
- Multi-site: Yes

**Comment by engram-design** [comment]
I'm struggling to replicate this one I'm afraid. I'm wondering if you can shoot through your entire project (including templates, JS, etc) to see if I can replicate it?

Thanks for your screencasts - they indeed show that even though validation is correctly triggered, the form continues with the submit, which is something that shouldn't be possible.

Out of interest, if you try and submit the form with a required field un-filled, does the page get submitted as well?

**Comment by romainpoirier** [comment]
I have sent you the files by email.

Yes it's like the phone validation is sometimes ignored. As you can see, I can also replicate it from the CP.

If there's a missing required phone number field, I can't submit: the required validation is working.

**Comment by engram-design** [comment]
Interesting, so there must be something going on the with custom validation that field adds to our validator, which granted is a little different to "normal" validations (required, max length, etc), which comes from the `intl-tel-input` library. 

That at least gives me a direction to go on.

**Comment by engram-design** [comment]
I can't seem to reproduce the issue of when validating the field, it preventing submission, but there must be some sort of race condition happening. We add custom validations via https://github.com/verbb/formie/blob/craft-3/src/web/assets/frontend/src/js/fields/phone-country.js#L117-L129 in much the same way as other fields https://github.com/verbb/formie/blob/craft-3/src/web/assets/frontend/src/js/fields/file-upload.js#L12-L28 which as I've mentioned is different to the native browser validation such as required.

But the numbers you're showing being pre-filled via Fake Filler (which I've also tested) and technically invalid (using https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html to validate the following):

- +1 (191) 825-9314
- +1 (106) 871-2612 

So the real issue is trying to figure out **how** page submission occurs despite these validations kicking in.

Is this a consistent or sporadic issue? Can you check to see if there's any console errors next time it happens? Otherwise, I may have to add some debug logging to the JS for the validator and get you to try to reproduce the series of events leading to this.

**Comment by romainpoirier** [comment]
Thank you for all of these explanations.

So you've finally found that despite they look like valid, these phone numbers were in fact invalids ones.

It seems a sporadic issue, and still have to understand the logic behind that. I will check the console, but as far as I now there weren't.

Let say that we can close this issue. I'll update later if I still got it, after setting Fake Filler to only valid phone numbers.

**Comment by engram-design** [comment]
The numbers totally _look_ valid, but they must be invalid according to US country data. Glad you can change that to your needs.

But yeah, the real issue is that an invalid phone number is not preventing form submissions. I cannot - no matter what I do - replicate that, but if it happens again, do let me know and we'll see how we can debug it further.
