### ISSUE TITLE
Unable to find any ReCAPTCHA placeholder.

### ISSUE THREAD

**Issue by pbmills** [verbb/formie#760]
**Description**
I am getting this Unable to find any ReCAPTCHA placeholder.

**Steps to reproduce**
1. 
2.

### Form settings
Please pick from the options below.

- Multi-page form:  No
- Submission Method: Ajax 
- Client-side Validation:  No
- Custom Form Templates: Yes
<img width="775" alt="Screen Shot 2022-02-17 at 6 03 55 PM" src="https://user-images.githubusercontent.com/31907075/154409114-fe433cec-f26c-4449-815a-ff29f41aecb6.png">

**Additional info**
- Plugin version: 1.5.9
- Craft version: 3.7.33
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
This is normal for a multi-page form, but as you mention this isn't one, it should find it.

You mention you're using custom form templates, and sounds like you might need to check if you're including `{% hook 'formie.buttons.before' %}` so that the captcha HTML is output? https://verbb.io/craft-plugins/formie/docs/template-guides/custom-rendering

**Comment by pbmills** [comment]
Well, it is showing me recaptcha-v2-checkbox.js error in console
________________________________

**Comment by pbmills** [comment]
Worked yay!
