### ISSUE TITLE
Conditional Bug - not hiding field when conditional isn't met.

### ISSUE THREAD

**Issue by cherrykoda** [verbb/formie#804]
**Description**

Conditional on checkbox field is not working, however the markup appears as expected.

**Steps to reproduce**
1. Create a form that does not use Formie's built-in style sheet ("Appearance" menu)
2. Create a drop down field
3. Create a checkbox field
4. Set a conditional to hide the checkboxes unless the dropdown meets a specific value (see images below)

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Default
- Custom Form Templates: No

NOTE: Formie styles are disabled, and are relying on site styling.

**Additional info**
- Plugin version: 1.5.11
- Craft version: 3.7.37
- Multi-site: No

**Additional context**

Form Setup Images:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/3789834/159413740-72e89204-a7b9-454c-85e9-52af490c9b6b.png">

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/3789834/159413803-ec346513-44f3-46b6-a210-517c808b8bef.png">

Markup as it appears when the conditional field is not "Yes":

<img width="560" alt="image" src="https://user-images.githubusercontent.com/3789834/159413928-5d24691b-9ede-497c-ad7c-fa3adb1e12f2.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/3789834/159413886-a2658f43-7562-4c18-babc-618f5fb7cf8b.png">

**Comment by engram-design** [comment]
Hiding fields are done via CSS for flexibility, rather than through JS adding `display: none` style attributes on classes. However, if you're not loading the Formie theme or base CSS, then you'll need to apply this yourself as part of your BYO CSS. 

https://github.com/verbb/formie/blob/0683680433a5a38884f989d19a0b7c7aa936b081/src/web/assets/frontend/src/scss/formie-base.scss#L29-L37

FYI, this rule is included in the non-opinionated Base CSS, which you can include for the most part, as it's more structural than any opinionated styles. It's kept extremely minimal for this purpose.

**Comment by cherrykoda** [comment]
That worked, thanks!
