### ISSUE TITLE
Cannot save "hidden" or "disabled" in "visibility" option of fields

### ISSUE THREAD

**Issue by tremby** [verbb/formie#848]
**Description**

I cannot save a "hidden" or "disabled" value in field settings -> "appearance" -> "visibility" option of any field.

I was trying to determine how this option affects the GQL output and so was trying to set different visibility values on different fields. It looks like I get `null` when I haven't changed it ("visible"), and I was seeing `"1"` in another case, so went to see what it was set to. But I see a blank field. I then found that setting it to either "hidden" or "disabled" and then hitting save causes this state. And then GQL responds with `"1"` in either case, it seems, which is a weird value for something called "visibility" to represent either "hidden" or "disabled". I don't see any other field for "hidden" or "disabled".

**Steps to reproduce**
1. Make a form field
2. Go to its settings -> appearance
3. Set its visibility to "hidden"
4. Save the form
5. Look again at its appearance setting, see it is a blank box
6. Repeat with "disabled"

### Form settings
Please pick from the options below.

- Multi-page form: Yes
- Submission Method: Ajax or Page Reload - whatever default is
- Client-side Validation: Yes or No - whatever default is
- Custom Form Templates: Yes or No - whatever default is

**Additional info**
- Plugin version: craft-4 at ea11346
- Craft version: 4.0.x at 9d2c37d
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Yep, another type issue I completely missed.

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`. 

But good point that this will do nothing to GraphQL queries - it won't exclude the field from the query, but that's correct behaviour for `hidden`, but not `disabled`.  You can technically include disabled fields through template overrides [`getRows(false)`](https://github.com/verbb/formie/blob/5d8f15e58b44a23453df8b07d54ed60b712985d7/src/models/FieldLayoutPage.php#L131-L143), but generally speaking I'm not sure disabled fields will work in a headless scenario. It's really there for only using `craft.formie.populateFormValues()` to populate the fields that are disabled via Twig which can be totally hidden from inspection in the HTML and payload sent to the server (they're never sent). But due to the detached nature of headless, that won't be possible.

**Comment by tremby** [comment]
I didn't fully follow your response there. To be clear, at this stage I'm still just trying to make sure I can get everything I need via GQL, and that I understand exactly what everything is -- what settings change what outputs.

Since your change I'm getting `visibility: null` for visible, `visibility: "hidden"` for hidden, and `visibility: "disabled"` for disabled. All as expected? I do find `visibility: null` to mean "visible" to be a little weird but it's not a big deal.

I take it "disabled" is meant to mean the form field is visible to the user but it has the `disabled` attr so it's not interactive and doesn't submit its value. Is that right?

**Comment by engram-design** [comment]
Yeah, I probably should change that to an enum type at some point, but Formie assumes that things are visible by default, hence the `null` as we just check if `visibility == "hidden" or visibility == "disabled"`. I could easily change that just for GraphQL where it's more exposed.

So `hidden` means that it should be still in the HTML source, but just invisible to users. `disabled` actually means to not output it at all on the page, but you can use [`craft.formie.populateFormValues()`](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms) to set the values for the fields in your Twig templates. This means that the field exists in the form, but it can't be tampered with, or seen in the payload when submitting the form. As I mentioned, this really is only possible with Twig.

**Comment by tremby** [comment]
Ah. Right, I see. So it doesn't mean `<input disabled>`, it means don't even render the field.

That means I should be filtering out any fields with `visibility: "disabled"`.

You seemed to say above that them being included in the query response was not correct behaviour for "disabled" -- is that something you're going to change, or should I add in some code to filter those out?

Incidentally, how do you handle "hidden" on the front end? Do I ignore the field type and render out a `<input type="hidden">`, or what's the idea?

**Comment by engram-design** [comment]
Yeah, "disabled" from rendering would be a better term. And I _might_ change that to be the default behaviour for GraphQL queries if I can figure that out! It is the default behaviour for Twig templates. But it does mean that it'll be impossible to set content for those fields (as the query to fetch the fields won't know about them, so you won't be able to send the values in your payload to the server).

You can totally include them in the payload to set them. It's really only a setting that's going to be applicable for a more traditional server-side rendered page with Twig. It's otherwise a useless setting for headless, unless you want to treat disabled fields differently, which of course you're able to do.

We actually add a `.fui-hidden` class to the wrapper `.fui-field` container (because fields can be more than a single input, different types of inputs, different components), so that there's freedom for a developer to handle that their own way. So in your scenario, you can treat it however you like - a hidden input would do, hide the wrapper around your fields' HTML, or just omit them from render altogether (unless you want to populate those hidden field in some way on your front-end).

**Comment by tremby** [comment]
OK, thanks for all that. As far as I'm concerned this is fixed, though I'll leave this open in case you wanted it as a reminder to maybe remove disabled fields from the GQL response.

**Comment by tremby** [comment]
Actually I'll open another, since the title of this one doesn't describe the remaining issue.
