### ISSUE TITLE
Duplicate fields are available in "Existing fields"

### ISSUE THREAD

**Issue by Saboteur777** [verbb/formie#934]
**Description**
When creating forms using stencils, multiple instances of the same field are available in the **Add Existing Field** modal: 

![kép](https://user-images.githubusercontent.com/9061795/172858724-ffbbff70-ccb0-452b-8db2-aa815ed3d92f.png)

Is this intentional?

**Steps to reproduce**
1. Create a stencil with some fields. 
2. Create a form using that stencil.
3. Create another form and click on Add existing fields button in the right sidebar. 

**Additional info**
- Plugin version: 1.5.19
- Craft version: 3.7.44
- Multi-site: No

**Comment by engram-design** [comment]
That would be correct behaviour, as a stencil is just a starter. Each time you create a new form, it creates new fields, hence you'll have duplicates. There's not really a global field instance concept with Formie (other than synced fields), because once a form is created from a stencil, it just becomes a regular form.

**Comment by Saboteur777** [comment]
Okay, thank you for the explanation!
