### ISSUE TITLE
Trivy Vulnerability Scanning failed because of package dompdf/dompdf

### ISSUE THREAD

**Issue by xinningsu** [verbb/formie#972]
### Question

<img width="955" alt="image" src="https://user-images.githubusercontent.com/7017728/177514338-7a9fa0cf-6148-4530-a0ea-c311b1e3eebc.png">

Maybe it's time to upgrade `dompdf/dompdf` to 2.0? thanks.

**Comment by engram-design** [comment]
This is a low risk (as stated), and it's kept at the same version as Commerce (v3) just to prevent version incompatibility. At least for the Craft 3 version of Formie. But if [this](https://github.com/craftcms/commerce/pull/2879) is anything to go by, we'll be making the change for Formie v2.

**Comment by engram-design** [comment]
Addressed in [2.0.1](https://github.com/verbb/formie/releases/tag/2.0.1), but you'll still receive this warning if you have Commerce installed, due to their requirement not meeting v2.0.0 of `dompdf/dompdf` yet. But when they [merge](https://github.com/craftcms/commerce/pull/2879) to required update, the warning will go away.
