### ISSUE TITLE
No Repeater JS output in no-cache tag

### ISSUE THREAD

**Issue by pl-mnm** [verbb/formie#992]
### Describe the bug

When the Formie tag is rendered inside a [no-cache](https://plugins.craftcms.com/nocache) tag, then the `<script type="text/x-template">` tags for Repeater fields are missing from the HTML, rendering the repeater button unusable when cache is enabled.

### Steps to reproduce

1. Install the `no-cache` plugin and wrap it around the form output
2. Create a `Repeater` field in the Formie CP form
3. Make sure Craft cache is enabled

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.45

### Plugin version

1.6.3

### Multi-site?

No

**Comment by engram-design** [comment]
While I've not used that plugin, it should be no different to how to handle regular [cached forms](https://verbb.io/craft-plugins/formie/docs/v1/template-guides/cached-forms). In Craft 3, CSS/JS is not cached alongside HTML.

**Comment by rungta** [comment]
Hi @engram-design,

We’re using full-page caching (via [CacheFlag](https://github.com/mmikkel/CacheFlag-Craft3)) but wrapping the entire Formie code in the [`{% nocache %}`](https://plugins.craftcms.com/nocache) tag. Since all the Formie code is now _outside_ the cached content, CSRF tokens, CSS and JS all work okay. The CSS output location is set to _Manual_ while the JS output location is set to _Inside Form_. The template code is [roughly](https://github.com/miranj/craft-boilerplate/blob/master/templates/_layouts/html.twig) something like this:

```twig
{% cacheflag %}
  <html>
    <head>
      ...
    </head>
    <body>
      ...
      {% nocache %}
        {% set form = craft.formie.forms().id(formId).one() %}
        {{
          craft.formie.renderForm(form)
          |prepend(craft.formie.renderFormCss(form))
        }}
      {% endnocache %}
    </body>
  </html>
{% endcacheflag %}
```

All the CSS and JS (base, theme, field-specific) does get rendered in the right place alongside the form tag. The only exception seems to be the `<script type="text/x-template">` tags from the repeater fields which, when template caching is disabled, are rendered at the end of the page, and when template caching is enabled, do not get rendered at all.

**Comment by engram-design** [comment]
Table and Repeater JS is somewhat special, mostly due to handling Vue and other frameworks that don't really like inline JS. Otherwise, all CSS and JS is rendered through normal means through Craft's `register` asset methods for CSS/JS.

You can include the `includeScriptsInline` render option to have the `<script>` rendered inline, if that helps?

```twig
{{ craft.formie.renderForm(form, {
    renderOptions: {
        includeScriptsInline: true,
    },
}) }}
```

**However** even without this change, because we're also using `{% script %}` it's _supposed_ to act the same way as Craft's asset registration, to render it at the end of the page, along with other scripts. I'd have to look into the specifics of what these plugins are doing differently that causes this behaviour.

https://github.com/verbb/formie/blob/5b53f26e64b853515729bdd8d5d02753e27f5ad6/src/templates/_special/form-template/fields/repeater/index.html#L57-L78

**Comment by rungta** [comment]
Changed to
```
{{
  craft.formie.renderForm(form, {
    renderOptions: {
      includeScriptsInline: true,
    },
  })
  |prepend(craft.formie.renderFormCss(form))
}}
```
… but no difference in the output (even with template caching completely turned off). I then tried adding a debug statement in line 56 here but the value of `includeScriptsInline` is reported as `false`, not `true`. https://github.com/verbb/formie/blob/5b53f26e64b853515729bdd8d5d02753e27f5ad6/src/templates/_special/form-template/fields/repeater/index.html#L55-L57 

What are we doing wrong?

**Comment by engram-design** [comment]
@rungta Are you on Formie v1 or v2, like the OP?

**Comment by rungta** [comment]
Formie v1. We’re both talking about the same project. @pl-mnm works with us at Miranj. :)

**Comment by engram-design** [comment]
Gotcha, just didn't want to assume. Sorry, my mistake, the syntax is:

```twig
{{ craft.formie.renderForm(form, {
    includeScriptsInline: true,
}) }}
```

**Comment by rungta** [comment]
That did it! Thanks again Josh. 😃
